In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"C:\Users\Anish Kumar\Downloads\store_sales_data.csv")
df.head(5)

,Customer ID,Customer Name,Last Name,Date of Birth,Sales,Year,Outlet Type,City Type,Category of Goods,Region,...,Ship Date,Ship Mode,State,Postal Code,Product ID,Sub-Category,Product Name,Quantity,Discount,Profit
0,CUST000001,Curtis,Krause,1973-11-29,3344.69,2023,Large,Tier 1,Fast Food,East,...,2020-04-18,Same Day,West Bengal,700001,PROD000001,Burgers,Burgers - 718,3,0.09,448.24
1,CUST000002,Jeremy,Foster,1987-08-30,37094.41,2022,Medium,Tier 2,Fast Food,East,...,2021-01-11,Standard Class,Punjab,160001,PROD000002,Pizzas,Pizzas - 519,5,0.39,3134.34
2,CUST000003,Ariel,Mccann,1980-12-15,35501.08,2023,Large,Village,Electric Appliances,South,...,2020-08-16,Second Class,Gujarat,380001,PROD000003,Fans,Fans - 395,6,0.07,8324.21
3,CUST000004,Colleen,Maynard,1989-05-23,8969.33,2021,Medium,Village,Dairy Products,East,...,2021-10-16,First Class,West Bengal,700001,PROD000004,Milk,Milk - 798,4,0.18,1962.66
4,CUST000005,Gina,Holden,1957-12-31,35530.44,2021,Small,Village,Sessional Fruits & Vegetables,West,...,2019-01-25,Standard Class,Delhi,110001,PROD000005,Tomatoes,Tomatoes - 442,4,0.27,2843.93

In [3]:
df.tail(5)

,Customer ID,Customer Name,Last Name,Date of Birth,Sales,Year,Outlet Type,City Type,Category of Goods,Region,...,Ship Date,Ship Mode,State,Postal Code,Product ID,Sub-Category,Product Name,Quantity,Discount,Profit
99995,CUST099996,Thomas,Adams,2018-02-02,254.35,2020,Large,Tier 1,Furniture,East,...,2019-02-05,First Class,Gujarat,380001,PROD099996,Beds,Beds - 169,2,0.12,61.84
99996,CUST099997,Clifford,Dillon,1955-08-11,846.66,2019,Medium,Tier 2,Sessional Fruits & Vegetables,North,...,2020-04-09,Same Day,Rajasthan,302001,PROD099997,Tomatoes,Tomatoes - 291,1,0.43,118.60
99997,CUST099998,Kelly,Deleon,1991-02-27,12165.34,2019,Large,Tier 2,Furniture,East,...,2021-07-02,Standard Class,Maharashtra,400001,PROD099998,Chairs,Chairs - 381,4,0.13,2100.20
99998,CUST099999,Katie,Moses,1990-10-21,41242.99,2019,Small,Tier 1,Fast Food,North,...,2019-08-01,Second Class,Karnataka,560001,PROD099999,Sandwiches,Sandwiches - 961,4,0.41,4674.57
99999,CUST100000,Jeremy,Combs,2016-12-27,47402.45,2019,Medium,Village,Fast Food,North,...,2020-02-24,Same Day,Maharashtra,400001,PROD100000,Burgers,Burgers - 611,5,0.32,8490.54

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Customer ID        100000 non-null  str
 1   Customer Name      100000 non-null  str
 2   Last Name          100000 non-null  str
 3   Date of Birth      100000 non-null  str
 4   Sales              100000 non-null  float64
 5   Year               100000 non-null  int64
 6   Outlet Type        100000 non-null  str
 7   City Type          100000 non-null  str
 8   Category of Goods  100000 non-null  str
 9   Region             100000 non-null  str
 10  Country            100000 non-null  str
 11  Segment            100000 non-null  str
 12  Sales Date         100000 non-null  str
 13  Order ID           100000 non-null  str
 14  Order Date         100000 non-null  str
 15  Ship Date          100000 non-null  str
 16  Ship Mode          100000 non-null  str
 17  State              100000 non-null  str
 18  Postal Code        100000 non-null  int64
 19  Product ID         100000 non-null  str
 20  Sub-Category       100000 non-null  str
 21  Product Name       100000 non-null  str
 22  Quantity           100000 non-null  int64
 23  Discount           100000 non-null  float64
 24  Profit             100000 non-null  float64
dtypes: float64(3), int64(3), str(19)
memory usage: 19.1 MB

In [5]:
df.describe()

,Sales,Year,Postal Code,Quantity,Discount,Profit
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,25084.410142,2020.999910,388985.180000,5.493760,0.251320,3755.305114
std,14403.187686,1.413757,184192.704685,2.876102,0.144324,2639.852035
min,100.570000,2019.000000,110001.000000,1.000000,0.000000,6.520000
25%,12618.030000,2020.000000,226001.000000,3.000000,0.130000,1651.105000
50%,25134.695000,2021.000000,380001.000000,5.000000,0.250000,3317.450000
75%,37575.850000,2022.000000,560001.000000,8.000000,0.380000,5363.845000
max,49999.890000,2023.000000,700001.000000,10.000000,0.500000,14563.670000

In [6]:
df.columns

Index(['Customer ID', 'Customer Name', 'Last Name', 'Date of Birth', 'Sales',
       'Year', 'Outlet Type', 'City Type', 'Category of Goods', 'Region',
       'Country', 'Segment', 'Sales Date', 'Order ID', 'Order Date',
       'Ship Date', 'Ship Mode', 'State', 'Postal Code', 'Product ID',
       'Sub-Category', 'Product Name', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

### Data Type Change

In [7]:
date = [
    "Date of Birth",
    "Sales Date",
    "Order Date",
    "Ship Date"
]

df[date] = df[date].apply(pd.to_datetime)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Customer ID        100000 non-null  str
 1   Customer Name      100000 non-null  str
 2   Last Name          100000 non-null  str
 3   Date of Birth      100000 non-null  datetime64[us]
 4   Sales              100000 non-null  float64
 5   Year               100000 non-null  int64
 6   Outlet Type        100000 non-null  str
 7   City Type          100000 non-null  str
 8   Category of Goods  100000 non-null  str
 9   Region             100000 non-null  str
 10  Country            100000 non-null  str
 11  Segment            100000 non-null  str
 12  Sales Date         100000 non-null  datetime64[us]
 13  Order ID           100000 non-null  str
 14  Order Date         100000 non-null  datetime64[us]
 15  Ship Date          100000 non-null  datetime64[us]
 16  Ship Mode          100000 non-null  str
 17  State              100000 non-null  str
 18  Postal Code        100000 non-null  int64
 19  Product ID         100000 non-null  str
 20  Sub-Category       100000 non-null  str
 21  Product Name       100000 non-null  str
 22  Quantity           100000 non-null  int64
 23  Discount           100000 non-null  float64
 24  Profit             100000 non-null  float64
dtypes: datetime64[us](4), float64(3), int64(3), str(15)
memory usage: 19.1 MB

In [9]:
df.head()

,Customer ID,Customer Name,Last Name,Date of Birth,Sales,Year,Outlet Type,City Type,Category of Goods,Region,...,Ship Date,Ship Mode,State,Postal Code,Product ID,Sub-Category,Product Name,Quantity,Discount,Profit
0,CUST000001,Curtis,Krause,1973-11-29,3344.69,2023,Large,Tier 1,Fast Food,East,...,2020-04-18,Same Day,West Bengal,700001,PROD000001,Burgers,Burgers - 718,3,0.09,448.24
1,CUST000002,Jeremy,Foster,1987-08-30,37094.41,2022,Medium,Tier 2,Fast Food,East,...,2021-01-11,Standard Class,Punjab,160001,PROD000002,Pizzas,Pizzas - 519,5,0.39,3134.34
2,CUST000003,Ariel,Mccann,1980-12-15,35501.08,2023,Large,Village,Electric Appliances,South,...,2020-08-16,Second Class,Gujarat,380001,PROD000003,Fans,Fans - 395,6,0.07,8324.21
3,CUST000004,Colleen,Maynard,1989-05-23,8969.33,2021,Medium,Village,Dairy Products,East,...,2021-10-16,First Class,West Bengal,700001,PROD000004,Milk,Milk - 798,4,0.18,1962.66
4,CUST000005,Gina,Holden,1957-12-31,35530.44,2021,Small,Village,Sessional Fruits & Vegetables,West,...,2019-01-25,Standard Class,Delhi,110001,PROD000005,Tomatoes,Tomatoes - 442,4,0.27,2843.93

### Two column add

In [10]:
df["Full Name"] = (
    df["Customer Name"].fillna("") + " " +
    df["Last Name"].fillna("")
).str.strip()

In [11]:
df["Full Name"]

0          Curtis Krause
1          Jeremy Foster
2           Ariel Mccann
3        Colleen Maynard
4            Gina Holden
              ...
99995       Thomas Adams
99996    Clifford Dillon
99997       Kelly Deleon
99998        Katie Moses
99999       Jeremy Combs
Name: Full Name, Length: 100000, dtype: str

### Drop column

In [12]:
df = df.drop(columns=["Customer Name", "Last Name"])

In [13]:
df

,Customer ID,Date of Birth,Sales,Year,Outlet Type,City Type,Category of Goods,Region,Country,Segment,...,Ship Mode,State,Postal Code,Product ID,Sub-Category,Product Name,Quantity,Discount,Profit,Full Name
0,CUST000001,1973-11-29,3344.69,2023,Large,Tier 1,Fast Food,East,India,Consumer,...,Same Day,West Bengal,700001,PROD000001,Burgers,Burgers - 718,3,0.09,448.24,Curtis Krause
1,CUST000002,1987-08-30,37094.41,2022,Medium,Tier 2,Fast Food,East,India,Corporate,...,Standard Class,Punjab,160001,PROD000002,Pizzas,Pizzas - 519,5,0.39,3134.34,Jeremy Foster
2,CUST000003,1980-12-15,35501.08,2023,Large,Village,Electric Appliances,South,India,Consumer,...,Second Class,Gujarat,380001,PROD000003,Fans,Fans - 395,6,0.07,8324.21,Ariel Mccann
3,CUST000004,1989-05-23,8969.33,2021,Medium,Village,Dairy Products,East,India,Corporate,...,First Class,West Bengal,700001,PROD000004,Milk,Milk - 798,4,0.18,1962.66,Colleen Maynard
4,CUST000005,1957-12-31,35530.44,2021,Small,Village,Sessional Fruits & Vegetables,West,India,Consumer,...,Standard Class,Delhi,110001,PROD000005,Tomatoes,Tomatoes - 442,4,0.27,2843.93,Gina Holden
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,CUST099996,2018-02-02,254.35,2020,Large,Tier 1,Furniture,East,India,Corporate,...,First Class,Gujarat,380001,PROD099996,Beds,Beds - 169,2,0.12,61.84,Thomas Adams
99996,CUST099997,1955-08-11,846.66,2019,Medium,Tier 2,Sessional Fruits & Vegetables,North,India,Corporate,...,Same Day,Rajasthan,302001,PROD099997,Tomatoes,Tomatoes - 291,1,0.43,118.60,Clifford Dillon
99997,CUST099998,1991-02-27,12165.34,2019,Large,Tier 2,Furniture,East,India,Consumer,...,Standard Class,Maharashtra,400001,PROD099998,Chairs,Chairs - 381,4,0.13,2100.20,Kelly Deleon
99998,CUST099999,1990-10-21,41242.99,2019,Small,Tier 1,Fast Food,North,India,Consumer,...,Second Class,Karnataka,560001,PROD099999,Sandwiches,Sandwiches - 961,4,0.41,4674.57,Katie Moses
99999,CUST100000,2016-12-27,47402.45,2019,Medium,Village,Fast Food,North,India,Corporate,...,Same Day,Maharashtra,400001,PROD100000,Burgers,Burgers - 611,5,0.32,8490.54,Jeremy Combs

In [14]:
df.columns

Index(['Customer ID', 'Date of Birth', 'Sales', 'Year', 'Outlet Type',
       'City Type', 'Category of Goods', 'Region', 'Country', 'Segment',
       'Sales Date', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'State', 'Postal Code', 'Product ID', 'Sub-Category', 'Product Name',
       'Quantity', 'Discount', 'Profit', 'Full Name'],
      dtype='str')

### column change

In [15]:
df = df[
    ["Customer ID", "Full Name"] +
    [col for col in df.columns if col not in ["Customer ID", "Full Name"]]
]

In [16]:
df

,Customer ID,Full Name,Date of Birth,Sales,Year,Outlet Type,City Type,Category of Goods,Region,Country,...,Ship Date,Ship Mode,State,Postal Code,Product ID,Sub-Category,Product Name,Quantity,Discount,Profit
0,CUST000001,Curtis Krause,1973-11-29,3344.69,2023,Large,Tier 1,Fast Food,East,India,...,2020-04-18,Same Day,West Bengal,700001,PROD000001,Burgers,Burgers - 718,3,0.09,448.24
1,CUST000002,Jeremy Foster,1987-08-30,37094.41,2022,Medium,Tier 2,Fast Food,East,India,...,2021-01-11,Standard Class,Punjab,160001,PROD000002,Pizzas,Pizzas - 519,5,0.39,3134.34
2,CUST000003,Ariel Mccann,1980-12-15,35501.08,2023,Large,Village,Electric Appliances,South,India,...,2020-08-16,Second Class,Gujarat,380001,PROD000003,Fans,Fans - 395,6,0.07,8324.21
3,CUST000004,Colleen Maynard,1989-05-23,8969.33,2021,Medium,Village,Dairy Products,East,India,...,2021-10-16,First Class,West Bengal,700001,PROD000004,Milk,Milk - 798,4,0.18,1962.66
4,CUST000005,Gina Holden,1957-12-31,35530.44,2021,Small,Village,Sessional Fruits & Vegetables,West,India,...,2019-01-25,Standard Class,Delhi,110001,PROD000005,Tomatoes,Tomatoes - 442,4,0.27,2843.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,CUST099996,Thomas Adams,2018-02-02,254.35,2020,Large,Tier 1,Furniture,East,India,...,2019-02-05,First Class,Gujarat,380001,PROD099996,Beds,Beds - 169,2,0.12,61.84
99996,CUST099997,Clifford Dillon,1955-08-11,846.66,2019,Medium,Tier 2,Sessional Fruits & Vegetables,North,India,...,2020-04-09,Same Day,Rajasthan,302001,PROD099997,Tomatoes,Tomatoes - 291,1,0.43,118.60
99997,CUST099998,Kelly Deleon,1991-02-27,12165.34,2019,Large,Tier 2,Furniture,East,India,...,2021-07-02,Standard Class,Maharashtra,400001,PROD099998,Chairs,Chairs - 381,4,0.13,2100.20
99998,CUST099999,Katie Moses,1990-10-21,41242.99,2019,Small,Tier 1,Fast Food,North,India,...,2019-08-01,Second Class,Karnataka,560001,PROD099999,Sandwiches,Sandwiches - 961,4,0.41,4674.57
99999,CUST100000,Jeremy Combs,2016-12-27,47402.45,2019,Medium,Village,Fast Food,North,India,...,2020-02-24,Same Day,Maharashtra,400001,PROD100000,Burgers,Burgers - 611,5,0.32,8490.54

In [17]:
Avg = df["Sales"].to_numpy()
mean = np.mean(Avg).round(2)
print("AVG Value:", mean)

AVG Value: 25084.41