In [ ]:
import requests
import pandas as pd

url = "https://jsonplaceholder.typicode.com/users"
url = "https://api.open-meteo.com/v1/forecast?latitude=28.6519&longitude=77.2315&hourly=temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m&utm_source=chatgpt.com"

In [8]:
url = "https://api.open-meteo.com/v1/forecast?latitude=28.6519&longitude=77.2315&hourly=temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m&utm_source=chatgpt.com"
response = requests.get(url)
data = response.json()
df = pd.DataFrame(data)

In [12]:
df

,latitude,longitude,generationtime_ms,utc_offset_seconds,timezone,timezone_abbreviation,elevation,hourly_units,hourly
time,28.646748,77.2748,0.087738,0,GMT,GMT,231.0,iso8601,"[2026-09-05T00:00, 2026-09-05T01:00, 2026-09-0..."
temperature_2m,28.646748,77.2748,0.087738,0,GMT,GMT,231.0,°C,"[25.4, 25.0, 25.6, 26.2, 27.0, 27.9, 28.5, 27...."
relative_humidity_2m,28.646748,77.2748,0.087738,0,GMT,GMT,231.0,%,"[97, 96, 96, 92, 90, 85, 84, 88, 92, 95, 91, 9..."
precipitation,28.646748,77.2748,0.087738,0,GMT,GMT,231.0,mm,"[1.0, 2.0, 0.5, 0.2, 0.4, 0.5, 0.5, 1.7, 5.7, ..."
wind_speed_10m,28.646748,77.2748,0.087738,0,GMT,GMT,231.0,km/h,"[15.5, 8.9, 3.6, 6.5, 4.3, 5.3, 6.1, 8.3, 5.1,..."

In [11]:
df.head()

,latitude,longitude,generationtime_ms,utc_offset_seconds,timezone,timezone_abbreviation,elevation,hourly_units,hourly
time,28.646748,77.2748,0.087738,0,GMT,GMT,231.0,iso8601,"[2026-09-05T00:00, 2026-09-05T01:00, 2026-09-0..."
temperature_2m,28.646748,77.2748,0.087738,0,GMT,GMT,231.0,°C,"[25.4, 25.0, 25.6, 26.2, 27.0, 27.9, 28.5, 27...."
relative_humidity_2m,28.646748,77.2748,0.087738,0,GMT,GMT,231.0,%,"[97, 96, 96, 92, 90, 85, 84, 88, 92, 95, 91, 9..."
precipitation,28.646748,77.2748,0.087738,0,GMT,GMT,231.0,mm,"[1.0, 2.0, 0.5, 0.2, 0.4, 0.5, 0.5, 1.7, 5.7, ..."
wind_speed_10m,28.646748,77.2748,0.087738,0,GMT,GMT,231.0,km/h,"[15.5, 8.9, 3.6, 6.5, 4.3, 5.3, 6.1, 8.3, 5.1,..."

In [13]:
df.info()

<class 'pandas.DataFrame'>
Index: 5 entries, time to wind_speed_10m
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   latitude               5 non-null      float64
 1   longitude              5 non-null      float64
 2   generationtime_ms      5 non-null      float64
 3   utc_offset_seconds     5 non-null      int64
 4   timezone               5 non-null      str
 5   timezone_abbreviation  5 non-null      str
 6   elevation              5 non-null      float64
 7   hourly_units           5 non-null      str
 8   hourly                 5 non-null      object
dtypes: float64(4), int64(1), object(1), str(3)
memory usage: 572.0+ bytes

In [14]:
df.describe()

,latitude,longitude,generationtime_ms,utc_offset_seconds,elevation
count,5.000000e+00,5.0000,5.000000,5.0,5.0
mean,2.864675e+01,77.2748,0.087738,0.0,231.0
std,3.972055e-15,0.0000,0.000000,0.0,0.0
min,2.864675e+01,77.2748,0.087738,0.0,231.0
25%,2.864675e+01,77.2748,0.087738,0.0,231.0
50%,2.864675e+01,77.2748,0.087738,0.0,231.0
75%,2.864675e+01,77.2748,0.087738,0.0,231.0
max,2.864675e+01,77.2748,0.087738,0.0,231.0

In [17]:
df.columns

Index(['latitude', 'longitude', 'generationtime_ms', 'utc_offset_seconds',
       'timezone', 'timezone_abbreviation', 'elevation', 'hourly_units',
       'hourly'],
      dtype='str')

In [15]:
df.isna().sum()

latitude                 0
longitude                0
generationtime_ms        0
utc_offset_seconds       0
timezone                 0
timezone_abbreviation    0
elevation                0
hourly_units             0
hourly                   0
dtype: int64

In [27]:
column = pd.DataFrame(data["hourly"])

In [29]:
column

,time,temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m
0,2026-09-05T00:00,25.4,97,1.0,15.5
1,2026-09-05T01:00,25.0,96,2.0,8.9
2,2026-09-05T02:00,25.6,96,0.5,3.6
3,2026-09-05T03:00,26.2,92,0.2,6.5
4,2026-09-05T04:00,27.0,90,0.4,4.3
...,...,...,...,...,...
163,2026-09-11T19:00,26.1,97,0.0,5.0
164,2026-09-11T20:00,25.9,98,0.0,5.2
165,2026-09-11T21:00,25.7,99,0.0,5.3
166,2026-09-11T22:00,25.5,99,0.0,5.4
167,2026-09-11T23:00,25.5,98,0.0,5.8

In [30]:
column.head()

,time,temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m
0,2026-09-05T00:00,25.4,97,1.0,15.5
1,2026-09-05T01:00,25.0,96,2.0,8.9
2,2026-09-05T02:00,25.6,96,0.5,3.6
3,2026-09-05T03:00,26.2,92,0.2,6.5
4,2026-09-05T04:00,27.0,90,0.4,4.3

In [31]:
column.info()

<class 'pandas.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  168 non-null    str
 1   temperature_2m        168 non-null    float64
 2   relative_humidity_2m  168 non-null    int64
 3   precipitation         168 non-null    float64
 4   wind_speed_10m        168 non-null    float64
dtypes: float64(3), int64(1), str(1)
memory usage: 6.7 KB

In [33]:
column.describe()

       temperature_2m  relative_humidity_2m  precipitation  wind_speed_10m
count      168.000000            168.000000     168.000000      168.000000
mean        28.241071             81.083333       0.288690        5.399405
std          2.499828             12.608531       0.817065        2.615374
min         23.700000             55.000000       0.000000        0.200000
25%         26.400000             73.000000       0.000000        3.600000
50%         27.500000             83.000000       0.000000        5.200000
75%         29.850000             91.000000       0.100000        7.025000
max         33.700000             99.000000       5.700000       15.500000

In [32]:
column.isnull().sum()

time                    0
temperature_2m          0
relative_humidity_2m    0
precipitation           0
wind_speed_10m          0
dtype: int64

In [36]:
column["time"] = pd.to_datetime(column["time"])

In [37]:
column.dtypes

time                    datetime64[us]
temperature_2m                 float64
relative_humidity_2m             int64
precipitation                  float64
wind_speed_10m                 float64
dtype: object

In [38]:
column["date"] = column["time"].dt.date
column["hour"] = column["time"].dt.hour

In [39]:
column.head()

,time,temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m,date,hour
0,2026-09-05 00:00:00,25.4,97,1.0,15.5,2026-09-05,0
1,2026-09-05 01:00:00,25.0,96,2.0,8.9,2026-09-05,1
2,2026-09-05 02:00:00,25.6,96,0.5,3.6,2026-09-05,2
3,2026-09-05 03:00:00,26.2,92,0.2,6.5,2026-09-05,3
4,2026-09-05 04:00:00,27.0,90,0.4,4.3,2026-09-05,4

In [41]:
column.describe()

,time,temperature_2m,relative_humidity_2m,precipitation,wind_speed_10m,hour
count,168,168.000000,168.000000,168.000000,168.000000,168.000000
mean,2026-09-08 11:30:00,28.241071,81.083333,0.288690,5.399405,11.500000
min,2026-09-05 00:00:00,23.700000,55.000000,0.000000,0.200000,0.000000
25%,2026-09-06 17:45:00,26.400000,73.000000,0.000000,3.600000,5.750000
50%,2026-09-08 11:30:00,27.500000,83.000000,0.000000,5.200000,11.500000
75%,2026-09-10 05:15:00,29.850000,91.000000,0.100000,7.025000,17.250000
max,2026-09-11 23:00:00,33.700000,99.000000,5.700000,15.500000,23.000000
std,NaN,2.499828,12.608531,0.817065,2.615374,6.942881

## Temperature filter

pip install jugaad-data