In [1]:
from jugaad_data.nse import stock_df
from datetime import date

In [ ]:
df = stock_df(
    symbol="RELIANCE",
    from_date=date(2024, 1, 1),
    to_date=date(2026, 9, 6),
    series="EQ"
)

df

c:\Users\Anish Kumar\AppData\Local\Programs\Python\Python311\Lib\site-packages\jugaad_data\util.py:40: UserWarning: no explicit representation of timezones available for np.datetime64
  return np.datetime64(dt)

,DATE,SERIES,OPEN,HIGH,LOW,PREV. CLOSE,LTP,CLOSE,VWAP,VOLUME,VALUE,NO OF TRADES,DELIVERY QTY,DELIVERY %,SYMBOL
0,2026-09-03 18:30:00,EQ,1304.10,1333.00,1304.10,1302.50,1322.00,1322.00,1326.29,13031534,1.728359e+10,181295,8600946,66.00,RELIANCE
1,2026-09-02 18:30:00,EQ,1313.10,1316.80,1302.50,1313.10,1302.50,1302.50,1308.70,9721454,1.272246e+10,158231,5306274,54.58,RELIANCE
2,2026-09-01 18:30:00,EQ,1298.00,1321.90,1293.10,1309.00,1313.10,1313.10,1308.95,13497841,1.766806e+10,196257,8462199,62.69,RELIANCE
3,2026-08-31 18:30:00,EQ,1285.00,1311.80,1280.00,1277.00,1309.00,1309.00,1299.72,12617528,1.639928e+10,187471,7456999,59.10,RELIANCE
4,2026-08-30 18:30:00,EQ,1278.70,1297.60,1271.00,1287.00,1277.00,1277.00,1278.43,34871137,4.458028e+10,244866,30329813,86.98,RELIANCE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
672,2024-01-04 18:30:00,EQ,2602.90,2619.85,2598.00,2596.65,2609.00,2607.70,2606.82,4043203,1.053989e+10,211413,2280572,56.41,RELIANCE
673,2024-01-03 18:30:00,EQ,2588.00,2609.85,2579.10,2583.30,2600.00,2596.65,2597.37,4806389,1.248397e+10,267185,3003090,62.48,RELIANCE
674,2024-01-02 18:30:00,EQ,2610.00,2634.00,2577.20,2611.70,2580.75,2583.30,2606.46,4518768,1.177801e+10,198303,2706158,59.89,RELIANCE
675,2024-01-01 18:30:00,EQ,2585.00,2615.00,2573.00,2590.25,2609.00,2611.70,2596.75,3724400,9.671332e+09,175872,2059678,55.30,RELIANCE
676,2023-12-31 18:30:00,EQ,2580.55,2606.85,2573.15,2584.95,2588.45,2590.25,2588.14,2015270,5.215808e+09,115559,877801,43.56,RELIANCE

In [ ]:
df.columns

Index(['DATE', 'SERIES', 'OPEN', 'HIGH', 'LOW', 'PREV. CLOSE', 'LTP', 'CLOSE',
       'VWAP', 'VOLUME', 'VALUE', 'NO OF TRADES', 'DELIVERY QTY', 'DELIVERY %',
       'SYMBOL'],
      dtype='str')

In [ ]:
df.shape

(677, 15)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 677 entries, 0 to 676
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   DATE          677 non-null    datetime64[ms]
 1   SERIES        677 non-null    str
 2   OPEN          677 non-null    float64
 3   HIGH          677 non-null    float64
 4   LOW           677 non-null    float64
 5   PREV. CLOSE   677 non-null    float64
 6   LTP           677 non-null    float64
 7   CLOSE         677 non-null    float64
 8   VWAP          677 non-null    float64
 9   VOLUME        677 non-null    int64
 10  VALUE         677 non-null    float64
 11  NO OF TRADES  677 non-null    int64
 12  DELIVERY QTY  677 non-null    int64
 13  DELIVERY %    669 non-null    float64
 14  SYMBOL        677 non-null    str
dtypes: datetime64[ms](1), float64(9), int64(3), str(2)
memory usage: 79.5 KB

In [ ]:
df.isna().sum()

DATE            0
SERIES          0
OPEN            0
HIGH            0
LOW             0
PREV. CLOSE     0
LTP             0
CLOSE           0
VWAP            0
VOLUME          0
VALUE           0
NO OF TRADES    0
DELIVERY QTY    0
DELIVERY %      8
SYMBOL          0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates()

,DATE,SERIES,OPEN,HIGH,LOW,PREV. CLOSE,LTP,CLOSE,VWAP,VOLUME,VALUE,NO OF TRADES,DELIVERY QTY,DELIVERY %,SYMBOL
0,2026-09-03 18:30:00,EQ,1304.10,1333.00,1304.10,1302.50,1322.00,1322.00,1326.29,13031534,1.728359e+10,181295,8600946,66.00,RELIANCE
1,2026-09-02 18:30:00,EQ,1313.10,1316.80,1302.50,1313.10,1302.50,1302.50,1308.70,9721454,1.272246e+10,158231,5306274,54.58,RELIANCE
2,2026-09-01 18:30:00,EQ,1298.00,1321.90,1293.10,1309.00,1313.10,1313.10,1308.95,13497841,1.766806e+10,196257,8462199,62.69,RELIANCE
3,2026-08-31 18:30:00,EQ,1285.00,1311.80,1280.00,1277.00,1309.00,1309.00,1299.72,12617528,1.639928e+10,187471,7456999,59.10,RELIANCE
4,2026-08-30 18:30:00,EQ,1278.70,1297.60,1271.00,1287.00,1277.00,1277.00,1278.43,34871137,4.458028e+10,244866,30329813,86.98,RELIANCE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
672,2024-01-04 18:30:00,EQ,2602.90,2619.85,2598.00,2596.65,2609.00,2607.70,2606.82,4043203,1.053989e+10,211413,2280572,56.41,RELIANCE
673,2024-01-03 18:30:00,EQ,2588.00,2609.85,2579.10,2583.30,2600.00,2596.65,2597.37,4806389,1.248397e+10,267185,3003090,62.48,RELIANCE
674,2024-01-02 18:30:00,EQ,2610.00,2634.00,2577.20,2611.70,2580.75,2583.30,2606.46,4518768,1.177801e+10,198303,2706158,59.89,RELIANCE
675,2024-01-01 18:30:00,EQ,2585.00,2615.00,2573.00,2590.25,2609.00,2611.70,2596.75,3724400,9.671332e+09,175872,2059678,55.30,RELIANCE
676,2023-12-31 18:30:00,EQ,2580.55,2606.85,2573.15,2584.95,2588.45,2590.25,2588.14,2015270,5.215808e+09,115559,877801,43.56,RELIANCE