In [103]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pyodbc

In [104]:
df = pd.read_csv(r"C:\Users\Anish Kumar\Downloads\smart_city_urban_life_analytics.csv")

### Dataset Check

In [105]:
df.head(5)

,Record_ID,Date,Day_Name,City,Area_Type,Citizen_ID,Age_Group,Work_Mode,Temperature_C,Rainfall_mm,...,Internet_Usage_GB,Online_Food_Orders,Daily_Spending_INR,Hospital_Visits,Emergency_Complaints,Work_Hours,Outdoor_Activity_Hours,Happiness_Score,Service_Satisfaction,Weekend
0,REC000001,2024-07-17,Wednesday,Mumbai,Residential,CIT356787,25-34,Office,31.4,0.7,...,2.25,0,322.38,0,0,10.2,4.2,8.7,8.4,No
1,REC000002,2025-01-05,Sunday,Mumbai,Residential,CIT988662,25-34,Hybrid,21.2,2.5,...,0.97,1,1055.15,0,0,6.2,1.8,8.7,9.0,Yes
2,REC000003,2024-12-28,Saturday,Hyderabad,Residential,CIT319684,35-44,Office,20.6,2.0,...,5.80,0,99.29,0,0,8.3,2.0,8.8,10.0,Yes
3,REC000004,2023-10-13,Friday,Jaipur,Residential,CIT358607,35-44,Other,21.8,0.5,...,4.15,0,208.41,0,0,0.5,0.8,5.3,7.6,No
4,REC000005,2023-08-23,Wednesday,Delhi,Commercial,CIT814825,45-54,Hybrid,29.3,2.8,...,2.81,1,1088.10,0,0,7.0,2.4,8.9,10.0,No

In [106]:
df.tail()

,Record_ID,Date,Day_Name,City,Area_Type,Citizen_ID,Age_Group,Work_Mode,Temperature_C,Rainfall_mm,...,Internet_Usage_GB,Online_Food_Orders,Daily_Spending_INR,Hospital_Visits,Emergency_Complaints,Work_Hours,Outdoor_Activity_Hours,Happiness_Score,Service_Satisfaction,Weekend
99995,REC099996,2025-11-21,Friday,Chennai,Industrial,CIT227256,18-24,Hybrid,27.0,3.4,...,6.47,0,984.99,0,0,8.9,2.2,7.8,6.6,No
99996,REC099997,2023-05-26,Friday,Bengaluru,Residential,CIT834022,45-54,Work From Home,28.5,0.2,...,3.37,0,1284.73,0,0,6.1,1.9,8.7,9.0,No
99997,REC099998,2024-10-27,Sunday,Kolkata,Mixed Use,CIT455598,18-24,Other,24.3,2.7,...,3.37,2,1368.49,0,0,3.0,3.4,9.2,8.1,Yes
99998,REC099999,2023-09-14,Thursday,Chennai,Mixed Use,CIT721668,18-24,Office,30.5,0.5,...,3.51,0,768.40,0,0,7.8,4.6,10.0,9.5,No
99999,REC100000,2025-12-04,Thursday,Hyderabad,Residential,CIT170780,18-24,Hybrid,23.3,1.8,...,0.84,0,1909.19,0,0,6.8,2.1,7.9,8.3,No

In [107]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 27 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Record_ID                       100000 non-null  str
 1   Date                            100000 non-null  str
 2   Day_Name                        100000 non-null  str
 3   City                            100000 non-null  str
 4   Area_Type                       100000 non-null  str
 5   Citizen_ID                      100000 non-null  str
 6   Age_Group                       100000 non-null  str
 7   Work_Mode                       100000 non-null  str
 8   Temperature_C                   100000 non-null  float64
 9   Rainfall_mm                     100000 non-null  float64
 10  AQI                             98968 non-null   float64
 11  Traffic_Level                   100000 non-null  str
 12  Average_Traffic_Speed_kmh       100000 non-null  float64
 13  Primary_Transport               100000 non-null  str
 14  Public_Transport_Usage_Minutes  100000 non-null  int64
 15  Electricity_Consumption_kWh     100000 non-null  float64
 16  Water_Consumption_Liters        100000 non-null  int64
 17  Internet_Usage_GB               100000 non-null  float64
 18  Online_Food_Orders              100000 non-null  int64
 19  Daily_Spending_INR              99818 non-null   float64
 20  Hospital_Visits                 100000 non-null  int64
 21  Emergency_Complaints            100000 non-null  int64
 22  Work_Hours                      100000 non-null  float64
 23  Outdoor_Activity_Hours          100000 non-null  float64
 24  Happiness_Score                 100000 non-null  float64
 25  Service_Satisfaction            100000 non-null  float64
 26  Weekend                         100000 non-null  str
dtypes: float64(11), int64(5), str(11)
memory usage: 20.6 MB

In [108]:
df.describe()

,Temperature_C,Rainfall_mm,AQI,Average_Traffic_Speed_kmh,Public_Transport_Usage_Minutes,Electricity_Consumption_kWh,Water_Consumption_Liters,Internet_Usage_GB,Online_Food_Orders,Daily_Spending_INR,Hospital_Visits,Emergency_Complaints,Work_Hours,Outdoor_Activity_Hours,Happiness_Score,Service_Satisfaction
count,100000.000000,100000.000000,98968.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,99818.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,27.122641,3.664261,115.669954,27.924011,30.764970,9.884848,144.450540,3.836436,0.630160,1016.618077,0.001480,0.034740,6.601462,2.077842,7.700595,7.663431
std,5.535933,5.653815,47.671308,13.508682,39.548256,3.077680,44.872812,2.030874,0.756944,533.872974,0.038442,0.207542,2.364405,1.087854,1.062520,1.394511
min,6.800000,0.000000,20.000000,4.000000,0.000000,1.000000,20.000000,0.100000,0.000000,50.000000,0.000000,0.000000,0.000000,0.000000,3.000000,1.600000
25%,23.000000,0.600000,82.000000,16.200000,0.000000,7.790000,114.000000,2.390000,0.000000,634.642500,0.000000,0.000000,5.200000,1.300000,7.000000,6.700000
50%,27.100000,1.600000,114.000000,27.400000,0.000000,9.860000,145.000000,3.800000,0.000000,1005.105000,0.000000,0.000000,6.900000,2.100000,7.700000,7.700000
75%,31.300000,4.000000,148.000000,37.400000,63.000000,11.950000,175.000000,5.220000,1.000000,1377.055000,0.000000,0.000000,8.300000,2.800000,8.400000,8.700000
max,46.700000,92.400000,323.000000,55.000000,119.000000,22.820000,329.000000,14.150000,3.000000,3653.130000,1.000000,2.000000,11.000000,7.000000,10.000000,10.000000

In [109]:
df.columns

Index(['Record_ID', 'Date', 'Day_Name', 'City', 'Area_Type', 'Citizen_ID',
       'Age_Group', 'Work_Mode', 'Temperature_C', 'Rainfall_mm', 'AQI',
       'Traffic_Level', 'Average_Traffic_Speed_kmh', 'Primary_Transport',
       'Public_Transport_Usage_Minutes', 'Electricity_Consumption_kWh',
       'Water_Consumption_Liters', 'Internet_Usage_GB', 'Online_Food_Orders',
       'Daily_Spending_INR', 'Hospital_Visits', 'Emergency_Complaints',
       'Work_Hours', 'Outdoor_Activity_Hours', 'Happiness_Score',
       'Service_Satisfaction', 'Weekend'],
      dtype='str')

In [110]:
df.shape

(100000, 27)

### Data cleaning

1. null value check

In [111]:
df.isnull().sum()

Record_ID                            0
Date                                 0
Day_Name                             0
City                                 0
Area_Type                            0
Citizen_ID                           0
Age_Group                            0
Work_Mode                            0
Temperature_C                        0
Rainfall_mm                          0
AQI                               1032
Traffic_Level                        0
Average_Traffic_Speed_kmh            0
Primary_Transport                    0
Public_Transport_Usage_Minutes       0
Electricity_Consumption_kWh          0
Water_Consumption_Liters             0
Internet_Usage_GB                    0
Online_Food_Orders                   0
Daily_Spending_INR                 182
Hospital_Visits                      0
Emergency_Complaints                 0
Work_Hours                           0
Outdoor_Activity_Hours               0
Happiness_Score                      0
Service_Satisfaction                 0
Weekend                              0
dtype: int64

2. Duplicate Value check

In [112]:
df.duplicated().sum()

np.int64(0)

3. Missing Value Fill

In [113]:
df["AQI"] = df["AQI"].fillna(df["AQI"].median())

In [114]:
df["Daily_Spending_INR"] = df["Daily_Spending_INR"].fillna(
    df["Daily_Spending_INR"].median()
)

In [115]:
df["Age_Group"].value_counts()

Age_Group
25-34    31895
35-44    24937
18-24    18011
45-54    15126
55+      10031
Name: count, dtype: int64

4. Date

In [116]:
df["Date"] = pd.to_datetime(df["Date"],format="%Y-%m-%d")

In [117]:
df["Date"].dtypes

dtype('<M8[us]')

In [118]:
df["Month"] = df["Date"].dt.month

In [119]:
df["Year"] = df["Date"].dt.year

In [120]:
df["Day"] = df["Date"].dt.day

In [121]:
df["Month_Name"] = df["Date"].dt.month_name()

In [122]:
df["Quarter"] = df["Date"].dt.quarter

In [123]:
df.head()

,Record_ID,Date,Day_Name,City,Area_Type,Citizen_ID,Age_Group,Work_Mode,Temperature_C,Rainfall_mm,...,Work_Hours,Outdoor_Activity_Hours,Happiness_Score,Service_Satisfaction,Weekend,Month,Year,Day,Month_Name,Quarter
0,REC000001,2024-07-17,Wednesday,Mumbai,Residential,CIT356787,25-34,Office,31.4,0.7,...,10.2,4.2,8.7,8.4,No,7,2024,17,July,3
1,REC000002,2025-01-05,Sunday,Mumbai,Residential,CIT988662,25-34,Hybrid,21.2,2.5,...,6.2,1.8,8.7,9.0,Yes,1,2025,5,January,1
2,REC000003,2024-12-28,Saturday,Hyderabad,Residential,CIT319684,35-44,Office,20.6,2.0,...,8.3,2.0,8.8,10.0,Yes,12,2024,28,December,4
3,REC000004,2023-10-13,Friday,Jaipur,Residential,CIT358607,35-44,Other,21.8,0.5,...,0.5,0.8,5.3,7.6,No,10,2023,13,October,4
4,REC000005,2023-08-23,Wednesday,Delhi,Commercial,CIT814825,45-54,Hybrid,29.3,2.8,...,7.0,2.4,8.9,10.0,No,8,2023,23,August,3

### Text Cleaning

1. Clean and standardize text data in categorical columns.

In [124]:
df.select_dtypes(include="object").columns

C:\Users\Anish Kumar\AppData\Local\Temp\ipykernel_19364\1196084386.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").columns

Index(['Record_ID', 'Day_Name', 'City', 'Area_Type', 'Citizen_ID', 'Age_Group',
       'Work_Mode', 'Traffic_Level', 'Primary_Transport', 'Weekend',
       'Month_Name'],
      dtype='str')

In [125]:
df["City"] = df["City"].str.strip().str.title()

In [126]:
df["City"].unique()

<StringArray>
[   'Mumbai', 'Hyderabad',    'Jaipur',     'Delhi',      'Pune',   'Kolkata',
   'Chennai', 'Bengaluru']
Length: 8, dtype: str

In [127]:
text_cols = df.select_dtypes(include="str").columns
print(text_cols.tolist())

['Record_ID', 'Day_Name', 'City', 'Area_Type', 'Citizen_ID', 'Age_Group', 'Work_Mode', 'Traffic_Level', 'Primary_Transport', 'Weekend', 'Month_Name']

In [128]:
for col in text_cols:
    df[col] = df[col].str.strip()

In [129]:
for col in text_cols:
    print("\n", col)
    print(df[col].unique())

 Record_ID
<StringArray>
['REC000001', 'REC000002', 'REC000003', 'REC000004', 'REC000005', 'REC000006',
 'REC000007', 'REC000008', 'REC000009', 'REC000010',
 ...
 'REC099991', 'REC099992', 'REC099993', 'REC099994', 'REC099995', 'REC099996',
 'REC099997', 'REC099998', 'REC099999', 'REC100000']
Length: 100000, dtype: str

 Day_Name
<StringArray>
['Wednesday', 'Sunday', 'Saturday', 'Friday', 'Monday', 'Tuesday', 'Thursday']
Length: 7, dtype: str

 City
<StringArray>
[   'Mumbai', 'Hyderabad',    'Jaipur',     'Delhi',      'Pune',   'Kolkata',
   'Chennai', 'Bengaluru']
Length: 8, dtype: str

 Area_Type
<StringArray>
['Residential', 'Commercial', 'Mixed Use', 'Industrial']
Length: 4, dtype: str

 Citizen_ID
<StringArray>
['CIT356787', 'CIT988662', 'CIT319684', 'CIT358607', 'CIT814825', 'CIT972064',
 'CIT573417', 'CIT864491', 'CIT520521', 'CIT723939',
 ...
 'CIT624832', 'CIT949660', 'CIT879117', 'CIT510146', 'CIT936137', 'CIT121606',
 'CIT227256', 'CIT834022', 'CIT721668', 'CIT170780']
Length: 94680, dtype: str

 Age_Group
<StringArray>
['25-34', '35-44', '45-54', '18-24', '55+']
Length: 5, dtype: str

 Work_Mode
<StringArray>
['Office', 'Hybrid', 'Other', 'Work From Home', 'Student']
Length: 5, dtype: str

 Traffic_Level
<StringArray>
['Low', 'Medium', 'Severe', 'High']
Length: 4, dtype: str

 Primary_Transport
<StringArray>
[           'Auto', 'Private Vehicle',             'Cab',           'Metro',
 'Walking/Cycling',             'Bus', 'walking/cycling',             'cab',
 'private vehicle',           'metro',            'auto',             'bus']
Length: 12, dtype: str

 Weekend
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

 Month_Name
<StringArray>
[     'July',   'January',  'December',   'October',    'August',  'November',
     'March',       'May',      'June',  'February',     'April', 'September']
Length: 12, dtype: str

In [130]:

for col in text_cols:
    print(f"\n--- {col} ---")
    print("Unique:", df[col].nunique())
    print(df[col].unique())

--- Record_ID ---
Unique: 100000
<StringArray>
['REC000001', 'REC000002', 'REC000003', 'REC000004', 'REC000005', 'REC000006',
 'REC000007', 'REC000008', 'REC000009', 'REC000010',
 ...
 'REC099991', 'REC099992', 'REC099993', 'REC099994', 'REC099995', 'REC099996',
 'REC099997', 'REC099998', 'REC099999', 'REC100000']
Length: 100000, dtype: str

--- Day_Name ---
Unique: 7
<StringArray>
['Wednesday', 'Sunday', 'Saturday', 'Friday', 'Monday', 'Tuesday', 'Thursday']
Length: 7, dtype: str

--- City ---
Unique: 8
<StringArray>
[   'Mumbai', 'Hyderabad',    'Jaipur',     'Delhi',      'Pune',   'Kolkata',
   'Chennai', 'Bengaluru']
Length: 8, dtype: str

--- Area_Type ---
Unique: 4
<StringArray>
['Residential', 'Commercial', 'Mixed Use', 'Industrial']
Length: 4, dtype: str

--- Citizen_ID ---
Unique: 94680
<StringArray>
['CIT356787', 'CIT988662', 'CIT319684', 'CIT358607', 'CIT814825', 'CIT972064',
 'CIT573417', 'CIT864491', 'CIT520521', 'CIT723939',
 ...
 'CIT624832', 'CIT949660', 'CIT879117', 'CIT510146', 'CIT936137', 'CIT121606',
 'CIT227256', 'CIT834022', 'CIT721668', 'CIT170780']
Length: 94680, dtype: str

--- Age_Group ---
Unique: 5
<StringArray>
['25-34', '35-44', '45-54', '18-24', '55+']
Length: 5, dtype: str

--- Work_Mode ---
Unique: 5
<StringArray>
['Office', 'Hybrid', 'Other', 'Work From Home', 'Student']
Length: 5, dtype: str

--- Traffic_Level ---
Unique: 4
<StringArray>
['Low', 'Medium', 'Severe', 'High']
Length: 4, dtype: str

--- Primary_Transport ---
Unique: 12
<StringArray>
[           'Auto', 'Private Vehicle',             'Cab',           'Metro',
 'Walking/Cycling',             'Bus', 'walking/cycling',             'cab',
 'private vehicle',           'metro',            'auto',             'bus']
Length: 12, dtype: str

--- Weekend ---
Unique: 2
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

--- Month_Name ---
Unique: 12
<StringArray>
[     'July',   'January',  'December',   'October',    'August',  'November',
     'March',       'May',      'June',  'February',     'April', 'September']
Length: 12, dtype: str

In [131]:
cols = [
    "Citizen_ID",
    "Age_Group",
    "Work_Mode",
    "Traffic_Level",
    "Primary_Transport",
    "Weekend"
]

for col in cols:
    print(f"\n--- {col} ---")
    print("Unique:", df[col].nunique())
    print(df[col].value_counts())

--- Citizen_ID ---
Unique: 94680
Citizen_ID
CIT394631    4
CIT775296    4
CIT309398    4
CIT521325    4
CIT403417    4
            ..
CIT121606    1
CIT227256    1
CIT834022    1
CIT721668    1
CIT170780    1
Name: count, Length: 94680, dtype: int64

--- Age_Group ---
Unique: 5
Age_Group
25-34    31895
35-44    24937
18-24    18011
45-54    15126
55+      10031
Name: count, dtype: int64

--- Work_Mode ---
Unique: 5
Work_Mode
Student           20131
Hybrid            20082
Office            20040
Other             19951
Work From Home    19796
Name: count, dtype: int64

--- Traffic_Level ---
Unique: 4
Traffic_Level
Medium    35185
Low       26834
High      22173
Severe    15808
Name: count, dtype: int64

--- Primary_Transport ---
Unique: 12
Primary_Transport
Bus                22063
Metro              21957
Private Vehicle    19816
Cab                14972
Auto               12024
Walking/Cycling     8861
metro                 71
bus                   70
cab                   58
private vehicle       54
walking/cycling       29
auto                  25
Name: count, dtype: int64

--- Weekend ---
Unique: 2
Weekend
No     71440
Yes    28560
Name: count, dtype: int64

## Outliers check

In [132]:
df.columns

Index(['Record_ID', 'Date', 'Day_Name', 'City', 'Area_Type', 'Citizen_ID',
       'Age_Group', 'Work_Mode', 'Temperature_C', 'Rainfall_mm', 'AQI',
       'Traffic_Level', 'Average_Traffic_Speed_kmh', 'Primary_Transport',
       'Public_Transport_Usage_Minutes', 'Electricity_Consumption_kWh',
       'Water_Consumption_Liters', 'Internet_Usage_GB', 'Online_Food_Orders',
       'Daily_Spending_INR', 'Hospital_Visits', 'Emergency_Complaints',
       'Work_Hours', 'Outdoor_Activity_Hours', 'Happiness_Score',
       'Service_Satisfaction', 'Weekend', 'Month', 'Year', 'Day', 'Month_Name',
       'Quarter'],
      dtype='str')

In [133]:
numeric_cols = df.select_dtypes(include="number").columns
print(numeric_cols.tolist())

['Temperature_C', 'Rainfall_mm', 'AQI', 'Average_Traffic_Speed_kmh', 'Public_Transport_Usage_Minutes', 'Electricity_Consumption_kWh', 'Water_Consumption_Liters', 'Internet_Usage_GB', 'Online_Food_Orders', 'Daily_Spending_INR', 'Hospital_Visits', 'Emergency_Complaints', 'Work_Hours', 'Outdoor_Activity_Hours', 'Happiness_Score', 'Service_Satisfaction', 'Month', 'Year', 'Day', 'Quarter']

In [134]:
outlier_cols = [
    "Temperature_C",
    "Rainfall_mm",
    "AQI",
    "Average_Traffic_Speed_kmh",
    "Public_Transport_Usage_Minutes",
    "Electricity_Consumption_kWh",
    "Water_Consumption_Liters",
    "Internet_Usage_GB",
    "Online_Food_Orders",
    "Daily_Spending_INR",
    "Hospital_Visits",
    "Emergency_Complaints",
    "Work_Hours",
    "Outdoor_Activity_Hours",
    "Happiness_Score",
    "Service_Satisfaction"
]

outlier_summary = []

for col in outlier_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    count = ((df[col] < lower) | (df[col] > upper)).sum()

    outlier_summary.append({
        "Column": col,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "Lower_Bound": lower,
        "Upper_Bound": upper,
        "Outlier_Count": count
    })

outlier_summary = pd.DataFrame(outlier_summary)

print(outlier_summary)

                            Column      Q1       Q3     IQR  Lower_Bound  \
0                    Temperature_C   23.00    31.30    8.30       10.550
1                      Rainfall_mm    0.60     4.00    3.40       -4.500
2                              AQI   82.00   147.00   65.00      -15.500
3        Average_Traffic_Speed_kmh   16.20    37.40   21.20      -15.600
4   Public_Transport_Usage_Minutes    0.00    63.00   63.00      -94.500
5      Electricity_Consumption_kWh    7.79    11.95    4.16        1.550
6         Water_Consumption_Liters  114.00   175.00   61.00       22.500
7                Internet_Usage_GB    2.39     5.22    2.83       -1.855
8               Online_Food_Orders    0.00     1.00    1.00       -1.500
9               Daily_Spending_INR  635.42  1376.33  740.91     -475.945
10                 Hospital_Visits    0.00     0.00    0.00        0.000
11            Emergency_Complaints    0.00     0.00    0.00        0.000
12                      Work_Hours    5.20     8.30    3.10        0.550
13          Outdoor_Activity_Hours    1.30     2.80    1.50       -0.950
14                 Happiness_Score    7.00     8.40    1.40        4.900
15            Service_Satisfaction    6.70     8.70    2.00        3.700

    Upper_Bound  Outlier_Count
0        43.750             38
1         9.100          10803
2       244.500            346
3        69.200              0
4       157.500              0
5        18.190            746
6       266.500            653
7         9.465            349
8         2.500           2005
9      2487.695            407
10        0.000            148
11        0.000           2997
12       12.950           1380
13        5.050            358
14       10.500            400
15       11.700            355

In [135]:
print(df["Hospital_Visits"].value_counts().sort_index())
print(df["Emergency_Complaints"].value_counts().sort_index())

Hospital_Visits
0    99852
1      148
Name: count, dtype: int64
Emergency_Complaints
0    97003
1     2520
2      477
Name: count, dtype: int64

In [136]:
for col in outlier_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df.loc[
        (df[col] < lower) | (df[col] > upper),
        col
    ]

    if len(outliers) > 0:
        print(f"\n--- {col} ---")
        print("Count:", len(outliers))
        print("Min Outlier:", outliers.min())
        print("Max Outlier:", outliers.max())

--- Temperature_C ---
Count: 38
Min Outlier: 6.8
Max Outlier: 46.7

--- Rainfall_mm ---
Count: 10803
Min Outlier: 9.2
Max Outlier: 92.4

--- AQI ---
Count: 346
Min Outlier: 245.0
Max Outlier: 323.0

--- Electricity_Consumption_kWh ---
Count: 746
Min Outlier: 1.0
Max Outlier: 22.82

--- Water_Consumption_Liters ---
Count: 653
Min Outlier: 20
Max Outlier: 329

--- Internet_Usage_GB ---
Count: 349
Min Outlier: 9.47
Max Outlier: 14.15

--- Online_Food_Orders ---
Count: 2005
Min Outlier: 3
Max Outlier: 3

--- Daily_Spending_INR ---
Count: 407
Min Outlier: 2488.01
Max Outlier: 3653.13

--- Hospital_Visits ---
Count: 148
Min Outlier: 1
Max Outlier: 1

--- Emergency_Complaints ---
Count: 2997
Min Outlier: 1
Max Outlier: 2

--- Work_Hours ---
Count: 1380
Min Outlier: 0.0
Max Outlier: 0.5

--- Outdoor_Activity_Hours ---
Count: 358
Min Outlier: 5.1
Max Outlier: 7.0

--- Happiness_Score ---
Count: 400
Min Outlier: 3.0
Max Outlier: 4.8

--- Service_Satisfaction ---
Count: 355
Min Outlier: 1.6
Max Outlier: 3.7

In [137]:
for col in outlier_cols:
    print(
        col,
        "Min =", df[col].min(),
        "Max =", df[col].max()
    )

Temperature_C Min = 6.8 Max = 46.7
Rainfall_mm Min = 0.0 Max = 92.4
AQI Min = 20.0 Max = 323.0
Average_Traffic_Speed_kmh Min = 4.0 Max = 55.0
Public_Transport_Usage_Minutes Min = 0 Max = 119
Electricity_Consumption_kWh Min = 1.0 Max = 22.82
Water_Consumption_Liters Min = 20 Max = 329
Internet_Usage_GB Min = 0.1 Max = 14.15
Online_Food_Orders Min = 0 Max = 3
Daily_Spending_INR Min = 50.0 Max = 3653.13
Hospital_Visits Min = 0 Max = 1
Emergency_Complaints Min = 0 Max = 2
Work_Hours Min = 0.0 Max = 11.0
Outdoor_Activity_Hours Min = 0.0 Max = 7.0
Happiness_Score Min = 3.0 Max = 10.0
Service_Satisfaction Min = 1.6 Max = 10.0

In [143]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Record_ID                       100000 non-null  string
 1   Date                            100000 non-null  datetime64[us]
 2   Day_Name                        100000 non-null  string
 3   City                            100000 non-null  string
 4   Area_Type                       100000 non-null  string
 5   Citizen_ID                      100000 non-null  string
 6   Age_Group                       100000 non-null  string
 7   Work_Mode                       100000 non-null  string
 8   Temperature_C                   100000 non-null  float64
 9   Rainfall_mm                     100000 non-null  float64
 10  AQI                             100000 non-null  float64
 11  Traffic_Level                   100000 non-null  string
 12  Average_Traffic_Speed_kmh       100000 non-null  float64
 13  Primary_Transport               100000 non-null  string
 14  Public_Transport_Usage_Minutes  100000 non-null  int64
 15  Electricity_Consumption_kWh     100000 non-null  float64
 16  Water_Consumption_Liters        100000 non-null  int64
 17  Internet_Usage_GB               100000 non-null  float64
 18  Online_Food_Orders              100000 non-null  int64
 19  Daily_Spending_INR              100000 non-null  float64
 20  Hospital_Visits                 100000 non-null  int64
 21  Emergency_Complaints            100000 non-null  int64
 22  Work_Hours                      100000 non-null  float64
 23  Outdoor_Activity_Hours          100000 non-null  float64
 24  Happiness_Score                 100000 non-null  float64
 25  Service_Satisfaction            100000 non-null  float64
 26  Weekend                         100000 non-null  string
 27  Month                           100000 non-null  int32
 28  Year                            100000 non-null  int32
 29  Day                             100000 non-null  int32
 30  Month_Name                      100000 non-null  string
 31  Quarter                         100000 non-null  int32
dtypes: datetime64[us](1), float64(11), int32(4), int64(5), string(11)
memory usage: 22.9 MB

### datatype validation

In [139]:
# Date
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

# Numeric columns
numeric_cols = [
    "Temperature_C",
    "Rainfall_mm",
    "AQI",
    "Average_Traffic_Speed_kmh",
    "Public_Transport_Usage_Minutes",
    "Electricity_Consumption_kWh",
    "Water_Consumption_Liters",
    "Internet_Usage_GB",
    "Online_Food_Orders",
    "Daily_Spending_INR",
    "Hospital_Visits",
    "Emergency_Complaints",
    "Work_Hours",
    "Outdoor_Activity_Hours",
    "Happiness_Score",
    "Service_Satisfaction",
    "Month",
    "Year",
    "Day",
    "Quarter"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [140]:
df.dtypes

Record_ID                                    str
Date                              datetime64[us]
Day_Name                                     str
City                                         str
Area_Type                                    str
Citizen_ID                                   str
Age_Group                                    str
Work_Mode                                    str
Temperature_C                            float64
Rainfall_mm                              float64
AQI                                      float64
Traffic_Level                                str
Average_Traffic_Speed_kmh                float64
Primary_Transport                            str
Public_Transport_Usage_Minutes             int64
Electricity_Consumption_kWh              float64
Water_Consumption_Liters                   int64
Internet_Usage_GB                        float64
Online_Food_Orders                         int64
Daily_Spending_INR                       float64
Hospital_Visits                            int64
Emergency_Complaints                       int64
Work_Hours                               float64
Outdoor_Activity_Hours                   float64
Happiness_Score                          float64
Service_Satisfaction                     float64
Weekend                                      str
Month                                      int32
Year                                       int32
Day                                        int32
Month_Name                                   str
Quarter                                    int32
dtype: object

In [141]:
text_cols = [
    "Record_ID",
    "Day_Name",
    "City",
    "Area_Type",
    "Citizen_ID",
    "Age_Group",
    "Work_Mode",
    "Traffic_Level",
    "Primary_Transport",
    "Weekend",
    "Month_Name"
]

for col in text_cols:
    df[col] = df[col].astype("string")

In [142]:
df.dtypes

Record_ID                                 string
Date                              datetime64[us]
Day_Name                                  string
City                                      string
Area_Type                                 string
Citizen_ID                                string
Age_Group                                 string
Work_Mode                                 string
Temperature_C                            float64
Rainfall_mm                              float64
AQI                                      float64
Traffic_Level                             string
Average_Traffic_Speed_kmh                float64
Primary_Transport                         string
Public_Transport_Usage_Minutes             int64
Electricity_Consumption_kWh              float64
Water_Consumption_Liters                   int64
Internet_Usage_GB                        float64
Online_Food_Orders                         int64
Daily_Spending_INR                       float64
Hospital_Visits                            int64
Emergency_Complaints                       int64
Work_Hours                               float64
Outdoor_Activity_Hours                   float64
Happiness_Score                          float64
Service_Satisfaction                     float64
Weekend                                   string
Month                                      int32
Year                                       int32
Day                                        int32
Month_Name                                string
Quarter                                    int32
dtype: object

In [ ]:
print(df["Hospital_Visits"].value_counts().sort_index())
print(df["Emergency_Complaints"].value_counts().sort_index())

Hospital_Visits
0    99852
1      148
Name: count, dtype: int64
Emergency_Complaints
0    97003
1     2520
2      477
Name: count, dtype: int64

In [144]:
df.to_csv("cleaned_data.csv", index=False)