# Import Pandas

In [2]:
import pandas as pd
import numpy as np

# Upload File In Pandas

In [3]:
df = pd.read_excel(r"C:\EXCEL\employee_data_cleaning_practice.xlsx")
df

    emp_id   name   age department    city   salary joining_date
0    E1000    NaN   NaN         HR    Pune  50000.0   2022-06-19
1    E1001  Pooja  30.0    Finance   Delhi  60000.0   2021-08-18
2    E1002  Ankit  22.0        NaN     NaN      NaN   2023-04-06
3    E1003    NaN   NaN         HR  Mumbai  30000.0   2021-06-30
4    E1004   Neha  35.0      Sales  Mumbai      NaN   2019-05-14
..     ...    ...   ...        ...     ...      ...          ...
100  E1000    NaN   NaN         HR    Pune  50000.0   2022-06-19
101  E1001  Pooja  30.0    Finance   Delhi  60000.0   2021-08-18
102  E1002  Ankit  22.0        NaN     NaN      NaN   2023-04-06
103  E1003    NaN   NaN         HR  Mumbai  30000.0   2021-06-30
104  E1004   Neha  35.0      Sales  Mumbai      NaN   2019-05-14

[105 rows x 7 columns]

# Data ko samajhana

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   emp_id        105 non-null    object
 1   name          87 non-null     object
 2   age           89 non-null     float64
 3   department    95 non-null     object
 4   city          86 non-null     object
 5   salary        77 non-null     float64
 6   joining_date  105 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(4)
memory usage: 5.9+ KB

In [5]:
df.head()

  emp_id   name   age department    city   salary joining_date
0  E1000    NaN   NaN         HR    Pune  50000.0   2022-06-19
1  E1001  Pooja  30.0    Finance   Delhi  60000.0   2021-08-18
2  E1002  Ankit  22.0        NaN     NaN      NaN   2023-04-06
3  E1003    NaN   NaN         HR  Mumbai  30000.0   2021-06-30
4  E1004   Neha  35.0      Sales  Mumbai      NaN   2019-05-14

In [6]:
df.tail()

    emp_id   name   age department    city   salary joining_date
100  E1000    NaN   NaN         HR    Pune  50000.0   2022-06-19
101  E1001  Pooja  30.0    Finance   Delhi  60000.0   2021-08-18
102  E1002  Ankit  22.0        NaN     NaN      NaN   2023-04-06
103  E1003    NaN   NaN         HR  Mumbai  30000.0   2021-06-30
104  E1004   Neha  35.0      Sales  Mumbai      NaN   2019-05-14

In [7]:
df.shape

(105, 7)

In [8]:
df.describe().round()

        age   salary                   joining_date
count  89.0     77.0                            105
mean   28.0  46364.0  2020-11-07 23:05:08.571428608
min    22.0  30000.0            2018-02-04 00:00:00
25%    25.0  40000.0            2019-10-25 00:00:00
50%    28.0  50000.0            2020-11-08 00:00:00
75%    30.0  60000.0            2022-02-25 00:00:00
max    35.0  60000.0            2023-04-30 00:00:00
std     5.0  11688.0                            NaN

# Check Missing Value

In [9]:
df.isnull().sum()

emp_id           0
name            18
age             16
department      10
city            19
salary          28
joining_date     0
dtype: int64

# Duplicate Value check

In [10]:
df["emp_id"].value_counts().head

<bound method NDFrame.head of emp_id
E1000    2
E1001    2
E1002    2
E1003    2
E1004    2
        ..
E1095    1
E1096    1
E1097    1
E1098    1
E1099    1
Name: count, Length: 100, dtype: int64>

In [11]:
for col in df.columns:
    if df[col].nunique() < 20:
        print(df[col].value_counts())
        print('-'*50)

name
Pooja    22
Rohit    17
Suman    15
Ankit    13
Neha     12
Amit      8
Name: count, dtype: int64
--------------------------------------------------
age
22.0    22
30.0    20
35.0    19
28.0    17
25.0    11
Name: count, dtype: int64
--------------------------------------------------
department
HR         31
Finance    25
Sales      25
IT         14
Name: count, dtype: int64
--------------------------------------------------
city
Delhi        24
Mumbai       24
Pune         20
Bangalore    18
Name: count, dtype: int64
--------------------------------------------------
salary
60000.0    26
40000.0    20
30000.0    17
50000.0    14
Name: count, dtype: int64
--------------------------------------------------

Parameter:
1. `df["emp_id"]`
- DataFrame ka emp_id column select karta hai

2. `value_counts()` 
- Kitni baar repeat huaa hai ye count karta hai
- har unique emp_id

In [12]:
df[df.duplicated()]

    emp_id   name   age department    city   salary joining_date
100  E1000    NaN   NaN         HR    Pune  50000.0   2022-06-19
101  E1001  Pooja  30.0    Finance   Delhi  60000.0   2021-08-18
102  E1002  Ankit  22.0        NaN     NaN      NaN   2023-04-06
103  E1003    NaN   NaN         HR  Mumbai  30000.0   2021-06-30
104  E1004   Neha  35.0      Sales  Mumbai      NaN   2019-05-14

# Remove Duplicate

In [13]:
df.drop_duplicates(subset="emp_id", inplace=True)
df

   emp_id   name   age department       city   salary joining_date
0   E1000    NaN   NaN         HR       Pune  50000.0   2022-06-19
1   E1001  Pooja  30.0    Finance      Delhi  60000.0   2021-08-18
2   E1002  Ankit  22.0        NaN        NaN      NaN   2023-04-06
3   E1003    NaN   NaN         HR     Mumbai  30000.0   2021-06-30
4   E1004   Neha  35.0      Sales     Mumbai      NaN   2019-05-14
..    ...    ...   ...        ...        ...      ...          ...
95  E1095  Suman  22.0         HR     Mumbai  50000.0   2022-02-01
96  E1096  Pooja  22.0    Finance     Mumbai  60000.0   2022-02-16
97  E1097  Suman  22.0    Finance      Delhi      NaN   2022-05-08
98  E1098    NaN  28.0      Sales  Bangalore      NaN   2021-03-20
99  E1099    NaN   NaN         HR     Mumbai  60000.0   2021-03-13

[100 rows x 7 columns]

In [14]:
df.duplicated().sum()

np.int64(0)

In [16]:
df

   emp_id   name   age department       city   salary joining_date
0   E1000    NaN   NaN         HR       Pune  50000.0   2022-06-19
1   E1001  Pooja  30.0    Finance      Delhi  60000.0   2021-08-18
2   E1002  Ankit  22.0        NaN        NaN      NaN   2023-04-06
3   E1003    NaN   NaN         HR     Mumbai  30000.0   2021-06-30
4   E1004   Neha  35.0      Sales     Mumbai      NaN   2019-05-14
..    ...    ...   ...        ...        ...      ...          ...
95  E1095  Suman  22.0         HR     Mumbai  50000.0   2022-02-01
96  E1096  Pooja  22.0    Finance     Mumbai  60000.0   2022-02-16
97  E1097  Suman  22.0    Finance      Delhi      NaN   2022-05-08
98  E1098    NaN  28.0      Sales  Bangalore      NaN   2021-03-20
99  E1099    NaN   NaN         HR     Mumbai  60000.0   2021-03-13

[100 rows x 7 columns]

# Handle Missing Value

In [15]:
df.dropna(subset=["emp_id"], inplace=True)

In [17]:
df['age'] = (
    df['age']
    .apply(lambda x: int(round(x)) if pd.notna(x) else None)
    .astype('Int64')
)

In [18]:
df["age"].dtype
df.head()

  emp_id   name   age department    city   salary joining_date
0  E1000    NaN  <NA>         HR    Pune  50000.0   2022-06-19
1  E1001  Pooja    30    Finance   Delhi  60000.0   2021-08-18
2  E1002  Ankit    22        NaN     NaN      NaN   2023-04-06
3  E1003    NaN  <NA>         HR  Mumbai  30000.0   2021-06-30
4  E1004   Neha    35      Sales  Mumbai      NaN   2019-05-14

In [19]:
df['salary'] = (
    df['salary']
    .apply(lambda x: int(round(x)) if pd.notna(x) else None)
    .astype('Int64')
)

✅Sirf Date (YYYY-MM-DD) rakhna

In [20]:
df["joining_date"] = pd.to_datetime(df["joining_date"]).dt.date

String format me clean date

In [21]:
df["joining_date"] = pd.to_datetime(df["joining_date"]).dt.strftime("%d-%m-%Y")

In [22]:
df.head(3)

  emp_id   name   age department   city  salary joining_date
0  E1000    NaN  <NA>         HR   Pune   50000   19-06-2022
1  E1001  Pooja    30    Finance  Delhi   60000   18-08-2021
2  E1002  Ankit    22        NaN    NaN    <NA>   06-04-2023

Fill missing valuue in rendom number

In [23]:
df['age'] = df['age'].apply(
    lambda x: np.random.randint(22, 35) if pd.isna(x) else x
)

In [24]:
df.describe()

              age        salary
count  100.000000          74.0
mean    28.060000  46351.351351
std      4.449083  11654.186657
min     22.000000       30000.0
25%     25.000000       40000.0
50%     28.000000       50000.0
75%     30.000000       60000.0
max     35.000000       60000.0

In [25]:
df['salary'] = df['salary'].apply(
    lambda x: np.random.randint(3000, 6000) if pd.isna(x) else x
)

In [26]:
df['name'] = df['name'].apply(
    lambda x: np.random.choice(df['name'].dropna()) if pd.isna(x) else x
)

In [27]:
df['department'] = df['department'].apply(
    lambda x: np.random.choice(df['department'].dropna()) if pd.isna(x) else x
)

In [28]:
df['city'] = df['city'].apply(
    lambda x: np.random.choice(df['city'].dropna()) if pd.isna(x) else x
)

In [29]:
df.isnull().sum()

emp_id          0
name            0
age             0
department      0
city            0
salary          0
joining_date    0
dtype: int64

# fixing Inconsistent Formatting

In [30]:
df["name"].unique()

array(['Rohit', 'Pooja', 'Ankit', 'Neha', 'Suman', 'Amit'], dtype=object)

In [31]:
df['emp_id'].str.upper()
df

   emp_id   name   age department       city   salary joining_date
0   E1000  Rohit  30.0         HR       Pune  50000.0   19-06-2022
1   E1001  Pooja  30.0    Finance      Delhi  60000.0   18-08-2021
2   E1002  Ankit  22.0    Finance  Bangalore   3745.0   06-04-2023
3   E1003   Neha  26.0         HR     Mumbai  30000.0   30-06-2021
4   E1004   Neha  35.0      Sales     Mumbai   4445.0   14-05-2019
..    ...    ...   ...        ...        ...      ...          ...
95  E1095  Suman  22.0         HR     Mumbai  50000.0   01-02-2022
96  E1096  Pooja  22.0    Finance     Mumbai  60000.0   16-02-2022
97  E1097  Suman  22.0    Finance      Delhi   3270.0   08-05-2022
98  E1098   Neha  28.0      Sales  Bangalore   4277.0   20-03-2021
99  E1099  Rohit  23.0         HR     Mumbai  60000.0   13-03-2021

[100 rows x 7 columns]

In [32]:
df.to_excel("employee_data_cleaning_practice.xlsx", index=False)