In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel(r"c:\Pandas practice Data\01_Data.xlsx")
df

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,Unknown,Finance,50653.0,18-12-2020,Delhi,4
1,47,Ravi,29,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40,HR,NaN,18-09-2022,Pune,1
3,36,Sneha,34,Sales,NaN,15-11-2020,Delhi,4
4,24,Karan,27,IT,31899.0,28-07-2022,Kolkata,1
...,...,...,...,...,...,...,...,...
95,27,Ravi,28,HR,NaN,11-01-2021,Chennai,4
96,10,Sneha,Unknown,Sales,72570.0,17-01-2021,Kolkata,1
97,30,Karan,Unknown,Sales,46938.0,18-12-2020,Kolkata,5
98,12,Rahul,Unknown,Finance,NaN,02-04-2022,Mumbai,4
99,27,Pooja,Unknown,Finance,NaN,23-08-2022,Chennai,2

# Basic Data Inspection

In [4]:
df.head()

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,Unknown,Finance,50653.0,18-12-2020,Delhi,4
1,47,Ravi,29,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40,HR,NaN,18-09-2022,Pune,1
3,36,Sneha,34,Sales,NaN,15-11-2020,Delhi,4
4,24,Karan,27,IT,31899.0,28-07-2022,Kolkata,1

In [5]:
df.tail()

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
95,27,Ravi,28,HR,NaN,11-01-2021,Chennai,4
96,10,Sneha,Unknown,Sales,72570.0,17-01-2021,Kolkata,1
97,30,Karan,Unknown,Sales,46938.0,18-12-2020,Kolkata,5
98,12,Rahul,Unknown,Finance,NaN,02-04-2022,Mumbai,4
99,27,Pooja,Unknown,Finance,NaN,23-08-2022,Chennai,2

In [6]:
df.shape

(100, 8)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Emp_ID             100 non-null    int64
 1   Name               100 non-null    object
 2   Age                100 non-null    object
 3   Department         100 non-null    object
 4   Salary             53 non-null     float64
 5   Joining_Date       100 non-null    object
 6   City               100 non-null    object
 7   Performance_Score  100 non-null    int64
dtypes: float64(1), int64(2), object(5)
memory usage: 6.4+ KB

In [8]:
df.describe()

           Emp_ID        Salary  Performance_Score
count  100.000000     53.000000         100.000000
mean    24.310000  56121.264151           3.000000
std     14.765299  15065.095846           1.497473
min      1.000000  31899.000000           1.000000
25%     10.000000  40528.000000           1.750000
50%     25.000000  57969.000000           3.000000
75%     36.000000  69668.000000           4.000000
max     50.000000  79253.000000           5.000000

In [9]:
df.columns

Index(['Emp_ID', 'Name', 'Age', 'Department', 'Salary', 'Joining_Date', 'City',
       'Performance_Score'],
      dtype='object')

In [10]:
df.dtypes

Emp_ID                 int64
Name                  object
Age                   object
Department            object
Salary               float64
Joining_Date          object
City                  object
Performance_Score      int64
dtype: object

# Duplicate

In [11]:
df.isnull().sum()

Emp_ID                0
Name                  0
Age                   0
Department            0
Salary               47
Joining_Date          0
City                  0
Performance_Score     0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

Convert INT

In [13]:
df["Salary"] = df["Salary"].round().astype("Int64")
df

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,Unknown,Finance,50653,18-12-2020,Delhi,4
1,47,Ravi,29,HR,69988,18-10-2020,Mumbai,2
2,29,Priya,40,HR,<NA>,18-09-2022,Pune,1
3,36,Sneha,34,Sales,<NA>,15-11-2020,Delhi,4
4,24,Karan,27,IT,31899,28-07-2022,Kolkata,1
...,...,...,...,...,...,...,...,...
95,27,Ravi,28,HR,<NA>,11-01-2021,Chennai,4
96,10,Sneha,Unknown,Sales,72570,17-01-2021,Kolkata,1
97,30,Karan,Unknown,Sales,46938,18-12-2020,Kolkata,5
98,12,Rahul,Unknown,Finance,<NA>,02-04-2022,Mumbai,4
99,27,Pooja,Unknown,Finance,<NA>,23-08-2022,Chennai,2

# Fill Missing Value

In [14]:
df["Salary"] = df["Salary"].apply(
    lambda x: np.random.randint(31899, 79253) if pd.isna(x) else x
)
df

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,Unknown,Finance,50653.0,18-12-2020,Delhi,4
1,47,Ravi,29,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40,HR,71920.0,18-09-2022,Pune,1
3,36,Sneha,34,Sales,72905.0,15-11-2020,Delhi,4
4,24,Karan,27,IT,31899.0,28-07-2022,Kolkata,1
...,...,...,...,...,...,...,...,...
95,27,Ravi,28,HR,49939.0,11-01-2021,Chennai,4
96,10,Sneha,Unknown,Sales,72570.0,17-01-2021,Kolkata,1
97,30,Karan,Unknown,Sales,46938.0,18-12-2020,Kolkata,5
98,12,Rahul,Unknown,Finance,58011.0,02-04-2022,Mumbai,4
99,27,Pooja,Unknown,Finance,75038.0,23-08-2022,Chennai,2

# Age Fill Missing value
- "unknown" ko NaN me convert karo

In [15]:
df["Age"] = df["Age"].replace("Unknown", np.nan)
df

C:\Users\Anish Kumar\AppData\Local\Temp\ipykernel_28596\301595900.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Age"] = df["Age"].replace("Unknown", np.nan)

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,NaN,Finance,50653.0,18-12-2020,Delhi,4
1,47,Ravi,29.0,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40.0,HR,71920.0,18-09-2022,Pune,1
3,36,Sneha,34.0,Sales,72905.0,15-11-2020,Delhi,4
4,24,Karan,27.0,IT,31899.0,28-07-2022,Kolkata,1
...,...,...,...,...,...,...,...,...
95,27,Ravi,28.0,HR,49939.0,11-01-2021,Chennai,4
96,10,Sneha,NaN,Sales,72570.0,17-01-2021,Kolkata,1
97,30,Karan,NaN,Sales,46938.0,18-12-2020,Kolkata,5
98,12,Rahul,NaN,Finance,58011.0,02-04-2022,Mumbai,4
99,27,Pooja,NaN,Finance,75038.0,23-08-2022,Chennai,2

# Age ko numeric type me convert karo

In [16]:
df["Age"] = pd.to_numeric(df["Age"])
df

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,NaN,Finance,50653.0,18-12-2020,Delhi,4
1,47,Ravi,29.0,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40.0,HR,71920.0,18-09-2022,Pune,1
3,36,Sneha,34.0,Sales,72905.0,15-11-2020,Delhi,4
4,24,Karan,27.0,IT,31899.0,28-07-2022,Kolkata,1
...,...,...,...,...,...,...,...,...
95,27,Ravi,28.0,HR,49939.0,11-01-2021,Chennai,4
96,10,Sneha,NaN,Sales,72570.0,17-01-2021,Kolkata,1
97,30,Karan,NaN,Sales,46938.0,18-12-2020,Kolkata,5
98,12,Rahul,NaN,Finance,58011.0,02-04-2022,Mumbai,4
99,27,Pooja,NaN,Finance,75038.0,23-08-2022,Chennai,2

# Fill Missing Value

In [20]:
df["Age"] = df["Age"].apply(
    lambda x: np.random.randint(21, 40) if pd.isna(x) else x
)
df

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,22.0,Finance,50653.0,18-12-2020,Delhi,4
1,47,Ravi,29.0,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40.0,HR,71920.0,18-09-2022,Pune,1
3,36,Sneha,34.0,Sales,72905.0,15-11-2020,Delhi,4
4,24,Karan,27.0,IT,31899.0,28-07-2022,Kolkata,1
...,...,...,...,...,...,...,...,...
95,27,Ravi,28.0,HR,49939.0,11-01-2021,Chennai,4
96,10,Sneha,31.0,Sales,72570.0,17-01-2021,Kolkata,1
97,30,Karan,36.0,Sales,46938.0,18-12-2020,Kolkata,5
98,12,Rahul,27.0,Finance,58011.0,02-04-2022,Mumbai,4
99,27,Pooja,34.0,Finance,75038.0,23-08-2022,Chennai,2

# ⭐ Selection & Filtering

# SELECTION IN PANDAS

# ✅ A) Single Column

In [21]:
df["Name"]

0      Neha
1      Ravi
2     Priya
3     Sneha
4     Karan
      ...
95     Ravi
96    Sneha
97    Karan
98    Rahul
99    Pooja
Name: Name, Length: 100, dtype: object

# ✅ B) Multiple Columns

In [22]:
df[["Age", "Salary"]]

     Age   Salary
0   22.0  50653.0
1   29.0  69988.0
2   40.0  71920.0
3   34.0  72905.0
4   27.0  31899.0
..   ...      ...
95  28.0  49939.0
96  31.0  72570.0
97  36.0  46938.0
98  27.0  58011.0
99  34.0  75038.0

[100 rows x 2 columns]

# 2️⃣ Row Selection

# 🔹 A) loc[] (Label Based Selection)
- `df.loc[row_label , column_label]`

✅ Example 1: First 5 rows

In [23]:
df.loc[0:4]

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,22.0,Finance,50653.0,18-12-2020,Delhi,4
1,47,Ravi,29.0,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40.0,HR,71920.0,18-09-2022,Pune,1
3,36,Sneha,34.0,Sales,72905.0,15-11-2020,Delhi,4
4,24,Karan,27.0,IT,31899.0,28-07-2022,Kolkata,1

✅ Example 2: Specific row & column

In [24]:
df.loc[2, "Department"]

'HR'

✅ Example 3: Rows 0-5 & specific columns

In [25]:
df.loc[0:4, "Salary"]

0    50653.0
1    69988.0
2    71920.0
3    72905.0
4    31899.0
Name: Salary, dtype: float64

# 🔹 B) iloc[] (Position Based Selection)
`df.iloc[row_position , column_position]`

✅ Example 1: First 5 rows

In [26]:
df.iloc[0:5]

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,22.0,Finance,50653.0,18-12-2020,Delhi,4
1,47,Ravi,29.0,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40.0,HR,71920.0,18-09-2022,Pune,1
3,36,Sneha,34.0,Sales,72905.0,15-11-2020,Delhi,4
4,24,Karan,27.0,IT,31899.0,28-07-2022,Kolkata,1

✅ Example 2: Specific row & column

In [27]:
df.iloc[2, 1]

'Priya'

✅ Example 3: Rows & Columns

In [28]:
df.iloc[0:3, 1:3]

    Name   Age
0   Neha  22.0
1   Ravi  29.0
2  Priya  40.0

# 🔷 PART 2: FILTERING IN PANDAS
🔹 Filtering kya hota hai?
- 👉 Condition ke base par rows select karna.

# 1️⃣ Basic Filtering
✅ Salary > 50000

In [29]:
df[df["Salary"] > 50000]

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,22.0,Finance,50653.0,18-12-2020,Delhi,4
1,47,Ravi,29.0,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40.0,HR,71920.0,18-09-2022,Pune,1
3,36,Sneha,34.0,Sales,72905.0,15-11-2020,Delhi,4
5,43,Rahul,23.0,Finance,65085.0,12-12-2021,Delhi,2
...,...,...,...,...,...,...,...,...
92,3,Rahul,31.0,HR,69668.0,13-10-2020,Chennai,1
94,43,Karan,27.0,Finance,74583.0,19-02-2022,Mumbai,1
96,10,Sneha,31.0,Sales,72570.0,17-01-2021,Kolkata,1
98,12,Rahul,27.0,Finance,58011.0,02-04-2022,Mumbai,4
99,27,Pooja,34.0,Finance,75038.0,23-08-2022,Chennai,2

✅ Department == IT

In [30]:
df[df["Department"] == 'IT']

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
4,24,Karan,27.0,IT,31899.0,28-07-2022,Kolkata,1
23,50,Neha,39.0,IT,62722.0,03-01-2022,Kolkata,4
34,19,Sneha,29.0,IT,59160.0,15-10-2021,Pune,5
38,24,Priya,28.0,IT,51268.0,17-02-2020,Kolkata,1
39,28,Rahul,29.0,IT,52494.0,10-02-2021,Kolkata,4
47,30,Priya,30.0,IT,33405.0,15-11-2021,Mumbai,5
49,1,Amit,26.0,IT,33524.0,28-04-2022,Chennai,4
52,33,Karan,34.0,IT,73498.0,01-06-2021,Chennai,1
58,9,Sneha,33.0,IT,78948.0,02-02-2022,Delhi,4
61,29,Ravi,27.0,IT,38191.0,07-02-2022,Pune,1
62,44,Ravi,37.0,IT,61561.0,22-05-2020,Pune,3
64,40,Rahul,38.0,IT,68535.0,10-12-2020,Pune,1
66,27,Pooja,34.0,IT,37652.0,28-02-2022,Pune,4
67,23,Ravi,26.0,IT,57759.0,12-11-2021,Kolkata,1
74,39,Sneha,36.0,IT,79253.0,14-02-2022,Kolkata,4
75,5,Pooja,30.0,IT,34692.0,14-01-2020,Pune,1
76,12,Sneha,27.0,IT,75298.0,11-01-2021,Kolkata,4
81,31,Amit,33.0,IT,43313.0,01-03-2021,Delhi,5
85,29,Amit,26.0,IT,34313.0,11-07-2020,Pune,5

# 2️⃣ Multiple Conditions

✅ AND Condition (&)

In [31]:
df[(df["Age"] > 25) & (df["Salary"] > 40000)]

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
1,47,Ravi,29.0,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40.0,HR,71920.0,18-09-2022,Pune,1
3,36,Sneha,34.0,Sales,72905.0,15-11-2020,Delhi,4
7,36,Priya,34.0,HR,62662.0,02-10-2021,Chennai,2
9,10,Priya,38.0,HR,73454.0,21-07-2022,Pune,4
10,20,Neha,38.0,Finance,63645.0,20-11-2020,Delhi,5
11,16,Sneha,37.0,HR,79070.0,11-10-2020,Chennai,2
13,15,Neha,26.0,Finance,47550.0,27-09-2021,Mumbai,5
14,4,Neha,40.0,Sales,48924.0,18-05-2021,Chennai,3
23,50,Neha,39.0,IT,62722.0,03-01-2022,Kolkata,4
25,47,Rahul,38.0,HR,66914.0,02-05-2020,Mumbai,5
26,1,Priya,36.0,Sales,77696.0,10-09-2022,Mumbai,1
28,33,Rahul,32.0,Sales,54048.0,18-09-2022,Delhi,1
29,35,Amit,34.0,Sales,51314.0,29-05-2022,Mumbai,1
30,6,Sneha,38.0,Finance,69934.0,24-10-2020,Chennai,3
31,12,Ravi,32.0,Sales,60430.0,22-01-2022,Pune,5
32,4,Sneha,32.0,Sales,55851.0,07-04-2021,Mumbai,4
33,19,Amit,28.0,Sales,54819.0,24-08-2021,Chennai,4
34,19,Sneha,29.0,IT,59160.0,15-10-2021,Pune,5
35,33,Rahul,40.0,Sales,53693.0,07-05-2022,Pune,3
36,3,Neha,30.0,HR,40528.0,18-03-2020,Chennai,5
37,49,Sneha,37.0,Finance,54003.0,11-01-2020,Pune,1
38,24,Priya,28.0,IT,51268.0,17-02-2020,Kolkata,1
39,28,Rahul,29.0,IT,52494.0,10-02-2021,Kolkata,4
43,40,Rahul,32.0,HR,56007.0,03-06-2020,Pune,3
46,3,Karan,30.0,HR,43817.0,01-11-2020,Pune,2
48,21,Amit,28.0,HR,49800.0,03-07-2021,Pune,5
51,30,Sneha,33.0,Finance,62797.0,15-06-2020,Delhi,5
52,33,Karan,34.0,IT,73498.0,01-06-2021,Chennai,1
53,48,Rahul,39.0,Sales,41176.0,23-03-2020,Delhi,3
56,42,Rahul,36.0,Finance,42615.0,15-03-2020,Chennai,3
58,9,Sneha,33.0,IT,78948.0,02-02-2022,Delhi,4
60,31,Sneha,40.0,Sales,53518.0,11-04-2021,Pune,1
62,44,Ravi,37.0,IT,61561.0,22-05-2020,Pune,3
63,47,Pooja,30.0,Finance,74353.0,22-02-2022,Kolkata,4
64,40,Rahul,38.0,IT,68535.0,10-12-2020,Pune,1
65,17,Priya,31.0,Sales,66960.0,29-12-2020,Delhi,1
67,23,Ravi,26.0,IT,57759.0,12-11-2021,Kolkata,1
68,9,Ravi,37.0,HR,64592.0,01-09-2020,Pune,1
72,23,Amit,37.0,HR,46595.0,04-12-2021,Pune,2
74,39,Sneha,36.0,IT,79253.0,14-02-2022,Kolkata,4
76,12,Sneha,27.0,IT,75298.0,11-01-2021,Kolkata,4
77,8,Ravi,37.0,HR,55883.0,15-09-2022,Mumbai,5
78,17,Amit,39.0,Sales,63053.0,28-01-2020,Delhi,1
80,47,Pooja,35.0,HR,55772.0,14-12-2021,Pune,5
81,31,Amit,33.0,IT,43313.0,01-03-2021,Delhi,5
82,7,Karan,27.0,HR,57202.0,07-06-2021,Pune,2
83,9,Neha,30.0,Finance,66296.0,04-02-2020,Chennai,5
86,35,Karan,29.0,Finance,63126.0,19-04-2022,Mumbai,4
88,26,Ravi,33.0,Finance,75826.0,12-01-2022,Chennai,4
90,6,Karan,37.0,Sales,54810.0,10-06-2022,Kolkata,3
92,3,Rahul,31.0,HR,69668.0,13-10-2020,Chennai,1
94,43,Karan,27.0,Finance,74583.0,19-02-2022,Mumbai,1
95,27,Ravi,28.0,HR,49939.0,11-01-2021,Chennai,4
96,10,Sneha,31.0,Sales,72570.0,17-01-2021,Kolkata,1
97,30,Karan,36.0,Sales,46938.0,18-12-2020,Kolkata,5
98,12,Rahul,27.0,Finance,58011.0,02-04-2022,Mumbai,4
99,27,Pooja,34.0,Finance,75038.0,23-08-2022,Chennai,2

✅ OR Condition (|)

In [32]:
df[(df["Department"] == "IT") | (df["Department"] == "HR")]

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
1,47,Ravi,29.0,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40.0,HR,71920.0,18-09-2022,Pune,1
4,24,Karan,27.0,IT,31899.0,28-07-2022,Kolkata,1
7,36,Priya,34.0,HR,62662.0,02-10-2021,Chennai,2
9,10,Priya,38.0,HR,73454.0,21-07-2022,Pune,4
11,16,Sneha,37.0,HR,79070.0,11-10-2020,Chennai,2
12,41,Amit,24.0,HR,34481.0,06-05-2022,Mumbai,1
16,8,Karan,36.0,HR,36733.0,29-08-2020,Mumbai,2
19,32,Priya,26.0,HR,34661.0,29-01-2020,Chennai,4
21,8,Karan,32.0,HR,37793.0,22-12-2020,Delhi,2
23,50,Neha,39.0,IT,62722.0,03-01-2022,Kolkata,4
25,47,Rahul,38.0,HR,66914.0,02-05-2020,Mumbai,5
27,37,Ravi,21.0,HR,75765.0,19-10-2021,Delhi,1
34,19,Sneha,29.0,IT,59160.0,15-10-2021,Pune,5
36,3,Neha,30.0,HR,40528.0,18-03-2020,Chennai,5
38,24,Priya,28.0,IT,51268.0,17-02-2020,Kolkata,1
39,28,Rahul,29.0,IT,52494.0,10-02-2021,Kolkata,4
43,40,Rahul,32.0,HR,56007.0,03-06-2020,Pune,3
44,39,Ravi,21.0,HR,74456.0,23-11-2021,Mumbai,5
45,15,Rahul,24.0,HR,36754.0,11-09-2022,Chennai,4
46,3,Karan,30.0,HR,43817.0,01-11-2020,Pune,2
47,30,Priya,30.0,IT,33405.0,15-11-2021,Mumbai,5
48,21,Amit,28.0,HR,49800.0,03-07-2021,Pune,5
49,1,Amit,26.0,IT,33524.0,28-04-2022,Chennai,4
50,4,Neha,21.0,HR,67218.0,12-08-2021,Chennai,5
52,33,Karan,34.0,IT,73498.0,01-06-2021,Chennai,1
54,40,Rahul,36.0,HR,34389.0,19-12-2020,Mumbai,4
58,9,Sneha,33.0,IT,78948.0,02-02-2022,Delhi,4
61,29,Ravi,27.0,IT,38191.0,07-02-2022,Pune,1
62,44,Ravi,37.0,IT,61561.0,22-05-2020,Pune,3
64,40,Rahul,38.0,IT,68535.0,10-12-2020,Pune,1
66,27,Pooja,34.0,IT,37652.0,28-02-2022,Pune,4
67,23,Ravi,26.0,IT,57759.0,12-11-2021,Kolkata,1
68,9,Ravi,37.0,HR,64592.0,01-09-2020,Pune,1
69,17,Ravi,29.0,HR,34772.0,01-12-2021,Kolkata,5
71,15,Neha,21.0,HR,42574.0,29-10-2021,Delhi,1
72,23,Amit,37.0,HR,46595.0,04-12-2021,Pune,2
74,39,Sneha,36.0,IT,79253.0,14-02-2022,Kolkata,4
75,5,Pooja,30.0,IT,34692.0,14-01-2020,Pune,1
76,12,Sneha,27.0,IT,75298.0,11-01-2021,Kolkata,4
77,8,Ravi,37.0,HR,55883.0,15-09-2022,Mumbai,5
79,16,Pooja,39.0,HR,39119.0,11-03-2020,Pune,3
80,47,Pooja,35.0,HR,55772.0,14-12-2021,Pune,5
81,31,Amit,33.0,IT,43313.0,01-03-2021,Delhi,5
82,7,Karan,27.0,HR,57202.0,07-06-2021,Pune,2
84,44,Rahul,25.0,HR,42007.0,16-02-2022,Pune,3
85,29,Amit,26.0,IT,34313.0,11-07-2020,Pune,5
92,3,Rahul,31.0,HR,69668.0,13-10-2020,Chennai,1
93,15,Pooja,38.0,HR,39204.0,13-04-2022,Mumbai,2
95,27,Ravi,28.0,HR,49939.0,11-01-2021,Chennai,4

3️⃣ NOT Condition (~)

In [33]:
df[~(df["Department"] == "IT")]

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,22.0,Finance,50653.0,18-12-2020,Delhi,4
1,47,Ravi,29.0,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40.0,HR,71920.0,18-09-2022,Pune,1
3,36,Sneha,34.0,Sales,72905.0,15-11-2020,Delhi,4
5,43,Rahul,23.0,Finance,65085.0,12-12-2021,Delhi,2
...,...,...,...,...,...,...,...,...
95,27,Ravi,28.0,HR,49939.0,11-01-2021,Chennai,4
96,10,Sneha,31.0,Sales,72570.0,17-01-2021,Kolkata,1
97,30,Karan,36.0,Sales,46938.0,18-12-2020,Kolkata,5
98,12,Rahul,27.0,Finance,58011.0,02-04-2022,Mumbai,4
99,27,Pooja,34.0,Finance,75038.0,23-08-2022,Chennai,2

4️⃣ isin() Function

In [34]:
df[df["Department"].isin(["IT", "HR"])]

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
1,47,Ravi,29.0,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40.0,HR,71920.0,18-09-2022,Pune,1
4,24,Karan,27.0,IT,31899.0,28-07-2022,Kolkata,1
7,36,Priya,34.0,HR,62662.0,02-10-2021,Chennai,2
9,10,Priya,38.0,HR,73454.0,21-07-2022,Pune,4
11,16,Sneha,37.0,HR,79070.0,11-10-2020,Chennai,2
12,41,Amit,24.0,HR,34481.0,06-05-2022,Mumbai,1
16,8,Karan,36.0,HR,36733.0,29-08-2020,Mumbai,2
19,32,Priya,26.0,HR,34661.0,29-01-2020,Chennai,4
21,8,Karan,32.0,HR,37793.0,22-12-2020,Delhi,2
23,50,Neha,39.0,IT,62722.0,03-01-2022,Kolkata,4
25,47,Rahul,38.0,HR,66914.0,02-05-2020,Mumbai,5
27,37,Ravi,21.0,HR,75765.0,19-10-2021,Delhi,1
34,19,Sneha,29.0,IT,59160.0,15-10-2021,Pune,5
36,3,Neha,30.0,HR,40528.0,18-03-2020,Chennai,5
38,24,Priya,28.0,IT,51268.0,17-02-2020,Kolkata,1
39,28,Rahul,29.0,IT,52494.0,10-02-2021,Kolkata,4
43,40,Rahul,32.0,HR,56007.0,03-06-2020,Pune,3
44,39,Ravi,21.0,HR,74456.0,23-11-2021,Mumbai,5
45,15,Rahul,24.0,HR,36754.0,11-09-2022,Chennai,4
46,3,Karan,30.0,HR,43817.0,01-11-2020,Pune,2
47,30,Priya,30.0,IT,33405.0,15-11-2021,Mumbai,5
48,21,Amit,28.0,HR,49800.0,03-07-2021,Pune,5
49,1,Amit,26.0,IT,33524.0,28-04-2022,Chennai,4
50,4,Neha,21.0,HR,67218.0,12-08-2021,Chennai,5
52,33,Karan,34.0,IT,73498.0,01-06-2021,Chennai,1
54,40,Rahul,36.0,HR,34389.0,19-12-2020,Mumbai,4
58,9,Sneha,33.0,IT,78948.0,02-02-2022,Delhi,4
61,29,Ravi,27.0,IT,38191.0,07-02-2022,Pune,1
62,44,Ravi,37.0,IT,61561.0,22-05-2020,Pune,3
64,40,Rahul,38.0,IT,68535.0,10-12-2020,Pune,1
66,27,Pooja,34.0,IT,37652.0,28-02-2022,Pune,4
67,23,Ravi,26.0,IT,57759.0,12-11-2021,Kolkata,1
68,9,Ravi,37.0,HR,64592.0,01-09-2020,Pune,1
69,17,Ravi,29.0,HR,34772.0,01-12-2021,Kolkata,5
71,15,Neha,21.0,HR,42574.0,29-10-2021,Delhi,1
72,23,Amit,37.0,HR,46595.0,04-12-2021,Pune,2
74,39,Sneha,36.0,IT,79253.0,14-02-2022,Kolkata,4
75,5,Pooja,30.0,IT,34692.0,14-01-2020,Pune,1
76,12,Sneha,27.0,IT,75298.0,11-01-2021,Kolkata,4
77,8,Ravi,37.0,HR,55883.0,15-09-2022,Mumbai,5
79,16,Pooja,39.0,HR,39119.0,11-03-2020,Pune,3
80,47,Pooja,35.0,HR,55772.0,14-12-2021,Pune,5
81,31,Amit,33.0,IT,43313.0,01-03-2021,Delhi,5
82,7,Karan,27.0,HR,57202.0,07-06-2021,Pune,2
84,44,Rahul,25.0,HR,42007.0,16-02-2022,Pune,3
85,29,Amit,26.0,IT,34313.0,11-07-2020,Pune,5
92,3,Rahul,31.0,HR,69668.0,13-10-2020,Chennai,1
93,15,Pooja,38.0,HR,39204.0,13-04-2022,Mumbai,2
95,27,Ravi,28.0,HR,49939.0,11-01-2021,Chennai,4

5️⃣ between()

In [35]:
df[df["Age"].between(25, 35)]

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
1,47,Ravi,29.0,HR,69988.0,18-10-2020,Mumbai,2
3,36,Sneha,34.0,Sales,72905.0,15-11-2020,Delhi,4
4,24,Karan,27.0,IT,31899.0,28-07-2022,Kolkata,1
7,36,Priya,34.0,HR,62662.0,02-10-2021,Chennai,2
13,15,Neha,26.0,Finance,47550.0,27-09-2021,Mumbai,5
17,44,Amit,25.0,Sales,57969.0,31-08-2020,Chennai,3
19,32,Priya,26.0,HR,34661.0,29-01-2020,Chennai,4
21,8,Karan,32.0,HR,37793.0,22-12-2020,Delhi,2
24,6,Priya,26.0,Sales,34947.0,19-11-2020,Delhi,2
28,33,Rahul,32.0,Sales,54048.0,18-09-2022,Delhi,1
29,35,Amit,34.0,Sales,51314.0,29-05-2022,Mumbai,1
31,12,Ravi,32.0,Sales,60430.0,22-01-2022,Pune,5
32,4,Sneha,32.0,Sales,55851.0,07-04-2021,Mumbai,4
33,19,Amit,28.0,Sales,54819.0,24-08-2021,Chennai,4
34,19,Sneha,29.0,IT,59160.0,15-10-2021,Pune,5
36,3,Neha,30.0,HR,40528.0,18-03-2020,Chennai,5
38,24,Priya,28.0,IT,51268.0,17-02-2020,Kolkata,1
39,28,Rahul,29.0,IT,52494.0,10-02-2021,Kolkata,4
41,11,Neha,33.0,Finance,38382.0,21-05-2021,Chennai,3
42,21,Sneha,30.0,Finance,33941.0,09-11-2020,Chennai,2
43,40,Rahul,32.0,HR,56007.0,03-06-2020,Pune,3
46,3,Karan,30.0,HR,43817.0,01-11-2020,Pune,2
47,30,Priya,30.0,IT,33405.0,15-11-2021,Mumbai,5
48,21,Amit,28.0,HR,49800.0,03-07-2021,Pune,5
49,1,Amit,26.0,IT,33524.0,28-04-2022,Chennai,4
51,30,Sneha,33.0,Finance,62797.0,15-06-2020,Delhi,5
52,33,Karan,34.0,IT,73498.0,01-06-2021,Chennai,1
58,9,Sneha,33.0,IT,78948.0,02-02-2022,Delhi,4
59,34,Sneha,34.0,Finance,39997.0,31-08-2022,Chennai,3
61,29,Ravi,27.0,IT,38191.0,07-02-2022,Pune,1
63,47,Pooja,30.0,Finance,74353.0,22-02-2022,Kolkata,4
65,17,Priya,31.0,Sales,66960.0,29-12-2020,Delhi,1
66,27,Pooja,34.0,IT,37652.0,28-02-2022,Pune,4
67,23,Ravi,26.0,IT,57759.0,12-11-2021,Kolkata,1
69,17,Ravi,29.0,HR,34772.0,01-12-2021,Kolkata,5
75,5,Pooja,30.0,IT,34692.0,14-01-2020,Pune,1
76,12,Sneha,27.0,IT,75298.0,11-01-2021,Kolkata,4
80,47,Pooja,35.0,HR,55772.0,14-12-2021,Pune,5
81,31,Amit,33.0,IT,43313.0,01-03-2021,Delhi,5
82,7,Karan,27.0,HR,57202.0,07-06-2021,Pune,2
83,9,Neha,30.0,Finance,66296.0,04-02-2020,Chennai,5
84,44,Rahul,25.0,HR,42007.0,16-02-2022,Pune,3
85,29,Amit,26.0,IT,34313.0,11-07-2020,Pune,5
86,35,Karan,29.0,Finance,63126.0,19-04-2022,Mumbai,4
88,26,Ravi,33.0,Finance,75826.0,12-01-2022,Chennai,4
91,10,Rahul,25.0,Sales,52292.0,21-04-2021,Delhi,4
92,3,Rahul,31.0,HR,69668.0,13-10-2020,Chennai,1
94,43,Karan,27.0,Finance,74583.0,19-02-2022,Mumbai,1
95,27,Ravi,28.0,HR,49939.0,11-01-2021,Chennai,4
96,10,Sneha,31.0,Sales,72570.0,17-01-2021,Kolkata,1
98,12,Rahul,27.0,Finance,58011.0,02-04-2022,Mumbai,4
99,27,Pooja,34.0,Finance,75038.0,23-08-2022,Chennai,2

6️⃣ String Filtering

Case insensitive:

# 📝 🔥 PRACTICE SET (Level Wise)

# 🟢 LEVEL 1 – Basic Selection
Q1️⃣ Sirf “Name” column select karo.

In [36]:
df["Name"]

0      Neha
1      Ravi
2     Priya
3     Sneha
4     Karan
      ...
95     Ravi
96    Sneha
97    Karan
98    Rahul
99    Pooja
Name: Name, Length: 100, dtype: object

Q2️⃣ “Name” aur “Salary” dono columns select karo.

In [37]:
df[["Name", "Salary"]]

     Name   Salary
0    Neha  50653.0
1    Ravi  69988.0
2   Priya  71920.0
3   Sneha  72905.0
4   Karan  31899.0
..    ...      ...
95   Ravi  49939.0
96  Sneha  72570.0
97  Karan  46938.0
98  Rahul  58011.0
99  Pooja  75038.0

[100 rows x 2 columns]

Q3️⃣ First 10 rows show karo.

In [38]:
df.loc[0:9]

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,22.0,Finance,50653.0,18-12-2020,Delhi,4
1,47,Ravi,29.0,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40.0,HR,71920.0,18-09-2022,Pune,1
3,36,Sneha,34.0,Sales,72905.0,15-11-2020,Delhi,4
4,24,Karan,27.0,IT,31899.0,28-07-2022,Kolkata,1
5,43,Rahul,23.0,Finance,65085.0,12-12-2021,Delhi,2
6,5,Pooja,22.0,Sales,68706.0,25-11-2020,Pune,1
7,36,Priya,34.0,HR,62662.0,02-10-2021,Chennai,2
8,35,Sneha,21.0,Finance,72945.0,10-01-2022,Chennai,2
9,10,Priya,38.0,HR,73454.0,21-07-2022,Pune,4

Q4️⃣ 5th row ka “Department” value nikalo.

In [39]:
df.loc[4, "Department"]

'IT'

# 🟡 LEVEL 2 – Basic Filtering
Q5️⃣ Salary > 60000 wale employees dikhao.

In [40]:
df[df["Salary"] > 60000]

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
1,47,Ravi,29.0,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40.0,HR,71920.0,18-09-2022,Pune,1
3,36,Sneha,34.0,Sales,72905.0,15-11-2020,Delhi,4
5,43,Rahul,23.0,Finance,65085.0,12-12-2021,Delhi,2
6,5,Pooja,22.0,Sales,68706.0,25-11-2020,Pune,1
7,36,Priya,34.0,HR,62662.0,02-10-2021,Chennai,2
8,35,Sneha,21.0,Finance,72945.0,10-01-2022,Chennai,2
9,10,Priya,38.0,HR,73454.0,21-07-2022,Pune,4
10,20,Neha,38.0,Finance,63645.0,20-11-2020,Delhi,5
11,16,Sneha,37.0,HR,79070.0,11-10-2020,Chennai,2
23,50,Neha,39.0,IT,62722.0,03-01-2022,Kolkata,4
25,47,Rahul,38.0,HR,66914.0,02-05-2020,Mumbai,5
26,1,Priya,36.0,Sales,77696.0,10-09-2022,Mumbai,1
27,37,Ravi,21.0,HR,75765.0,19-10-2021,Delhi,1
30,6,Sneha,38.0,Finance,69934.0,24-10-2020,Chennai,3
31,12,Ravi,32.0,Sales,60430.0,22-01-2022,Pune,5
44,39,Ravi,21.0,HR,74456.0,23-11-2021,Mumbai,5
50,4,Neha,21.0,HR,67218.0,12-08-2021,Chennai,5
51,30,Sneha,33.0,Finance,62797.0,15-06-2020,Delhi,5
52,33,Karan,34.0,IT,73498.0,01-06-2021,Chennai,1
57,41,Pooja,24.0,Finance,62308.0,23-08-2022,Kolkata,2
58,9,Sneha,33.0,IT,78948.0,02-02-2022,Delhi,4
62,44,Ravi,37.0,IT,61561.0,22-05-2020,Pune,3
63,47,Pooja,30.0,Finance,74353.0,22-02-2022,Kolkata,4
64,40,Rahul,38.0,IT,68535.0,10-12-2020,Pune,1
65,17,Priya,31.0,Sales,66960.0,29-12-2020,Delhi,1
68,9,Ravi,37.0,HR,64592.0,01-09-2020,Pune,1
70,43,Rahul,21.0,Sales,66924.0,30-04-2020,Delhi,3
74,39,Sneha,36.0,IT,79253.0,14-02-2022,Kolkata,4
76,12,Sneha,27.0,IT,75298.0,11-01-2021,Kolkata,4
78,17,Amit,39.0,Sales,63053.0,28-01-2020,Delhi,1
83,9,Neha,30.0,Finance,66296.0,04-02-2020,Chennai,5
86,35,Karan,29.0,Finance,63126.0,19-04-2022,Mumbai,4
87,35,Rahul,23.0,Sales,62391.0,09-12-2021,Mumbai,4
88,26,Ravi,33.0,Finance,75826.0,12-01-2022,Chennai,4
92,3,Rahul,31.0,HR,69668.0,13-10-2020,Chennai,1
94,43,Karan,27.0,Finance,74583.0,19-02-2022,Mumbai,1
96,10,Sneha,31.0,Sales,72570.0,17-01-2021,Kolkata,1
99,27,Pooja,34.0,Finance,75038.0,23-08-2022,Chennai,2

Q6️⃣ Department == "IT" wale employees dikhao.

In [41]:
df[df["Department"] == "IT"]

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
4,24,Karan,27.0,IT,31899.0,28-07-2022,Kolkata,1
23,50,Neha,39.0,IT,62722.0,03-01-2022,Kolkata,4
34,19,Sneha,29.0,IT,59160.0,15-10-2021,Pune,5
38,24,Priya,28.0,IT,51268.0,17-02-2020,Kolkata,1
39,28,Rahul,29.0,IT,52494.0,10-02-2021,Kolkata,4
47,30,Priya,30.0,IT,33405.0,15-11-2021,Mumbai,5
49,1,Amit,26.0,IT,33524.0,28-04-2022,Chennai,4
52,33,Karan,34.0,IT,73498.0,01-06-2021,Chennai,1
58,9,Sneha,33.0,IT,78948.0,02-02-2022,Delhi,4
61,29,Ravi,27.0,IT,38191.0,07-02-2022,Pune,1
62,44,Ravi,37.0,IT,61561.0,22-05-2020,Pune,3
64,40,Rahul,38.0,IT,68535.0,10-12-2020,Pune,1
66,27,Pooja,34.0,IT,37652.0,28-02-2022,Pune,4
67,23,Ravi,26.0,IT,57759.0,12-11-2021,Kolkata,1
74,39,Sneha,36.0,IT,79253.0,14-02-2022,Kolkata,4
75,5,Pooja,30.0,IT,34692.0,14-01-2020,Pune,1
76,12,Sneha,27.0,IT,75298.0,11-01-2021,Kolkata,4
81,31,Amit,33.0,IT,43313.0,01-03-2021,Delhi,5
85,29,Amit,26.0,IT,34313.0,11-07-2020,Pune,5

Q7️⃣ Age < 30 wale employees show karo.

In [42]:
df[df["Age"] < 30]

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,22.0,Finance,50653.0,18-12-2020,Delhi,4
1,47,Ravi,29.0,HR,69988.0,18-10-2020,Mumbai,2
4,24,Karan,27.0,IT,31899.0,28-07-2022,Kolkata,1
5,43,Rahul,23.0,Finance,65085.0,12-12-2021,Delhi,2
6,5,Pooja,22.0,Sales,68706.0,25-11-2020,Pune,1
8,35,Sneha,21.0,Finance,72945.0,10-01-2022,Chennai,2
12,41,Amit,24.0,HR,34481.0,06-05-2022,Mumbai,1
13,15,Neha,26.0,Finance,47550.0,27-09-2021,Mumbai,5
15,15,Rahul,21.0,Finance,55977.0,01-08-2020,Pune,3
17,44,Amit,25.0,Sales,57969.0,31-08-2020,Chennai,3
18,5,Pooja,23.0,Finance,49144.0,20-03-2022,Mumbai,4
19,32,Priya,26.0,HR,34661.0,29-01-2020,Chennai,4
20,35,Rahul,22.0,Finance,48613.0,15-03-2022,Pune,5
22,47,Karan,24.0,Sales,49260.0,26-04-2020,Delhi,5
24,6,Priya,26.0,Sales,34947.0,19-11-2020,Delhi,2
27,37,Ravi,21.0,HR,75765.0,19-10-2021,Delhi,1
33,19,Amit,28.0,Sales,54819.0,24-08-2021,Chennai,4
34,19,Sneha,29.0,IT,59160.0,15-10-2021,Pune,5
38,24,Priya,28.0,IT,51268.0,17-02-2020,Kolkata,1
39,28,Rahul,29.0,IT,52494.0,10-02-2021,Kolkata,4
40,48,Amit,24.0,Sales,50709.0,09-01-2021,Delhi,1
44,39,Ravi,21.0,HR,74456.0,23-11-2021,Mumbai,5
45,15,Rahul,24.0,HR,36754.0,11-09-2022,Chennai,4
48,21,Amit,28.0,HR,49800.0,03-07-2021,Pune,5
49,1,Amit,26.0,IT,33524.0,28-04-2022,Chennai,4
50,4,Neha,21.0,HR,67218.0,12-08-2021,Chennai,5
55,5,Karan,24.0,Sales,39808.0,18-02-2022,Kolkata,1
57,41,Pooja,24.0,Finance,62308.0,23-08-2022,Kolkata,2
61,29,Ravi,27.0,IT,38191.0,07-02-2022,Pune,1
67,23,Ravi,26.0,IT,57759.0,12-11-2021,Kolkata,1
69,17,Ravi,29.0,HR,34772.0,01-12-2021,Kolkata,5
70,43,Rahul,21.0,Sales,66924.0,30-04-2020,Delhi,3
71,15,Neha,21.0,HR,42574.0,29-10-2021,Delhi,1
73,13,Ravi,24.0,Finance,58087.0,04-02-2022,Delhi,5
76,12,Sneha,27.0,IT,75298.0,11-01-2021,Kolkata,4
82,7,Karan,27.0,HR,57202.0,07-06-2021,Pune,2
84,44,Rahul,25.0,HR,42007.0,16-02-2022,Pune,3
85,29,Amit,26.0,IT,34313.0,11-07-2020,Pune,5
86,35,Karan,29.0,Finance,63126.0,19-04-2022,Mumbai,4
87,35,Rahul,23.0,Sales,62391.0,09-12-2021,Mumbai,4
91,10,Rahul,25.0,Sales,52292.0,21-04-2021,Delhi,4
94,43,Karan,27.0,Finance,74583.0,19-02-2022,Mumbai,1
95,27,Ravi,28.0,HR,49939.0,11-01-2021,Chennai,4
98,12,Rahul,27.0,Finance,58011.0,02-04-2022,Mumbai,4

# 🟠 LEVEL 3 – Multiple Conditions
Q8️⃣ IT department me Salary > 50000 wale employees.

In [43]:
df.loc[
    (df["Department"] == "IT") & (df["Salary"] > 50000)
]

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
23,50,Neha,39.0,IT,62722.0,03-01-2022,Kolkata,4
34,19,Sneha,29.0,IT,59160.0,15-10-2021,Pune,5
38,24,Priya,28.0,IT,51268.0,17-02-2020,Kolkata,1
39,28,Rahul,29.0,IT,52494.0,10-02-2021,Kolkata,4
52,33,Karan,34.0,IT,73498.0,01-06-2021,Chennai,1
58,9,Sneha,33.0,IT,78948.0,02-02-2022,Delhi,4
62,44,Ravi,37.0,IT,61561.0,22-05-2020,Pune,3
64,40,Rahul,38.0,IT,68535.0,10-12-2020,Pune,1
67,23,Ravi,26.0,IT,57759.0,12-11-2021,Kolkata,1
74,39,Sneha,36.0,IT,79253.0,14-02-2022,Kolkata,4
76,12,Sneha,27.0,IT,75298.0,11-01-2021,Kolkata,4

Q9️⃣ HR ya Sales department ke employees.

In [45]:
df.loc[
    (df["Department"] == "HR") | (df["Department"] == "Sales")
]

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
1,47,Ravi,29.0,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40.0,HR,71920.0,18-09-2022,Pune,1
3,36,Sneha,34.0,Sales,72905.0,15-11-2020,Delhi,4
6,5,Pooja,22.0,Sales,68706.0,25-11-2020,Pune,1
7,36,Priya,34.0,HR,62662.0,02-10-2021,Chennai,2
9,10,Priya,38.0,HR,73454.0,21-07-2022,Pune,4
11,16,Sneha,37.0,HR,79070.0,11-10-2020,Chennai,2
12,41,Amit,24.0,HR,34481.0,06-05-2022,Mumbai,1
14,4,Neha,40.0,Sales,48924.0,18-05-2021,Chennai,3
16,8,Karan,36.0,HR,36733.0,29-08-2020,Mumbai,2
17,44,Amit,25.0,Sales,57969.0,31-08-2020,Chennai,3
19,32,Priya,26.0,HR,34661.0,29-01-2020,Chennai,4
21,8,Karan,32.0,HR,37793.0,22-12-2020,Delhi,2
22,47,Karan,24.0,Sales,49260.0,26-04-2020,Delhi,5
24,6,Priya,26.0,Sales,34947.0,19-11-2020,Delhi,2
25,47,Rahul,38.0,HR,66914.0,02-05-2020,Mumbai,5
26,1,Priya,36.0,Sales,77696.0,10-09-2022,Mumbai,1
27,37,Ravi,21.0,HR,75765.0,19-10-2021,Delhi,1
28,33,Rahul,32.0,Sales,54048.0,18-09-2022,Delhi,1
29,35,Amit,34.0,Sales,51314.0,29-05-2022,Mumbai,1
31,12,Ravi,32.0,Sales,60430.0,22-01-2022,Pune,5
32,4,Sneha,32.0,Sales,55851.0,07-04-2021,Mumbai,4
33,19,Amit,28.0,Sales,54819.0,24-08-2021,Chennai,4
35,33,Rahul,40.0,Sales,53693.0,07-05-2022,Pune,3
36,3,Neha,30.0,HR,40528.0,18-03-2020,Chennai,5
40,48,Amit,24.0,Sales,50709.0,09-01-2021,Delhi,1
43,40,Rahul,32.0,HR,56007.0,03-06-2020,Pune,3
44,39,Ravi,21.0,HR,74456.0,23-11-2021,Mumbai,5
45,15,Rahul,24.0,HR,36754.0,11-09-2022,Chennai,4
46,3,Karan,30.0,HR,43817.0,01-11-2020,Pune,2
48,21,Amit,28.0,HR,49800.0,03-07-2021,Pune,5
50,4,Neha,21.0,HR,67218.0,12-08-2021,Chennai,5
53,48,Rahul,39.0,Sales,41176.0,23-03-2020,Delhi,3
54,40,Rahul,36.0,HR,34389.0,19-12-2020,Mumbai,4
55,5,Karan,24.0,Sales,39808.0,18-02-2022,Kolkata,1
60,31,Sneha,40.0,Sales,53518.0,11-04-2021,Pune,1
65,17,Priya,31.0,Sales,66960.0,29-12-2020,Delhi,1
68,9,Ravi,37.0,HR,64592.0,01-09-2020,Pune,1
69,17,Ravi,29.0,HR,34772.0,01-12-2021,Kolkata,5
70,43,Rahul,21.0,Sales,66924.0,30-04-2020,Delhi,3
71,15,Neha,21.0,HR,42574.0,29-10-2021,Delhi,1
72,23,Amit,37.0,HR,46595.0,04-12-2021,Pune,2
77,8,Ravi,37.0,HR,55883.0,15-09-2022,Mumbai,5
78,17,Amit,39.0,Sales,63053.0,28-01-2020,Delhi,1
79,16,Pooja,39.0,HR,39119.0,11-03-2020,Pune,3
80,47,Pooja,35.0,HR,55772.0,14-12-2021,Pune,5
82,7,Karan,27.0,HR,57202.0,07-06-2021,Pune,2
84,44,Rahul,25.0,HR,42007.0,16-02-2022,Pune,3
87,35,Rahul,23.0,Sales,62391.0,09-12-2021,Mumbai,4
90,6,Karan,37.0,Sales,54810.0,10-06-2022,Kolkata,3
91,10,Rahul,25.0,Sales,52292.0,21-04-2021,Delhi,4
92,3,Rahul,31.0,HR,69668.0,13-10-2020,Chennai,1
93,15,Pooja,38.0,HR,39204.0,13-04-2022,Mumbai,2
95,27,Ravi,28.0,HR,49939.0,11-01-2021,Chennai,4
96,10,Sneha,31.0,Sales,72570.0,17-01-2021,Kolkata,1
97,30,Karan,36.0,Sales,46938.0,18-12-2020,Kolkata,5

Q🔟 Salary 40000 se 70000 ke beech wale employees.

In [48]:
df.loc[df["Salary"].between(40000, 70000)]

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,22.0,Finance,50653.0,18-12-2020,Delhi,4
1,47,Ravi,29.0,HR,69988.0,18-10-2020,Mumbai,2
5,43,Rahul,23.0,Finance,65085.0,12-12-2021,Delhi,2
6,5,Pooja,22.0,Sales,68706.0,25-11-2020,Pune,1
7,36,Priya,34.0,HR,62662.0,02-10-2021,Chennai,2
...,...,...,...,...,...,...,...,...
91,10,Rahul,25.0,Sales,52292.0,21-04-2021,Delhi,4
92,3,Rahul,31.0,HR,69668.0,13-10-2020,Chennai,1
95,27,Ravi,28.0,HR,49939.0,11-01-2021,Chennai,4
97,30,Karan,36.0,Sales,46938.0,18-12-2020,Kolkata,5
98,12,Rahul,27.0,Finance,58011.0,02-04-2022,Mumbai,4

# 🔵 LEVEL 4 – Advanced Filtering
Q1️⃣ Name me letter "a" wale employees

In [49]:
df.loc[df["Name"].str.contains("a")]

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,22.0,Finance,50653.0,18-12-2020,Delhi,4
1,47,Ravi,29.0,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40.0,HR,71920.0,18-09-2022,Pune,1
3,36,Sneha,34.0,Sales,72905.0,15-11-2020,Delhi,4
4,24,Karan,27.0,IT,31899.0,28-07-2022,Kolkata,1
...,...,...,...,...,...,...,...,...
95,27,Ravi,28.0,HR,49939.0,11-01-2021,Chennai,4
96,10,Sneha,31.0,Sales,72570.0,17-01-2021,Kolkata,1
97,30,Karan,36.0,Sales,46938.0,18-12-2020,Kolkata,5
98,12,Rahul,27.0,Finance,58011.0,02-04-2022,Mumbai,4
99,27,Pooja,34.0,Finance,75038.0,23-08-2022,Chennai,2

Q2️⃣ IT department ke alawa sab employees.

In [50]:
df.loc[~(df["Department"] == "IT")]

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,22.0,Finance,50653.0,18-12-2020,Delhi,4
1,47,Ravi,29.0,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40.0,HR,71920.0,18-09-2022,Pune,1
3,36,Sneha,34.0,Sales,72905.0,15-11-2020,Delhi,4
5,43,Rahul,23.0,Finance,65085.0,12-12-2021,Delhi,2
...,...,...,...,...,...,...,...,...
95,27,Ravi,28.0,HR,49939.0,11-01-2021,Chennai,4
96,10,Sneha,31.0,Sales,72570.0,17-01-2021,Kolkata,1
97,30,Karan,36.0,Sales,46938.0,18-12-2020,Kolkata,5
98,12,Rahul,27.0,Finance,58011.0,02-04-2022,Mumbai,4
99,27,Pooja,34.0,Finance,75038.0,23-08-2022,Chennai,2

Q3️⃣ Top 5 highest salary wale employees.

Q4️⃣ Duplicate Emp_ID wale employees show karo.

# 🔴 LEVEL 5 – Real Interview Type
Q5️⃣ IT department me:
- Age > 30
- Salary > 60000
Wale employees show karo.

In [ ]:
df.loc[
    (df["Department"] == "IT") &
    (df["Age"] > 30) &
    (df["Salary"] > 60000)
]

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
23,50,Neha,39.0,IT,62722.0,03-01-2022,Kolkata,4
52,33,Karan,34.0,IT,73498.0,01-06-2021,Chennai,1
58,9,Sneha,33.0,IT,78948.0,02-02-2022,Delhi,4
62,44,Ravi,37.0,IT,61561.0,22-05-2020,Pune,3
64,40,Rahul,38.0,IT,68535.0,10-12-2020,Pune,1
74,39,Sneha,36.0,IT,79253.0,14-02-2022,Kolkata,4