In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel(r"c:\Pandas practice Data\01_Data.xlsx")
df

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,Unknown,Finance,50653.0,18-12-2020,Delhi,4
1,47,Ravi,29,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40,HR,NaN,18-09-2022,Pune,1
3,36,Sneha,34,Sales,NaN,15-11-2020,Delhi,4
4,24,Karan,27,IT,31899.0,28-07-2022,Kolkata,1
...,...,...,...,...,...,...,...,...
95,27,Ravi,28,HR,NaN,11-01-2021,Chennai,4
96,10,Sneha,Unknown,Sales,72570.0,17-01-2021,Kolkata,1
97,30,Karan,Unknown,Sales,46938.0,18-12-2020,Kolkata,5
98,12,Rahul,Unknown,Finance,NaN,02-04-2022,Mumbai,4
99,27,Pooja,Unknown,Finance,NaN,23-08-2022,Chennai,2

# Basic Data Inspection

In [3]:
df.head()

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,Unknown,Finance,50653.0,18-12-2020,Delhi,4
1,47,Ravi,29,HR,69988.0,18-10-2020,Mumbai,2
2,29,Priya,40,HR,NaN,18-09-2022,Pune,1
3,36,Sneha,34,Sales,NaN,15-11-2020,Delhi,4
4,24,Karan,27,IT,31899.0,28-07-2022,Kolkata,1

In [4]:
df.tail()

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
95,27,Ravi,28,HR,NaN,11-01-2021,Chennai,4
96,10,Sneha,Unknown,Sales,72570.0,17-01-2021,Kolkata,1
97,30,Karan,Unknown,Sales,46938.0,18-12-2020,Kolkata,5
98,12,Rahul,Unknown,Finance,NaN,02-04-2022,Mumbai,4
99,27,Pooja,Unknown,Finance,NaN,23-08-2022,Chennai,2

In [5]:
df.shape

(100, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Emp_ID             100 non-null    int64
 1   Name               100 non-null    object
 2   Age                100 non-null    object
 3   Department         100 non-null    object
 4   Salary             53 non-null     float64
 5   Joining_Date       100 non-null    object
 6   City               100 non-null    object
 7   Performance_Score  100 non-null    int64
dtypes: float64(1), int64(2), object(5)
memory usage: 6.4+ KB

In [7]:
df.describe()

           Emp_ID        Salary  Performance_Score
count  100.000000     53.000000         100.000000
mean    24.310000  56121.264151           3.000000
std     14.765299  15065.095846           1.497473
min      1.000000  31899.000000           1.000000
25%     10.000000  40528.000000           1.750000
50%     25.000000  57969.000000           3.000000
75%     36.000000  69668.000000           4.000000
max     50.000000  79253.000000           5.000000

In [8]:
df.columns

Index(['Emp_ID', 'Name', 'Age', 'Department', 'Salary', 'Joining_Date', 'City',
       'Performance_Score'],
      dtype='object')

In [9]:
df.dtypes

Emp_ID                 int64
Name                  object
Age                   object
Department            object
Salary               float64
Joining_Date          object
City                  object
Performance_Score      int64
dtype: object

# Duplicate

In [10]:
df.isnull().sum()

Emp_ID                0
Name                  0
Age                   0
Department            0
Salary               47
Joining_Date          0
City                  0
Performance_Score     0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

Convert INT

In [18]:
df["Salary"] = df["Salary"].round().astype("Int64")
df

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,38,Finance,50653,18-12-2020,Delhi,4
1,47,Ravi,29,HR,69988,18-10-2020,Mumbai,2
2,29,Priya,40,HR,32985,18-09-2022,Pune,1
3,36,Sneha,34,Sales,61239,15-11-2020,Delhi,4
4,24,Karan,27,IT,31899,28-07-2022,Kolkata,1
...,...,...,...,...,...,...,...,...
95,27,Ravi,28,HR,77768,11-01-2021,Chennai,4
96,10,Sneha,31,Sales,72570,17-01-2021,Kolkata,1
97,30,Karan,21,Sales,46938,18-12-2020,Kolkata,5
98,12,Rahul,30,Finance,54986,02-04-2022,Mumbai,4
99,27,Pooja,25,Finance,72938,23-08-2022,Chennai,2

# Fill Missing Value

In [19]:
df["Salary"] = df["Salary"].apply(
    lambda x: np.random.randint(31899, 79253) if pd.isna(x) else x
)
df

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,38,Finance,50653,18-12-2020,Delhi,4
1,47,Ravi,29,HR,69988,18-10-2020,Mumbai,2
2,29,Priya,40,HR,32985,18-09-2022,Pune,1
3,36,Sneha,34,Sales,61239,15-11-2020,Delhi,4
4,24,Karan,27,IT,31899,28-07-2022,Kolkata,1
...,...,...,...,...,...,...,...,...
95,27,Ravi,28,HR,77768,11-01-2021,Chennai,4
96,10,Sneha,31,Sales,72570,17-01-2021,Kolkata,1
97,30,Karan,21,Sales,46938,18-12-2020,Kolkata,5
98,12,Rahul,30,Finance,54986,02-04-2022,Mumbai,4
99,27,Pooja,25,Finance,72938,23-08-2022,Chennai,2

# Age Fill Missing value
- "unknown" ko NaN me convert karo

In [20]:
df["Age"] = df["Age"].replace("Unknown", np.nan)
df

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,38,Finance,50653,18-12-2020,Delhi,4
1,47,Ravi,29,HR,69988,18-10-2020,Mumbai,2
2,29,Priya,40,HR,32985,18-09-2022,Pune,1
3,36,Sneha,34,Sales,61239,15-11-2020,Delhi,4
4,24,Karan,27,IT,31899,28-07-2022,Kolkata,1
...,...,...,...,...,...,...,...,...
95,27,Ravi,28,HR,77768,11-01-2021,Chennai,4
96,10,Sneha,31,Sales,72570,17-01-2021,Kolkata,1
97,30,Karan,21,Sales,46938,18-12-2020,Kolkata,5
98,12,Rahul,30,Finance,54986,02-04-2022,Mumbai,4
99,27,Pooja,25,Finance,72938,23-08-2022,Chennai,2

# Age ko numeric type me convert karo

In [21]:
df["Age"] = pd.to_numeric(df["Age"]).astype(int)
df

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,38,Finance,50653,18-12-2020,Delhi,4
1,47,Ravi,29,HR,69988,18-10-2020,Mumbai,2
2,29,Priya,40,HR,32985,18-09-2022,Pune,1
3,36,Sneha,34,Sales,61239,15-11-2020,Delhi,4
4,24,Karan,27,IT,31899,28-07-2022,Kolkata,1
...,...,...,...,...,...,...,...,...
95,27,Ravi,28,HR,77768,11-01-2021,Chennai,4
96,10,Sneha,31,Sales,72570,17-01-2021,Kolkata,1
97,30,Karan,21,Sales,46938,18-12-2020,Kolkata,5
98,12,Rahul,30,Finance,54986,02-04-2022,Mumbai,4
99,27,Pooja,25,Finance,72938,23-08-2022,Chennai,2

# Fill Missing Value

In [22]:
df["Age"] = df["Age"].apply(
    lambda x: np.random.randint(21, 40) if pd.isna(x) else x
)
df

,Emp_ID,Name,Age,Department,Salary,Joining_Date,City,Performance_Score
0,31,Neha,38,Finance,50653,18-12-2020,Delhi,4
1,47,Ravi,29,HR,69988,18-10-2020,Mumbai,2
2,29,Priya,40,HR,32985,18-09-2022,Pune,1
3,36,Sneha,34,Sales,61239,15-11-2020,Delhi,4
4,24,Karan,27,IT,31899,28-07-2022,Kolkata,1
...,...,...,...,...,...,...,...,...
95,27,Ravi,28,HR,77768,11-01-2021,Chennai,4
96,10,Sneha,31,Sales,72570,17-01-2021,Kolkata,1
97,30,Karan,21,Sales,46938,18-12-2020,Kolkata,5
98,12,Rahul,30,Finance,54986,02-04-2022,Mumbai,4
99,27,Pooja,25,Finance,72938,23-08-2022,Chennai,2

# ⭐ Selection & Filtering

# SELECTION IN PANDAS

# ✅ A) Single Column

# ✅ B) Multiple Columns

# 2️⃣ Row Selection

# 🔹 A) loc[] (Label Based Selection)
- `df.loc[row_label , column_label]`

✅ Example 1: First 5 rows

✅ Example 2: Specific row & column

✅ Example 3: Rows 0-5 & specific columns

# 🔹 B) iloc[] (Position Based Selection)
`df.iloc[row_position , column_position]`

✅ Example 1: First 5 rows

✅ Example 2: Specific row & column

✅ Example 3: Rows & Columns

# 🔷 PART 2: FILTERING IN PANDAS
🔹 Filtering kya hota hai?
- 👉 Condition ke base par rows select karna.

# 1️⃣ Basic Filtering
✅ Salary > 50000

✅ Department == IT

# 2️⃣ Multiple Conditions

✅ AND Condition (&)

✅ OR Condition (|)

3️⃣ NOT Condition (~)

4️⃣ isin() Function

5️⃣ between()

6️⃣ String Filtering

Case insensitive:

# 📝 🔥 PRACTICE SET (Level Wise)

# 🟢 LEVEL 1 – Basic Selection
Q1️⃣ Sirf “Name” column select karo.

Q2️⃣ “Name” aur “Salary” dono columns select karo.

Q3️⃣ First 10 rows show karo.

Q4️⃣ 5th row ka “Department” value nikalo.

# 🟡 LEVEL 2 – Basic Filtering
Q5️⃣ Salary > 60000 wale employees dikhao.

Q6️⃣ Department == "IT" wale employees dikhao.

Q7️⃣ Age < 30 wale employees show karo.

# 🟠 LEVEL 3 – Multiple Conditions
Q8️⃣ IT department me Salary > 50000 wale employees.

Q9️⃣ HR ya Sales department ke employees.

Q🔟 Salary 40000 se 70000 ke beech wale employees.

# 🔵 LEVEL 4 – Advanced Filtering
Q1️⃣ Name me letter "a" wale employees

Q2️⃣ IT department ke alawa sab employees.

Q3️⃣ Top 5 highest salary wale employees.

Q4️⃣ Duplicate Emp_ID wale employees show karo.

# 🔴 LEVEL 5 – Real Interview Type
Q5️⃣ IT department me:
- Age > 30
- Salary > 60000
Wale employees show karo.