In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel(r"C:\Pandas practice Data\02_Data.xlsx")
df

    Emp_ID           Name      Age Department   Salary   Join_Date
0        1     Employee_1      NaN         it      NaN  2023-01-15
1       21     Employee_2       37         it      NaN  2023-01-15
2        3    employee_3   Unknown     SALES       NaN  15/02/2022
3        4     Employee_4  Unknown     SALES   22541.0  2023-01-15
4       16    employee_5       NaN         Hr  63615.0         NaN
5       24    employee_6       NaN         IT  32064.0  2023-01-15
6        7     Employee_7      NaN         HR      NaN         NaN
7        6     Employee_8       27         it      NaN  2023-01-15
8        9    employee_9   Unknown         it  59017.0         NaN
9       10    Employee_10       31         Hr      NaN  15/02/2022
10       1   employee_11       NaN         Hr  65769.0         NaN
11      12            NaN  Unknown         HR      NaN  15/02/2022
12      13    Employee_13  Unknown     SALES       NaN         NaN
13      14   employee_14        26         it      NaN  2023-01-15
14      15    Employee_15      NaN     SALES       NaN  15/02/2022
15      15    Employee_16  Unknown         Hr  76632.0  15/02/2022
16      17            NaN      NaN         IT      NaN  2023-01-15
17       9   employee_18        23         IT  66455.0  15/02/2022
18      19            NaN      NaN         IT  83768.0  15/02/2022
19      20            NaN       20         Hr      NaN  15/02/2022
20       4    Employee_21  Unknown         it  30321.0  15/02/2022
21      23    Employee_22      NaN         it      NaN  2023-01-15
22      23            NaN  Unknown         Hr      NaN         NaN
23      24            NaN      NaN         Hr  63211.0  2023-01-15
24      25    Employee_25      NaN         it      NaN         NaN
25      26            NaN  Unknown     SALES       NaN  15/02/2022
26      27    Employee_27      NaN    Finance      NaN  2023-01-15
27      28   employee_28       NaN         Hr      NaN         NaN
28      25            NaN       31         IT  79206.0         NaN
29      17            NaN       27    Finance      NaN         NaN
30      11            NaN  Unknown         HR      NaN  2023-01-15
31       5            NaN       22     SALES       NaN         NaN
32      15            NaN      NaN    Finance      NaN  15/02/2022
33      34            NaN      NaN         Hr      NaN         NaN
34      35   employee_35       NaN     SALES       NaN         NaN
35      19            NaN  Unknown     SALES   46735.0  15/02/2022
36       6            NaN  Unknown      Sales      NaN         NaN
37      38    Employee_38  Unknown         it  33953.0  15/02/2022
38       5   employee_39   Unknown    Finance  67422.0  15/02/2022
39      40            NaN      NaN    Finance      NaN  15/02/2022
40      41   employee_41   Unknown         it      NaN  15/02/2022
41      42   employee_42       NaN      Sales  63892.0  15/02/2022
42       3    Employee_43  Unknown         IT      NaN  15/02/2022
43      44   employee_44        50    Finance      NaN  15/02/2022
44      45   employee_45       NaN     SALES       NaN  15/02/2022
45       4   employee_46   Unknown         IT      NaN  15/02/2022
46      47   employee_47   Unknown         Hr      NaN  2023-01-15
47      48   employee_48        44         Hr      NaN  15/02/2022
48       4    Employee_49      NaN     SALES       NaN         NaN
49      50   employee_50        22         HR      NaN  2023-01-15

In [3]:
df.head()

   Emp_ID          Name      Age Department   Salary   Join_Date
0       1    Employee_1      NaN         it      NaN  2023-01-15
1      21    Employee_2       37         it      NaN  2023-01-15
2       3   employee_3   Unknown     SALES       NaN  15/02/2022
3       4    Employee_4  Unknown     SALES   22541.0  2023-01-15
4      16   employee_5       NaN         Hr  63615.0         NaN

In [4]:
df.shape

(50, 6)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_ID      50 non-null     int64
 1   Name        34 non-null     object
 2   Age         30 non-null     object
 3   Department  50 non-null     object
 4   Salary      15 non-null     float64
 5   Join_Date   35 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 2.5+ KB

In [6]:
df.describe()

          Emp_ID        Salary
count  50.000000     15.000000
mean   19.880000  56973.400000
std    14.250872  19200.782149
min     1.000000  22541.000000
25%     7.500000  40344.000000
50%    17.000000  63615.000000
75%    26.750000  66938.500000
max    50.000000  83768.000000

In [7]:
df.duplicated().value_counts()

False    50
Name: count, dtype: int64

In [8]:
df.isnull().sum()

Emp_ID         0
Name          16
Age           20
Department     0
Salary        35
Join_Date     15
dtype: int64

In [9]:
df.drop_duplicates("Emp_ID")

    Emp_ID           Name      Age Department   Salary   Join_Date
0        1     Employee_1      NaN         it      NaN  2023-01-15
1       21     Employee_2       37         it      NaN  2023-01-15
2        3    employee_3   Unknown     SALES       NaN  15/02/2022
3        4     Employee_4  Unknown     SALES   22541.0  2023-01-15
4       16    employee_5       NaN         Hr  63615.0         NaN
5       24    employee_6       NaN         IT  32064.0  2023-01-15
6        7     Employee_7      NaN         HR      NaN         NaN
7        6     Employee_8       27         it      NaN  2023-01-15
8        9    employee_9   Unknown         it  59017.0         NaN
9       10    Employee_10       31         Hr      NaN  15/02/2022
11      12            NaN  Unknown         HR      NaN  15/02/2022
12      13    Employee_13  Unknown     SALES       NaN         NaN
13      14   employee_14        26         it      NaN  2023-01-15
14      15    Employee_15      NaN     SALES       NaN  15/02/2022
16      17            NaN      NaN         IT      NaN  2023-01-15
18      19            NaN      NaN         IT  83768.0  15/02/2022
19      20            NaN       20         Hr      NaN  15/02/2022
21      23    Employee_22      NaN         it      NaN  2023-01-15
24      25    Employee_25      NaN         it      NaN         NaN
25      26            NaN  Unknown     SALES       NaN  15/02/2022
26      27    Employee_27      NaN    Finance      NaN  2023-01-15
27      28   employee_28       NaN         Hr      NaN         NaN
30      11            NaN  Unknown         HR      NaN  2023-01-15
31       5            NaN       22     SALES       NaN         NaN
33      34            NaN      NaN         Hr      NaN         NaN
34      35   employee_35       NaN     SALES       NaN         NaN
37      38    Employee_38  Unknown         it  33953.0  15/02/2022
39      40            NaN      NaN    Finance      NaN  15/02/2022
40      41   employee_41   Unknown         it      NaN  15/02/2022
41      42   employee_42       NaN      Sales  63892.0  15/02/2022
43      44   employee_44        50    Finance      NaN  15/02/2022
44      45   employee_45       NaN     SALES       NaN  15/02/2022
46      47   employee_47   Unknown         Hr      NaN  2023-01-15
47      48   employee_48        44         Hr      NaN  15/02/2022
49      50   employee_50        22         HR      NaN  2023-01-15

Handle missing value
- Age

In [10]:
df["Age"] = df["Age"].replace("Unknown", np.nan)

C:\Users\Anish Kumar\AppData\Local\Temp\ipykernel_17616\3265307568.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Age"] = df["Age"].replace("Unknown", np.nan)

In [11]:
df["Age"] = pd.to_numeric(df["Age"])

In [12]:
df["Age"] = df["Age"].apply(
    lambda x: np.random.randint(20, 50) if pd.isna(x) else x
)
df

    Emp_ID           Name   Age Department   Salary   Join_Date
0        1     Employee_1  28.0         it      NaN  2023-01-15
1       21     Employee_2  37.0         it      NaN  2023-01-15
2        3    employee_3   49.0     SALES       NaN  15/02/2022
3        4     Employee_4  20.0     SALES   22541.0  2023-01-15
4       16    employee_5   42.0         Hr  63615.0         NaN
5       24    employee_6   28.0         IT  32064.0  2023-01-15
6        7     Employee_7  27.0         HR      NaN         NaN
7        6     Employee_8  27.0         it      NaN  2023-01-15
8        9    employee_9   24.0         it  59017.0         NaN
9       10    Employee_10  31.0         Hr      NaN  15/02/2022
10       1   employee_11   44.0         Hr  65769.0         NaN
11      12            NaN  33.0         HR      NaN  15/02/2022
12      13    Employee_13  28.0     SALES       NaN         NaN
13      14   employee_14   26.0         it      NaN  2023-01-15
14      15    Employee_15  39.0     SALES       NaN  15/02/2022
15      15    Employee_16  35.0         Hr  76632.0  15/02/2022
16      17            NaN  25.0         IT      NaN  2023-01-15
17       9   employee_18   23.0         IT  66455.0  15/02/2022
18      19            NaN  46.0         IT  83768.0  15/02/2022
19      20            NaN  20.0         Hr      NaN  15/02/2022
20       4    Employee_21  39.0         it  30321.0  15/02/2022
21      23    Employee_22  36.0         it      NaN  2023-01-15
22      23            NaN  42.0         Hr      NaN         NaN
23      24            NaN  30.0         Hr  63211.0  2023-01-15
24      25    Employee_25  46.0         it      NaN         NaN
25      26            NaN  25.0     SALES       NaN  15/02/2022
26      27    Employee_27  26.0    Finance      NaN  2023-01-15
27      28   employee_28   26.0         Hr      NaN         NaN
28      25            NaN  31.0         IT  79206.0         NaN
29      17            NaN  27.0    Finance      NaN         NaN
30      11            NaN  37.0         HR      NaN  2023-01-15
31       5            NaN  22.0     SALES       NaN         NaN
32      15            NaN  46.0    Finance      NaN  15/02/2022
33      34            NaN  33.0         Hr      NaN         NaN
34      35   employee_35   28.0     SALES       NaN         NaN
35      19            NaN  33.0     SALES   46735.0  15/02/2022
36       6            NaN  26.0      Sales      NaN         NaN
37      38    Employee_38  42.0         it  33953.0  15/02/2022
38       5   employee_39   41.0    Finance  67422.0  15/02/2022
39      40            NaN  33.0    Finance      NaN  15/02/2022
40      41   employee_41   47.0         it      NaN  15/02/2022
41      42   employee_42   37.0      Sales  63892.0  15/02/2022
42       3    Employee_43  33.0         IT      NaN  15/02/2022
43      44   employee_44   50.0    Finance      NaN  15/02/2022
44      45   employee_45   39.0     SALES       NaN  15/02/2022
45       4   employee_46   35.0         IT      NaN  15/02/2022
46      47   employee_47   39.0         Hr      NaN  2023-01-15
47      48   employee_48   44.0         Hr      NaN  15/02/2022
48       4    Employee_49  49.0     SALES       NaN         NaN
49      50   employee_50   22.0         HR      NaN  2023-01-15

In [13]:
df["Age"] = df["Age"].astype(int)
df

    Emp_ID           Name  Age Department   Salary   Join_Date
0        1     Employee_1   28         it      NaN  2023-01-15
1       21     Employee_2   37         it      NaN  2023-01-15
2        3    employee_3    49     SALES       NaN  15/02/2022
3        4     Employee_4   20     SALES   22541.0  2023-01-15
4       16    employee_5    42         Hr  63615.0         NaN
5       24    employee_6    28         IT  32064.0  2023-01-15
6        7     Employee_7   27         HR      NaN         NaN
7        6     Employee_8   27         it      NaN  2023-01-15
8        9    employee_9    24         it  59017.0         NaN
9       10    Employee_10   31         Hr      NaN  15/02/2022
10       1   employee_11    44         Hr  65769.0         NaN
11      12            NaN   33         HR      NaN  15/02/2022
12      13    Employee_13   28     SALES       NaN         NaN
13      14   employee_14    26         it      NaN  2023-01-15
14      15    Employee_15   39     SALES       NaN  15/02/2022
15      15    Employee_16   35         Hr  76632.0  15/02/2022
16      17            NaN   25         IT      NaN  2023-01-15
17       9   employee_18    23         IT  66455.0  15/02/2022
18      19            NaN   46         IT  83768.0  15/02/2022
19      20            NaN   20         Hr      NaN  15/02/2022
20       4    Employee_21   39         it  30321.0  15/02/2022
21      23    Employee_22   36         it      NaN  2023-01-15
22      23            NaN   42         Hr      NaN         NaN
23      24            NaN   30         Hr  63211.0  2023-01-15
24      25    Employee_25   46         it      NaN         NaN
25      26            NaN   25     SALES       NaN  15/02/2022
26      27    Employee_27   26    Finance      NaN  2023-01-15
27      28   employee_28    26         Hr      NaN         NaN
28      25            NaN   31         IT  79206.0         NaN
29      17            NaN   27    Finance      NaN         NaN
30      11            NaN   37         HR      NaN  2023-01-15
31       5            NaN   22     SALES       NaN         NaN
32      15            NaN   46    Finance      NaN  15/02/2022
33      34            NaN   33         Hr      NaN         NaN
34      35   employee_35    28     SALES       NaN         NaN
35      19            NaN   33     SALES   46735.0  15/02/2022
36       6            NaN   26      Sales      NaN         NaN
37      38    Employee_38   42         it  33953.0  15/02/2022
38       5   employee_39    41    Finance  67422.0  15/02/2022
39      40            NaN   33    Finance      NaN  15/02/2022
40      41   employee_41    47         it      NaN  15/02/2022
41      42   employee_42    37      Sales  63892.0  15/02/2022
42       3    Employee_43   33         IT      NaN  15/02/2022
43      44   employee_44    50    Finance      NaN  15/02/2022
44      45   employee_45    39     SALES       NaN  15/02/2022
45       4   employee_46    35         IT      NaN  15/02/2022
46      47   employee_47    39         Hr      NaN  2023-01-15
47      48   employee_48    44         Hr      NaN  15/02/2022
48       4    Employee_49   49     SALES       NaN         NaN
49      50   employee_50    22         HR      NaN  2023-01-15

In [14]:
df["Department"] = df["Department"].replace({
    "it": "IT",
    "Hr": "HR"
})

Salary

In [15]:
df["Salary"] = df["Salary"].apply(
    lambda x : np.random.randint(22541, 83768) if pd.isna(x) else x
)
df

    Emp_ID           Name  Age Department   Salary   Join_Date
0        1     Employee_1   28         IT  67716.0  2023-01-15
1       21     Employee_2   37         IT  67158.0  2023-01-15
2        3    employee_3    49     SALES   42453.0  15/02/2022
3        4     Employee_4   20     SALES   22541.0  2023-01-15
4       16    employee_5    42         HR  63615.0         NaN
5       24    employee_6    28         IT  32064.0  2023-01-15
6        7     Employee_7   27         HR  47370.0         NaN
7        6     Employee_8   27         IT  83566.0  2023-01-15
8        9    employee_9    24         IT  59017.0         NaN
9       10    Employee_10   31         HR  59618.0  15/02/2022
10       1   employee_11    44         HR  65769.0         NaN
11      12            NaN   33         HR  59252.0  15/02/2022
12      13    Employee_13   28     SALES   82643.0         NaN
13      14   employee_14    26         IT  52450.0  2023-01-15
14      15    Employee_15   39     SALES   61906.0  15/02/2022
15      15    Employee_16   35         HR  76632.0  15/02/2022
16      17            NaN   25         IT  50227.0  2023-01-15
17       9   employee_18    23         IT  66455.0  15/02/2022
18      19            NaN   46         IT  83768.0  15/02/2022
19      20            NaN   20         HR  55936.0  15/02/2022
20       4    Employee_21   39         IT  30321.0  15/02/2022
21      23    Employee_22   36         IT  24464.0  2023-01-15
22      23            NaN   42         HR  68982.0         NaN
23      24            NaN   30         HR  63211.0  2023-01-15
24      25    Employee_25   46         IT  33199.0         NaN
25      26            NaN   25     SALES   53377.0  15/02/2022
26      27    Employee_27   26    Finance  76866.0  2023-01-15
27      28   employee_28    26         HR  56515.0         NaN
28      25            NaN   31         IT  79206.0         NaN
29      17            NaN   27    Finance  67135.0         NaN
30      11            NaN   37         HR  75221.0  2023-01-15
31       5            NaN   22     SALES   41726.0         NaN
32      15            NaN   46    Finance  42898.0  15/02/2022
33      34            NaN   33         HR  67740.0         NaN
34      35   employee_35    28     SALES   78736.0         NaN
35      19            NaN   33     SALES   46735.0  15/02/2022
36       6            NaN   26      Sales  41808.0         NaN
37      38    Employee_38   42         IT  33953.0  15/02/2022
38       5   employee_39    41    Finance  67422.0  15/02/2022
39      40            NaN   33    Finance  48730.0  15/02/2022
40      41   employee_41    47         IT  69804.0  15/02/2022
41      42   employee_42    37      Sales  63892.0  15/02/2022
42       3    Employee_43   33         IT  55358.0  15/02/2022
43      44   employee_44    50    Finance  29720.0  15/02/2022
44      45   employee_45    39     SALES   61780.0  15/02/2022
45       4   employee_46    35         IT  59299.0  15/02/2022
46      47   employee_47    39         HR  24715.0  2023-01-15
47      48   employee_48    44         HR  25920.0  15/02/2022
48       4    Employee_49   49     SALES   81581.0         NaN
49      50   employee_50    22         HR  32905.0  2023-01-15

In [16]:
df["Salary"] = df['Salary'].astype(int)
df

    Emp_ID           Name  Age Department  Salary   Join_Date
0        1     Employee_1   28         IT   67716  2023-01-15
1       21     Employee_2   37         IT   67158  2023-01-15
2        3    employee_3    49     SALES    42453  15/02/2022
3        4     Employee_4   20     SALES    22541  2023-01-15
4       16    employee_5    42         HR   63615         NaN
5       24    employee_6    28         IT   32064  2023-01-15
6        7     Employee_7   27         HR   47370         NaN
7        6     Employee_8   27         IT   83566  2023-01-15
8        9    employee_9    24         IT   59017         NaN
9       10    Employee_10   31         HR   59618  15/02/2022
10       1   employee_11    44         HR   65769         NaN
11      12            NaN   33         HR   59252  15/02/2022
12      13    Employee_13   28     SALES    82643         NaN
13      14   employee_14    26         IT   52450  2023-01-15
14      15    Employee_15   39     SALES    61906  15/02/2022
15      15    Employee_16   35         HR   76632  15/02/2022
16      17            NaN   25         IT   50227  2023-01-15
17       9   employee_18    23         IT   66455  15/02/2022
18      19            NaN   46         IT   83768  15/02/2022
19      20            NaN   20         HR   55936  15/02/2022
20       4    Employee_21   39         IT   30321  15/02/2022
21      23    Employee_22   36         IT   24464  2023-01-15
22      23            NaN   42         HR   68982         NaN
23      24            NaN   30         HR   63211  2023-01-15
24      25    Employee_25   46         IT   33199         NaN
25      26            NaN   25     SALES    53377  15/02/2022
26      27    Employee_27   26    Finance   76866  2023-01-15
27      28   employee_28    26         HR   56515         NaN
28      25            NaN   31         IT   79206         NaN
29      17            NaN   27    Finance   67135         NaN
30      11            NaN   37         HR   75221  2023-01-15
31       5            NaN   22     SALES    41726         NaN
32      15            NaN   46    Finance   42898  15/02/2022
33      34            NaN   33         HR   67740         NaN
34      35   employee_35    28     SALES    78736         NaN
35      19            NaN   33     SALES    46735  15/02/2022
36       6            NaN   26      Sales   41808         NaN
37      38    Employee_38   42         IT   33953  15/02/2022
38       5   employee_39    41    Finance   67422  15/02/2022
39      40            NaN   33    Finance   48730  15/02/2022
40      41   employee_41    47         IT   69804  15/02/2022
41      42   employee_42    37      Sales   63892  15/02/2022
42       3    Employee_43   33         IT   55358  15/02/2022
43      44   employee_44    50    Finance   29720  15/02/2022
44      45   employee_45    39     SALES    61780  15/02/2022
45       4   employee_46    35         IT   59299  15/02/2022
46      47   employee_47    39         HR   24715  2023-01-15
47      48   employee_48    44         HR   25920  15/02/2022
48       4    Employee_49   49     SALES    81581         NaN
49      50   employee_50    22         HR   32905  2023-01-15

✅ Step 1: Check Column

In [33]:
df["Join_Date"].unique()
df

    Emp_ID           Name  Age Department  Salary   Join_Date
0        1     Employee_1   28         IT   67716  2023-01-15
1       21     Employee_2   37         IT   67158  2023-01-15
2        3    employee_3    49     SALES    42453  2023-01-01
3        4     Employee_4   20     SALES    22541  2023-01-15
4       16    employee_5    42         HR   63615  2023-01-01
5       24    employee_6    28         IT   32064  2023-01-15
6        7     Employee_7   27         HR   47370  2023-01-01
7        6     Employee_8   27         IT   83566  2023-01-15
8        9    employee_9    24         IT   59017  2023-01-01
9       10    Employee_10   31         HR   59618  2023-01-01
10       1   employee_11    44         HR   65769  2023-01-01
11      12            NaN   33         HR   59252  2023-01-01
12      13    Employee_13   28     SALES    82643  2023-01-01
13      14   employee_14    26         IT   52450  2023-01-15
14      15    Employee_15   39     SALES    61906  2023-01-01
15      15    Employee_16   35         HR   76632  2023-01-01
16      17            NaN   25         IT   50227  2023-01-15
17       9   employee_18    23         IT   66455  2023-01-01
18      19            NaN   46         IT   83768  2023-01-01
19      20            NaN   20         HR   55936  2023-01-01
20       4    Employee_21   39         IT   30321  2023-01-01
21      23    Employee_22   36         IT   24464  2023-01-15
22      23            NaN   42         HR   68982  2023-01-01
23      24            NaN   30         HR   63211  2023-01-15
24      25    Employee_25   46         IT   33199  2023-01-01
25      26            NaN   25     SALES    53377  2023-01-01
26      27    Employee_27   26    Finance   76866  2023-01-15
27      28   employee_28    26         HR   56515  2023-01-01
28      25            NaN   31         IT   79206  2023-01-01
29      17            NaN   27    Finance   67135  2023-01-01
30      11            NaN   37         HR   75221  2023-01-15
31       5            NaN   22     SALES    41726  2023-01-01
32      15            NaN   46    Finance   42898  2023-01-01
33      34            NaN   33         HR   67740  2023-01-01
34      35   employee_35    28     SALES    78736  2023-01-01
35      19            NaN   33     SALES    46735  2023-01-01
36       6            NaN   26      Sales   41808  2023-01-01
37      38    Employee_38   42         IT   33953  2023-01-01
38       5   employee_39    41    Finance   67422  2023-01-01
39      40            NaN   33    Finance   48730  2023-01-01
40      41   employee_41    47         IT   69804  2023-01-01
41      42   employee_42    37      Sales   63892  2023-01-01
42       3    Employee_43   33         IT   55358  2023-01-01
43      44   employee_44    50    Finance   29720  2023-01-01
44      45   employee_45    39     SALES    61780  2023-01-01
45       4   employee_46    35         IT   59299  2023-01-01
46      47   employee_47    39         HR   24715  2023-01-15
47      48   employee_48    44         HR   25920  2023-01-01
48       4    Employee_49   49     SALES    81581  2023-01-01
49      50   employee_50    22         HR   32905  2023-01-15

✅ Step 2: "Missing value" ko NaN me convert karo

In [20]:
df["Join_Date"] = df["Join_Date"].replace("Missing value", np.nan)

✅ Step 3: Convert to Proper Datetime

In [32]:
df["Join_Date"] = pd.to_datetime(
    df["Join_Date"],
    errors="coerce",
    dayfirst=True
)

df["Join_Date"] = df["Join_Date"].dt.date
df

    Emp_ID           Name  Age Department  Salary   Join_Date
0        1     Employee_1   28         IT   67716  2023-01-15
1       21     Employee_2   37         IT   67158  2023-01-15
2        3    employee_3    49     SALES    42453  2023-01-01
3        4     Employee_4   20     SALES    22541  2023-01-15
4       16    employee_5    42         HR   63615  2023-01-01
5       24    employee_6    28         IT   32064  2023-01-15
6        7     Employee_7   27         HR   47370  2023-01-01
7        6     Employee_8   27         IT   83566  2023-01-15
8        9    employee_9    24         IT   59017  2023-01-01
9       10    Employee_10   31         HR   59618  2023-01-01
10       1   employee_11    44         HR   65769  2023-01-01
11      12            NaN   33         HR   59252  2023-01-01
12      13    Employee_13   28     SALES    82643  2023-01-01
13      14   employee_14    26         IT   52450  2023-01-15
14      15    Employee_15   39     SALES    61906  2023-01-01
15      15    Employee_16   35         HR   76632  2023-01-01
16      17            NaN   25         IT   50227  2023-01-15
17       9   employee_18    23         IT   66455  2023-01-01
18      19            NaN   46         IT   83768  2023-01-01
19      20            NaN   20         HR   55936  2023-01-01
20       4    Employee_21   39         IT   30321  2023-01-01
21      23    Employee_22   36         IT   24464  2023-01-15
22      23            NaN   42         HR   68982  2023-01-01
23      24            NaN   30         HR   63211  2023-01-15
24      25    Employee_25   46         IT   33199  2023-01-01
25      26            NaN   25     SALES    53377  2023-01-01
26      27    Employee_27   26    Finance   76866  2023-01-15
27      28   employee_28    26         HR   56515  2023-01-01
28      25            NaN   31         IT   79206  2023-01-01
29      17            NaN   27    Finance   67135  2023-01-01
30      11            NaN   37         HR   75221  2023-01-15
31       5            NaN   22     SALES    41726  2023-01-01
32      15            NaN   46    Finance   42898  2023-01-01
33      34            NaN   33         HR   67740  2023-01-01
34      35   employee_35    28     SALES    78736  2023-01-01
35      19            NaN   33     SALES    46735  2023-01-01
36       6            NaN   26      Sales   41808  2023-01-01
37      38    Employee_38   42         IT   33953  2023-01-01
38       5   employee_39    41    Finance   67422  2023-01-01
39      40            NaN   33    Finance   48730  2023-01-01
40      41   employee_41    47         IT   69804  2023-01-01
41      42   employee_42    37      Sales   63892  2023-01-01
42       3    Employee_43   33         IT   55358  2023-01-01
43      44   employee_44    50    Finance   29720  2023-01-01
44      45   employee_45    39     SALES    61780  2023-01-01
45       4   employee_46    35         IT   59299  2023-01-01
46      47   employee_47    39         HR   24715  2023-01-15
47      48   employee_48    44         HR   25920  2023-01-01
48       4    Employee_49   49     SALES    81581  2023-01-01
49      50   employee_50    22         HR   32905  2023-01-15

In [30]:
df.describe()

          Emp_ID        Age        Salary
count  50.000000  50.000000     50.000000
mean   19.880000  33.920000  56067.500000
std    14.250872   8.487301  17595.161872
min     1.000000  20.000000  22541.000000
25%     7.500000  27.000000  42564.250000
50%    17.000000  33.000000  59275.500000
75%    26.750000  40.500000  67642.500000
max    50.000000  50.000000  83768.000000