In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import

In [2]:
data = {
    "Emp_ID": range(1, 51),
    "Name": [f"Employee_{i}" for i in range(1, 51)],
    "Age": np.random.randint(20, 50, 50),
    "Department": np.random.choice(["IT", "HR", "Sales", "Finance"], 50),
    "Salary": np.random.randint(20000, 100000, 50),
    "Experience_Years": np.random.randint(1, 20, 50)
}
df = pd.DataFrame(data)

In [3]:
df.head()

   Emp_ID        Name  Age Department  Salary  Experience_Years
0       1  Employee_1   32         IT   28186                18
1       2  Employee_2   32         IT   59330                 3
2       3  Employee_3   26         HR   63153                12
3       4  Employee_4   34    Finance   75784                 9
4       5  Employee_5   36      Sales   52779                 5

In [4]:
df

    Emp_ID         Name  Age Department  Salary  Experience_Years
0        1   Employee_1   32         IT   28186                18
1        2   Employee_2   32         IT   59330                 3
2        3   Employee_3   26         HR   63153                12
3        4   Employee_4   34    Finance   75784                 9
4        5   Employee_5   36      Sales   52779                 5
5        6   Employee_6   36         IT   95987                 9
6        7   Employee_7   42    Finance   74972                 7
7        8   Employee_8   46         IT   89446                12
8        9   Employee_9   38      Sales   32267                 3
9       10  Employee_10   46      Sales   53265                 4
10      11  Employee_11   29      Sales   74552                 7
11      12  Employee_12   26    Finance   67911                 2
12      13  Employee_13   30         HR   65147                17
13      14  Employee_14   27         IT   87922                16
14      15  Employee_15   20      Sales   73118                11
15      16  Employee_16   21    Finance   22807                14
16      17  Employee_17   44    Finance   82560                16
17      18  Employee_18   21      Sales   26730                16
18      19  Employee_19   44         IT   85959                 2
19      20  Employee_20   20      Sales   27209                 8
20      21  Employee_21   38      Sales   97917                14
21      22  Employee_22   45      Sales   59121                 5
22      23  Employee_23   25    Finance   72176                11
23      24  Employee_24   41      Sales   54823                 3
24      25  Employee_25   28    Finance   34625                 9
25      26  Employee_26   34         IT   22831                12
26      27  Employee_27   23         IT   62760                 5
27      28  Employee_28   37         HR   26300                 7
28      29  Employee_29   37         HR   34435                15
29      30  Employee_30   35      Sales   62682                 1
30      31  Employee_31   27    Finance   95829                10
31      32  Employee_32   23         IT   43127                18
32      33  Employee_33   20         HR   67486                 5
33      34  Employee_34   36         HR   65540                 3
34      35  Employee_35   31      Sales   38120                 6
35      36  Employee_36   28      Sales   57203                18
36      37  Employee_37   40         IT   46398                 8
37      38  Employee_38   39         HR   49928                10
38      39  Employee_39   30         HR   69635                 4
39      40  Employee_40   38         IT   50928                12
40      41  Employee_41   33      Sales   40536                11
41      42  Employee_42   22      Sales   27967                16
42      43  Employee_43   42         HR   28240                 3
43      44  Employee_44   39      Sales   76389                17
44      45  Employee_45   42    Finance   35684                19
45      46  Employee_46   48      Sales   91690                12
46      47  Employee_47   23         IT   77773                 4
47      48  Employee_48   20    Finance   74886                 5
48      49  Employee_49   23         IT   95279                14
49      50  Employee_50   28    Finance   50753                14

In [5]:
df.shape

(50, 6)

In [6]:
df.duplicated().sum()

np.int64(0)

In [9]:
df["Bonus"] = df["Salary"] * 10
df

    Emp_ID         Name  Age Department  Salary  Experience_Years   Bonus
0        1   Employee_1   32         IT   28186                18  281860
1        2   Employee_2   32         IT   59330                 3  593300
2        3   Employee_3   26         HR   63153                12  631530
3        4   Employee_4   34    Finance   75784                 9  757840
4        5   Employee_5   36      Sales   52779                 5  527790
5        6   Employee_6   36         IT   95987                 9  959870
6        7   Employee_7   42    Finance   74972                 7  749720
7        8   Employee_8   46         IT   89446                12  894460
8        9   Employee_9   38      Sales   32267                 3  322670
9       10  Employee_10   46      Sales   53265                 4  532650
10      11  Employee_11   29      Sales   74552                 7  745520
11      12  Employee_12   26    Finance   67911                 2  679110
12      13  Employee_13   30         HR   65147                17  651470
13      14  Employee_14   27         IT   87922                16  879220
14      15  Employee_15   20      Sales   73118                11  731180
15      16  Employee_16   21    Finance   22807                14  228070
16      17  Employee_17   44    Finance   82560                16  825600
17      18  Employee_18   21      Sales   26730                16  267300
18      19  Employee_19   44         IT   85959                 2  859590
19      20  Employee_20   20      Sales   27209                 8  272090
20      21  Employee_21   38      Sales   97917                14  979170
21      22  Employee_22   45      Sales   59121                 5  591210
22      23  Employee_23   25    Finance   72176                11  721760
23      24  Employee_24   41      Sales   54823                 3  548230
24      25  Employee_25   28    Finance   34625                 9  346250
25      26  Employee_26   34         IT   22831                12  228310
26      27  Employee_27   23         IT   62760                 5  627600
27      28  Employee_28   37         HR   26300                 7  263000
28      29  Employee_29   37         HR   34435                15  344350
29      30  Employee_30   35      Sales   62682                 1  626820
30      31  Employee_31   27    Finance   95829                10  958290
31      32  Employee_32   23         IT   43127                18  431270
32      33  Employee_33   20         HR   67486                 5  674860
33      34  Employee_34   36         HR   65540                 3  655400
34      35  Employee_35   31      Sales   38120                 6  381200
35      36  Employee_36   28      Sales   57203                18  572030
36      37  Employee_37   40         IT   46398                 8  463980
37      38  Employee_38   39         HR   49928                10  499280
38      39  Employee_39   30         HR   69635                 4  696350
39      40  Employee_40   38         IT   50928                12  509280
40      41  Employee_41   33      Sales   40536                11  405360
41      42  Employee_42   22      Sales   27967                16  279670
42      43  Employee_43   42         HR   28240                 3  282400
43      44  Employee_44   39      Sales   76389                17  763890
44      45  Employee_45   42    Finance   35684                19  356840
45      46  Employee_46   48      Sales   91690                12  916900
46      47  Employee_47   23         IT   77773                 4  777730
47      48  Employee_48   20    Finance   74886                 5  748860
48      49  Employee_49   23         IT   95279                14  952790
49      50  Employee_50   28    Finance   50753                14  507530

In [10]:
df["Total_Income"] = df["Salary"] + df["Bonus"]
df.head(5)

,Emp_ID,Name,Age,Department,Salary,Experience_Years,Bonus,Total_Income
0,1,Employee_1,32,IT,28186,18,281860,310046
1,2,Employee_2,32,IT,59330,3,593300,652630
2,3,Employee_3,26,HR,63153,12,631530,694683
3,4,Employee_4,34,Finance,75784,9,757840,833624
4,5,Employee_5,36,Sales,52779,5,527790,580569

In [12]:
df["Salary_Category"] = np.where(
    df["Salary"] > 60000,
    "High",
    "Low"
)
df.head(5)

,Emp_ID,Name,Age,Department,Salary,Experience_Years,Bonus,Total_Income,Salary_Category
0,1,Employee_1,32,IT,28186,18,281860,310046,Low
1,2,Employee_2,32,IT,59330,3,593300,652630,Low
2,3,Employee_3,26,HR,63153,12,631530,694683,High
3,4,Employee_4,34,Finance,75784,9,757840,833624,High
4,5,Employee_5,36,Sales,52779,5,527790,580569,Low

🔹 4️⃣ Experience Level (apply + lambda)

In [14]:
df["Level"] = df["Experience_Years"].apply(
    lambda x: "Senior" if x > 10 else "Junior"
)
df.head()

,Emp_ID,Name,Age,Department,Salary,Experience_Years,Bonus,Total_Income,Salary_Category,Level
0,1,Employee_1,32,IT,28186,18,281860,310046,Low,Senior
1,2,Employee_2,32,IT,59330,3,593300,652630,Low,Junior
2,3,Employee_3,26,HR,63153,12,631530,694683,High,Senior
3,4,Employee_4,34,Finance,75784,9,757840,833624,High,Junior
4,5,Employee_5,36,Sales,52779,5,527790,580569,Low,Junior

In [16]:
df["Age_Group"] = df["Age"].apply(
    lambda x: "Young" if x < 30 else "Adult"
)
df

,Emp_ID,Name,Age,Department,Salary,Experience_Years,Bonus,Total_Income,Salary_Category,Level,Age_Group
0,1,Employee_1,32,IT,28186,18,281860,310046,Low,Senior,Adult
1,2,Employee_2,32,IT,59330,3,593300,652630,Low,Junior,Adult
2,3,Employee_3,26,HR,63153,12,631530,694683,High,Senior,Young
3,4,Employee_4,34,Finance,75784,9,757840,833624,High,Junior,Adult
4,5,Employee_5,36,Sales,52779,5,527790,580569,Low,Junior,Adult
5,6,Employee_6,36,IT,95987,9,959870,1055857,High,Junior,Adult
6,7,Employee_7,42,Finance,74972,7,749720,824692,High,Junior,Adult
7,8,Employee_8,46,IT,89446,12,894460,983906,High,Senior,Adult
8,9,Employee_9,38,Sales,32267,3,322670,354937,Low,Junior,Adult
9,10,Employee_10,46,Sales,53265,4,532650,585915,Low,Junior,Adult
10,11,Employee_11,29,Sales,74552,7,745520,820072,High,Junior,Young
11,12,Employee_12,26,Finance,67911,2,679110,747021,High,Junior,Young
12,13,Employee_13,30,HR,65147,17,651470,716617,High,Senior,Adult
13,14,Employee_14,27,IT,87922,16,879220,967142,High,Senior,Young
14,15,Employee_15,20,Sales,73118,11,731180,804298,High,Senior,Young
15,16,Employee_16,21,Finance,22807,14,228070,250877,Low,Senior,Young
16,17,Employee_17,44,Finance,82560,16,825600,908160,High,Senior,Adult
17,18,Employee_18,21,Sales,26730,16,267300,294030,Low,Senior,Young
18,19,Employee_19,44,IT,85959,2,859590,945549,High,Junior,Adult
19,20,Employee_20,20,Sales,27209,8,272090,299299,Low,Junior,Young
20,21,Employee_21,38,Sales,97917,14,979170,1077087,High,Senior,Adult
21,22,Employee_22,45,Sales,59121,5,591210,650331,Low,Junior,Adult
22,23,Employee_23,25,Finance,72176,11,721760,793936,High,Senior,Young
23,24,Employee_24,41,Sales,54823,3,548230,603053,Low,Junior,Adult
24,25,Employee_25,28,Finance,34625,9,346250,380875,Low,Junior,Young
25,26,Employee_26,34,IT,22831,12,228310,251141,Low,Senior,Adult
26,27,Employee_27,23,IT,62760,5,627600,690360,High,Junior,Young
27,28,Employee_28,37,HR,26300,7,263000,289300,Low,Junior,Adult
28,29,Employee_29,37,HR,34435,15,344350,378785,Low,Senior,Adult
29,30,Employee_30,35,Sales,62682,1,626820,689502,High,Junior,Adult
30,31,Employee_31,27,Finance,95829,10,958290,1054119,High,Junior,Young
31,32,Employee_32,23,IT,43127,18,431270,474397,Low,Senior,Young
32,33,Employee_33,20,HR,67486,5,674860,742346,High,Junior,Young
33,34,Employee_34,36,HR,65540,3,655400,720940,High,Junior,Adult
34,35,Employee_35,31,Sales,38120,6,381200,419320,Low,Junior,Adult
35,36,Employee_36,28,Sales,57203,18,572030,629233,Low,Senior,Young
36,37,Employee_37,40,IT,46398,8,463980,510378,Low,Junior,Adult
37,38,Employee_38,39,HR,49928,10,499280,549208,Low,Junior,Adult
38,39,Employee_39,30,HR,69635,4,696350,765985,High,Junior,Adult
39,40,Employee_40,38,IT,50928,12,509280,560208,Low,Senior,Adult
40,41,Employee_41,33,Sales,40536,11,405360,445896,Low,Senior,Adult
41,42,Employee_42,22,Sales,27967,16,279670,307637,Low,Senior,Young
42,43,Employee_43,42,HR,28240,3,282400,310640,Low,Junior,Adult
43,44,Employee_44,39,Sales,76389,17,763890,840279,High,Senior,Adult
44,45,Employee_45,42,Finance,35684,19,356840,392524,Low,Senior,Adult
45,46,Employee_46,48,Sales,91690,12,916900,1008590,High,Senior,Adult
46,47,Employee_47,23,IT,77773,4,777730,855503,High,Junior,Young
47,48,Employee_48,20,Finance,74886,5,748860,823746,High,Junior,Young
48,49,Employee_49,23,IT,95279,14,952790,1048069,High,Senior,Young
49,50,Employee_50,28,Finance,50753,14,507530,558283,Low,Senior,Young

In [18]:
df["Dept_Rank"] = df.groupby("Department")["Salary"].rank(ascending=False)
df

,Emp_ID,Name,Age,Department,Salary,Experience_Years,Bonus,Total_Income,Salary_Category,Level,Age_Group,Dept_Rank
0,1,Employee_1,32,IT,28186,18,281860,310046,Low,Senior,Adult,12.0
1,2,Employee_2,32,IT,59330,3,593300,652630,Low,Junior,Adult,8.0
2,3,Employee_3,26,HR,63153,12,631530,694683,High,Senior,Young,5.0
3,4,Employee_4,34,Finance,75784,9,757840,833624,High,Junior,Adult,3.0
4,5,Employee_5,36,Sales,52779,5,527790,580569,Low,Junior,Adult,11.0
5,6,Employee_6,36,IT,95987,9,959870,1055857,High,Junior,Adult,1.0
6,7,Employee_7,42,Finance,74972,7,749720,824692,High,Junior,Adult,4.0
7,8,Employee_8,46,IT,89446,12,894460,983906,High,Senior,Adult,3.0
8,9,Employee_9,38,Sales,32267,3,322670,354937,Low,Junior,Adult,14.0
9,10,Employee_10,46,Sales,53265,4,532650,585915,Low,Junior,Adult,10.0
10,11,Employee_11,29,Sales,74552,7,745520,820072,High,Junior,Young,4.0
11,12,Employee_12,26,Finance,67911,2,679110,747021,High,Junior,Young,7.0
12,13,Employee_13,30,HR,65147,17,651470,716617,High,Senior,Adult,4.0
13,14,Employee_14,27,IT,87922,16,879220,967142,High,Senior,Young,4.0
14,15,Employee_15,20,Sales,73118,11,731180,804298,High,Senior,Young,5.0
15,16,Employee_16,21,Finance,22807,14,228070,250877,Low,Senior,Young,11.0
16,17,Employee_17,44,Finance,82560,16,825600,908160,High,Senior,Adult,2.0
17,18,Employee_18,21,Sales,26730,16,267300,294030,Low,Senior,Young,17.0
18,19,Employee_19,44,IT,85959,2,859590,945549,High,Junior,Adult,5.0
19,20,Employee_20,20,Sales,27209,8,272090,299299,Low,Junior,Young,16.0
20,21,Employee_21,38,Sales,97917,14,979170,1077087,High,Senior,Adult,1.0
21,22,Employee_22,45,Sales,59121,5,591210,650331,Low,Junior,Adult,7.0
22,23,Employee_23,25,Finance,72176,11,721760,793936,High,Senior,Young,6.0
23,24,Employee_24,41,Sales,54823,3,548230,603053,Low,Junior,Adult,9.0
24,25,Employee_25,28,Finance,34625,9,346250,380875,Low,Junior,Young,10.0
25,26,Employee_26,34,IT,22831,12,228310,251141,Low,Senior,Adult,13.0
26,27,Employee_27,23,IT,62760,5,627600,690360,High,Junior,Young,7.0
27,28,Employee_28,37,HR,26300,7,263000,289300,Low,Junior,Adult,9.0
28,29,Employee_29,37,HR,34435,15,344350,378785,Low,Senior,Adult,7.0
29,30,Employee_30,35,Sales,62682,1,626820,689502,High,Junior,Adult,6.0
30,31,Employee_31,27,Finance,95829,10,958290,1054119,High,Junior,Young,1.0
31,32,Employee_32,23,IT,43127,18,431270,474397,Low,Senior,Young,11.0
32,33,Employee_33,20,HR,67486,5,674860,742346,High,Junior,Young,2.0
33,34,Employee_34,36,HR,65540,3,655400,720940,High,Junior,Adult,3.0
34,35,Employee_35,31,Sales,38120,6,381200,419320,Low,Junior,Adult,13.0
35,36,Employee_36,28,Sales,57203,18,572030,629233,Low,Senior,Young,8.0
36,37,Employee_37,40,IT,46398,8,463980,510378,Low,Junior,Adult,10.0
37,38,Employee_38,39,HR,49928,10,499280,549208,Low,Junior,Adult,6.0
38,39,Employee_39,30,HR,69635,4,696350,765985,High,Junior,Adult,1.0
39,40,Employee_40,38,IT,50928,12,509280,560208,Low,Senior,Adult,9.0
40,41,Employee_41,33,Sales,40536,11,405360,445896,Low,Senior,Adult,12.0
41,42,Employee_42,22,Sales,27967,16,279670,307637,Low,Senior,Young,15.0
42,43,Employee_43,42,HR,28240,3,282400,310640,Low,Junior,Adult,8.0
43,44,Employee_44,39,Sales,76389,17,763890,840279,High,Senior,Adult,3.0
44,45,Employee_45,42,Finance,35684,19,356840,392524,Low,Senior,Adult,9.0
45,46,Employee_46,48,Sales,91690,12,916900,1008590,High,Senior,Adult,2.0
46,47,Employee_47,23,IT,77773,4,777730,855503,High,Junior,Young,6.0
47,48,Employee_48,20,Finance,74886,5,748860,823746,High,Junior,Young,5.0
48,49,Employee_49,23,IT,95279,14,952790,1048069,High,Senior,Young,2.0
49,50,Employee_50,28,Finance,50753,14,507530,558283,Low,Senior,Young,8.0

🔹 8️⃣ Conditional Update (loc Apply)

In [19]:
df.loc[df["Department"] == "IT", "Salary"] += 5000
df

,Emp_ID,Name,Age,Department,Salary,Experience_Years,Bonus,Total_Income,Salary_Category,Level,Age_Group,Dept_Rank
0,1,Employee_1,32,IT,33186,18,281860,310046,Low,Senior,Adult,12.0
1,2,Employee_2,32,IT,64330,3,593300,652630,Low,Junior,Adult,8.0
2,3,Employee_3,26,HR,63153,12,631530,694683,High,Senior,Young,5.0
3,4,Employee_4,34,Finance,75784,9,757840,833624,High,Junior,Adult,3.0
4,5,Employee_5,36,Sales,52779,5,527790,580569,Low,Junior,Adult,11.0
5,6,Employee_6,36,IT,100987,9,959870,1055857,High,Junior,Adult,1.0
6,7,Employee_7,42,Finance,74972,7,749720,824692,High,Junior,Adult,4.0
7,8,Employee_8,46,IT,94446,12,894460,983906,High,Senior,Adult,3.0
8,9,Employee_9,38,Sales,32267,3,322670,354937,Low,Junior,Adult,14.0
9,10,Employee_10,46,Sales,53265,4,532650,585915,Low,Junior,Adult,10.0
10,11,Employee_11,29,Sales,74552,7,745520,820072,High,Junior,Young,4.0
11,12,Employee_12,26,Finance,67911,2,679110,747021,High,Junior,Young,7.0
12,13,Employee_13,30,HR,65147,17,651470,716617,High,Senior,Adult,4.0
13,14,Employee_14,27,IT,92922,16,879220,967142,High,Senior,Young,4.0
14,15,Employee_15,20,Sales,73118,11,731180,804298,High,Senior,Young,5.0
15,16,Employee_16,21,Finance,22807,14,228070,250877,Low,Senior,Young,11.0
16,17,Employee_17,44,Finance,82560,16,825600,908160,High,Senior,Adult,2.0
17,18,Employee_18,21,Sales,26730,16,267300,294030,Low,Senior,Young,17.0
18,19,Employee_19,44,IT,90959,2,859590,945549,High,Junior,Adult,5.0
19,20,Employee_20,20,Sales,27209,8,272090,299299,Low,Junior,Young,16.0
20,21,Employee_21,38,Sales,97917,14,979170,1077087,High,Senior,Adult,1.0
21,22,Employee_22,45,Sales,59121,5,591210,650331,Low,Junior,Adult,7.0
22,23,Employee_23,25,Finance,72176,11,721760,793936,High,Senior,Young,6.0
23,24,Employee_24,41,Sales,54823,3,548230,603053,Low,Junior,Adult,9.0
24,25,Employee_25,28,Finance,34625,9,346250,380875,Low,Junior,Young,10.0
25,26,Employee_26,34,IT,27831,12,228310,251141,Low,Senior,Adult,13.0
26,27,Employee_27,23,IT,67760,5,627600,690360,High,Junior,Young,7.0
27,28,Employee_28,37,HR,26300,7,263000,289300,Low,Junior,Adult,9.0
28,29,Employee_29,37,HR,34435,15,344350,378785,Low,Senior,Adult,7.0
29,30,Employee_30,35,Sales,62682,1,626820,689502,High,Junior,Adult,6.0
30,31,Employee_31,27,Finance,95829,10,958290,1054119,High,Junior,Young,1.0
31,32,Employee_32,23,IT,48127,18,431270,474397,Low,Senior,Young,11.0
32,33,Employee_33,20,HR,67486,5,674860,742346,High,Junior,Young,2.0
33,34,Employee_34,36,HR,65540,3,655400,720940,High,Junior,Adult,3.0
34,35,Employee_35,31,Sales,38120,6,381200,419320,Low,Junior,Adult,13.0
35,36,Employee_36,28,Sales,57203,18,572030,629233,Low,Senior,Young,8.0
36,37,Employee_37,40,IT,51398,8,463980,510378,Low,Junior,Adult,10.0
37,38,Employee_38,39,HR,49928,10,499280,549208,Low,Junior,Adult,6.0
38,39,Employee_39,30,HR,69635,4,696350,765985,High,Junior,Adult,1.0
39,40,Employee_40,38,IT,55928,12,509280,560208,Low,Senior,Adult,9.0
40,41,Employee_41,33,Sales,40536,11,405360,445896,Low,Senior,Adult,12.0
41,42,Employee_42,22,Sales,27967,16,279670,307637,Low,Senior,Young,15.0
42,43,Employee_43,42,HR,28240,3,282400,310640,Low,Junior,Adult,8.0
43,44,Employee_44,39,Sales,76389,17,763890,840279,High,Senior,Adult,3.0
44,45,Employee_45,42,Finance,35684,19,356840,392524,Low,Senior,Adult,9.0
45,46,Employee_46,48,Sales,91690,12,916900,1008590,High,Senior,Adult,2.0
46,47,Employee_47,23,IT,82773,4,777730,855503,High,Junior,Young,6.0
47,48,Employee_48,20,Finance,74886,5,748860,823746,High,Junior,Young,5.0
48,49,Employee_49,23,IT,100279,14,952790,1048069,High,Senior,Young,2.0
49,50,Employee_50,28,Finance,50753,14,507530,558283,Low,Senior,Young,8.0

# 🏆 📘 Pandas Mini Project (Employee Data)
🎯 Task 1

Bonus column create karo (10% of Salary)

🎯 Task 2

Total_Income column banao (Salary + Bonus)

🎯 Task 3

Salary_Category column banao:

Salary > 70000 → "High"

40000–70000 → "Medium"

< 40000 → "Low"

🎯 Task 4

Experience_Level column banao:

12 → Senior

6–12 → Mid

≤ 5 → Junior

🎯 Task 5

IT department ke employees ki salary 5000 increase karo.

🎯 Task 6

Top 5 highest salary wale employees show karo.

🎯 Task 7

Department wise average salary nikalo.

🎯 Task 8

Har department me highest salary wale employee ka naam nikalo.

🎯 Task 9

Age 25 se 35 ke beech wale employees filter karo.

🎯 Task 10 🔥 (Interview Level)

Department wise salary rank column banao.

# 🔥 Advanced Pandas Practice Questions

🎯 Q11

Department wise total salary expense nikalo.

👉 Hint: groupby() + sum()

🎯 Q12

Kaun sa department sabse zyada average salary de raha hai?

👉 Hint: mean() + idxmax()

🎯 Q13

Un employees ko filter karo jinki salary department average se zyada hai.

👉 Ye thoda tricky hai 😎
(Hint: transform("mean"))

🎯 Q14

Har employee ke liye salary ka percentage calculate karo
(Company total salary me se kitna % hai?)

🎯 Q15

Salary ke basis par employees ko 4 equal groups me divide karo
(Q1, Q2, Q3, Q4)

👉 Hint: pd.qcut()

🎯 Q16

Experience aur Salary ke basis par new column banao:

Senior + Salary > 70000 → "Premium"

Junior + Salary < 40000 → "Low Tier"

Baaki → "Standard"

🎯 Q17

Har department ka highest paid employee ka full record nikalo
(sirf naam nahi, poori row)

👉 Hint: groupby() + idxmax()

🎯 Q18

Salary aur Experience ke beech correlation nikalo.

👉 Hint: corr()

🎯 Q19

Age ka distribution check karo (value_counts in bins).

👉 Hint: pd.cut()

🎯 Q20 🔥 (Interview Level)

Company me total salary ka 20% cut karna hai
Sirf un logon par jinki salary > 80000.

New column banao: Revised_Salary

Suraj 💡
Agar tum Q13, Q15, Q17 solve kar loge na…
to samajh lo tum beginner nahi rahe 😎🔥