In [1]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_excel(r"C:\Users\Anish Kumar\Downloads\Pandas_Excel_Practice.xlsx")

In [5]:
df.head(5)

,OrderID,Date,Customer,City,Product,Category,Qty,Original_Price,Unit_Price,Sales,Salesperson,Discount
0,ORD0001,2025-05-06,Priya,Gurgaon,Mouse,Electronics,1,800,720.0,720.0,Raj,0.10
1,ORD0002,2025-01-17,Amit,Noida,Notebook,Stationery,2,120,102.0,204.0,Simran,0.15
2,ORD0003,2025-10-15,Priya,Hyderabad,Monitor,Electronics,9,12000,12000.0,108000.0,Simran,0.00
3,ORD0004,2025-01-04,Rahul,Hyderabad,Printer,Electronics,10,14500,13050.0,130500.0,Ankit,0.10
4,ORD0005,2025-06-22,Neha,Noida,Office Chair,Furniture,3,8500,8075.0,24225.0,Meena,0.05

In [ ]:
df.shape

(500, 12)

In [7]:
df.tail(5)

,OrderID,Date,Customer,City,Product,Category,Qty,Original_Price,Unit_Price,Sales,Salesperson,Discount
495,ORD0496,2025-06-24,Rahul,Bangalore,Pen,Stationery,4,30,28.5,114.0,Raj,0.05
496,ORD0497,2025-02-26,Arjun,Bangalore,Laptop,Electronics,3,55000,52250.0,156750.0,Raj,0.05
497,ORD0498,2025-06-22,Rohit,Bangalore,Desk,Furniture,7,6500,6500.0,45500.0,Simran,0.00
498,ORD0499,2025-11-29,Sneha,Gurgaon,Keyboard,Electronics,7,1500,1275.0,8925.0,Deepak,0.15
499,ORD0500,2025-12-07,Kiran,Gurgaon,Pen,Stationery,6,30,28.5,171.0,Meena,0.05

In [11]:
df.dtypes

OrderID                      str
Date              datetime64[us]
Customer                     str
City                         str
Product                      str
Category                     str
Qty                        int64
Original_Price             int64
Unit_Price               float64
Sales                    float64
Salesperson                  str
Discount                 float64
dtype: object

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   OrderID         500 non-null    str
 1   Date            500 non-null    datetime64[us]
 2   Customer        500 non-null    str
 3   City            500 non-null    str
 4   Product         500 non-null    str
 5   Category        500 non-null    str
 6   Qty             500 non-null    int64
 7   Original_Price  500 non-null    int64
 8   Unit_Price      500 non-null    float64
 9   Sales           500 non-null    float64
 10  Salesperson     500 non-null    str
 11  Discount        500 non-null    float64
dtypes: datetime64[us](1), float64(3), int64(2), str(6)
memory usage: 47.0 KB

In [14]:
df.columns

Index(['OrderID', 'Date', 'Customer', 'City', 'Product', 'Category', 'Qty',
       'Original_Price', 'Unit_Price', 'Sales', 'Salesperson', 'Discount'],
      dtype='str')

In [15]:
df.describe()

,Date,Qty,Original_Price,Unit_Price,Sales,Discount
count,500,500.000000,500.000000,500.000000,500.000000,500.000000
mean,2025-07-08 14:00:57.600000,5.380000,9635.380000,8784.453000,46741.425000,0.078500
min,2025-01-03 00:00:00,1.000000,30.000000,25.500000,25.500000,0.000000
25%,2025-04-03 18:00:00,3.000000,800.000000,720.000000,2662.500000,0.050000
50%,2025-07-08 12:00:00,5.000000,2200.000000,2200.000000,13145.000000,0.100000
75%,2025-10-16 00:00:00,8.000000,12000.000000,10800.000000,52650.000000,0.150000
max,2025-12-31 00:00:00,10.000000,55000.000000,55000.000000,522500.000000,0.150000
std,NaN,2.812013,15292.226484,13798.556431,87022.784407,0.056384

1. Date

In [33]:
df["Date"] = pd.to_datetime(df["Date"]).dt.strftime("%d/%m/%Y")

###  missing values count

In [34]:
df.isnull().sum()

OrderID           0
Date              0
Customer          0
City              0
Product           0
Category          0
Qty               0
Original_Price    0
Unit_Price        0
Sales             0
Salesperson       0
Discount          0
dtype: int64

### unique values

In [39]:
df["City"].unique()

<StringArray>
[  'Gurgaon',     'Noida', 'Hyderabad',     'Delhi',      'Pune', 'Bangalore',
   'Chennai',    'Mumbai']
Length: 8, dtype: str

In [40]:
df["Category"].unique()

<StringArray>
['Electronics', 'Stationery', 'Furniture']
Length: 3, dtype: str

1. Get all orders where the city is Delhi.

In [41]:
result = df[df["City"] == "Delhi"]
result

,OrderID,Date,Customer,City,Product,Category,Qty,Original_Price,Unit_Price,Sales,Salesperson,Discount
5,ORD0006,06/11/2025,Rohit,Delhi,Mouse,Electronics,6,800,720.0,4320.0,Meena,0.10
7,ORD0008,27/12/2025,Neha,Delhi,Desk,Furniture,10,6500,6175.0,61750.0,Simran,0.05
11,ORD0012,29/01/2025,Priya,Delhi,Notebook,Stationery,4,120,108.0,432.0,Ankit,0.10
18,ORD0019,22/03/2025,Pooja,Delhi,Mouse,Electronics,5,800,680.0,3400.0,Ankit,0.15
26,ORD0027,29/10/2025,Priya,Delhi,Pen,Stationery,9,30,28.5,256.5,Raj,0.05
37,ORD0038,30/01/2025,Kiran,Delhi,Monitor,Electronics,5,12000,11400.0,57000.0,Ankit,0.05
40,ORD0041,24/10/2025,Kiran,Delhi,Headphones,Electronics,2,2200,2090.0,4180.0,Deepak,0.05
59,ORD0060,25/10/2025,Rohit,Delhi,Mouse,Electronics,5,800,760.0,3800.0,Raj,0.05
61,ORD0062,23/01/2025,Vikas,Delhi,Pen,Stationery,4,30,27.0,108.0,Deepak,0.10
65,ORD0066,27/07/2025,Arjun,Delhi,Pen,Stationery,10,30,27.0,270.0,Ankit,0.10
83,ORD0084,21/07/2025,Kiran,Delhi,Keyboard,Electronics,10,1500,1500.0,15000.0,Raj,0.00
86,ORD0087,29/08/2025,Amit,Delhi,Headphones,Electronics,5,2200,2200.0,11000.0,Ankit,0.00
110,ORD0111,07/02/2025,Kiran,Delhi,Mouse,Electronics,7,800,680.0,4760.0,Simran,0.15
113,ORD0114,06/06/2025,Kiran,Delhi,Office Chair,Furniture,10,8500,7225.0,72250.0,Deepak,0.15
121,ORD0122,11/02/2025,Kiran,Delhi,Notebook,Stationery,8,120,102.0,816.0,Meena,0.15
143,ORD0144,12/06/2025,Pooja,Delhi,Desk,Furniture,9,6500,5525.0,49725.0,Deepak,0.15
145,ORD0146,22/12/2025,Rohit,Delhi,Mouse,Electronics,8,800,760.0,6080.0,Raj,0.05
153,ORD0154,25/12/2025,Rohit,Delhi,Pen,Stationery,6,30,27.0,162.0,Meena,0.10
177,ORD0178,23/08/2025,Amit,Delhi,Laptop,Electronics,9,55000,49500.0,445500.0,Meena,0.10
189,ORD0190,08/11/2025,Rohit,Delhi,Notebook,Stationery,10,120,120.0,1200.0,Simran,0.00
197,ORD0198,22/07/2025,Kiran,Delhi,Office Chair,Furniture,1,8500,8075.0,8075.0,Raj,0.05
200,ORD0201,06/02/2025,Vikas,Delhi,Notebook,Stationery,4,120,108.0,432.0,Meena,0.10
202,ORD0203,28/02/2025,Vikas,Delhi,Headphones,Electronics,7,2200,1980.0,13860.0,Ankit,0.10
211,ORD0212,20/08/2025,Amit,Delhi,Mouse,Electronics,5,800,680.0,3400.0,Ankit,0.15
221,ORD0222,18/09/2025,Sneha,Delhi,Notebook,Stationery,2,120,102.0,204.0,Ankit,0.15
223,ORD0224,01/06/2025,Neha,Delhi,Keyboard,Electronics,3,1500,1500.0,4500.0,Ankit,0.00
241,ORD0242,19/07/2025,Pooja,Delhi,Notebook,Stationery,9,120,120.0,1080.0,Meena,0.00
245,ORD0246,31/05/2025,Priya,Delhi,Mouse,Electronics,8,800,800.0,6400.0,Simran,0.00
272,ORD0273,16/10/2025,Amit,Delhi,Pen,Stationery,10,30,27.0,270.0,Raj,0.10
295,ORD0296,15/12/2025,Priya,Delhi,Pen,Stationery,7,30,28.5,199.5,Deepak,0.05
306,ORD0307,23/11/2025,Priya,Delhi,Laptop,Electronics,9,55000,52250.0,470250.0,Raj,0.05
307,ORD0308,21/02/2025,Rahul,Delhi,Headphones,Electronics,6,2200,1870.0,11220.0,Deepak,0.15
317,ORD0318,18/06/2025,Rohit,Delhi,Monitor,Electronics,8,12000,10800.0,86400.0,Ankit,0.10
326,ORD0327,22/08/2025,Kiran,Delhi,Printer,Electronics,3,14500,12325.0,36975.0,Deepak,0.15
327,ORD0328,22/07/2025,Rohit,Delhi,Printer,Electronics,5,14500,14500.0,72500.0,Simran,0.00
332,ORD0333,25/04/2025,Amit,Delhi,Notebook,Stationery,7,120,114.0,798.0,Ankit,0.05
337,ORD0338,04/10/2025,Priya,Delhi,Headphones,Electronics,8,2200,2090.0,16720.0,Simran,0.05
355,ORD0356,05/10/2025,Amit,Delhi,Notebook,Stationery,8,120,114.0,912.0,Raj,0.05
362,ORD0363,17/12/2025,Neha,Delhi,Monitor,Electronics,4,12000,10800.0,43200.0,Raj,0.10
363,ORD0364,10/10/2025,Pooja,Delhi,Headphones,Electronics,7,2200,1870.0,13090.0,Raj,0.15
366,ORD0367,06/10/2025,Kiran,Delhi,Laptop,Electronics,2,55000,49500.0,99000.0,Simran,0.10
398,ORD0399,30/12/2025,Neha,Delhi,Mouse,Electronics,5,800,800.0,4000.0,Ankit,0.00
419,ORD0420,16/04/2025,Priya,Delhi,Headphones,Electronics,3,2200,2090.0,6270.0,Deepak,0.05
425,ORD0426,07/09/2025,Sneha,Delhi,Office Chair,Furniture,6,8500,7225.0,43350.0,Raj,0.15
428,ORD0429,25/06/2025,Amit,Delhi,Pen,Stationery,3,30,25.5,76.5,Raj,0.15
442,ORD0443,20/07/2025,Rohit,Delhi,Notebook,Stationery,10,120,114.0,1140.0,Simran,0.05
450,ORD0451,01/03/2025,Pooja,Delhi,Monitor,Electronics,2,12000,10200.0,20400.0,Ankit,0.15
451,ORD0452,29/12/2025,Rahul,Delhi,Keyboard,Electronics,2,1500,1500.0,3000.0,Simran,0.00
456,ORD0457,18/09/2025,Amit,Delhi,Pen,Stationery,2,30,28.5,57.0,Raj,0.05
474,ORD0475,18/12/2025,Rohit,Delhi,Mouse,Electronics,2,800,760.0,1520.0,Simran,0.05
476,ORD0477,14/05/2025,Rahul,Delhi,Notebook,Stationery,1,120,108.0,108.0,Meena,0.10
480,ORD0481,19/06/2025,Neha,Delhi,Printer,Electronics,3,14500,14500.0,43500.0,Meena,0.00
481,ORD0482,22/07/2025,Pooja,Delhi,Laptop,Electronics,3,55000,46750.0,140250.0,Meena,0.15
488,ORD0489,16/01/2025,Rohit,Delhi,Desk,Furniture,10,6500,6175.0,61750.0,Meena,0.05
493,ORD0494,20/01/2025,Neha,Delhi,Office Chair,Furniture,3,8500,7225.0,21675.0,Simran,0.15
494,ORD0495,27/09/2025,Pooja,Delhi,Pen,Stationery,4,30,30.0,120.0,Ankit,0.00

2. Get all orders where the category is Electronics.

In [42]:
result = df[df["Category"] == "Electronics"]
result

,OrderID,Date,Customer,City,Product,Category,Qty,Original_Price,Unit_Price,Sales,Salesperson,Discount
0,ORD0001,06/05/2025,Priya,Gurgaon,Mouse,Electronics,1,800,720.0,720.0,Raj,0.10
2,ORD0003,15/10/2025,Priya,Hyderabad,Monitor,Electronics,9,12000,12000.0,108000.0,Simran,0.00
3,ORD0004,04/01/2025,Rahul,Hyderabad,Printer,Electronics,10,14500,13050.0,130500.0,Ankit,0.10
5,ORD0006,06/11/2025,Rohit,Delhi,Mouse,Electronics,6,800,720.0,4320.0,Meena,0.10
12,ORD0013,19/04/2025,Kiran,Bangalore,Headphones,Electronics,5,2200,2200.0,11000.0,Simran,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
486,ORD0487,03/09/2025,Arjun,Chennai,Laptop,Electronics,7,55000,49500.0,346500.0,Ankit,0.10
491,ORD0492,31/10/2025,Sneha,Bangalore,Keyboard,Electronics,3,1500,1425.0,4275.0,Deepak,0.05
492,ORD0493,16/10/2025,Priya,Chennai,Laptop,Electronics,6,55000,52250.0,313500.0,Deepak,0.05
496,ORD0497,26/02/2025,Arjun,Bangalore,Laptop,Electronics,3,55000,52250.0,156750.0,Raj,0.05
498,ORD0499,29/11/2025,Sneha,Gurgaon,Keyboard,Electronics,7,1500,1275.0,8925.0,Deepak,0.15

3. Get Electronics orders where sales are greater than 10,000.

In [44]:
result = df[
    (df["Category"] == "Electronics") &
    (df["Sales"] > 10000)
]
result

,OrderID,Date,Customer,City,Product,Category,Qty,Original_Price,Unit_Price,Sales,Salesperson,Discount
2,ORD0003,15/10/2025,Priya,Hyderabad,Monitor,Electronics,9,12000,12000.0,108000.0,Simran,0.00
3,ORD0004,04/01/2025,Rahul,Hyderabad,Printer,Electronics,10,14500,13050.0,130500.0,Ankit,0.10
12,ORD0013,19/04/2025,Kiran,Bangalore,Headphones,Electronics,5,2200,2200.0,11000.0,Simran,0.00
13,ORD0014,15/03/2025,Rohit,Gurgaon,Printer,Electronics,7,14500,12325.0,86275.0,Simran,0.15
15,ORD0016,16/02/2025,Amit,Noida,Monitor,Electronics,3,12000,10200.0,30600.0,Simran,0.15
...,...,...,...,...,...,...,...,...,...,...,...,...
483,ORD0484,11/11/2025,Kiran,Mumbai,Printer,Electronics,3,14500,14500.0,43500.0,Ankit,0.00
484,ORD0485,01/02/2025,Neha,Pune,Printer,Electronics,7,14500,12325.0,86275.0,Meena,0.15
486,ORD0487,03/09/2025,Arjun,Chennai,Laptop,Electronics,7,55000,49500.0,346500.0,Ankit,0.10
492,ORD0493,16/10/2025,Priya,Chennai,Laptop,Electronics,6,55000,52250.0,313500.0,Deepak,0.05
496,ORD0497,26/02/2025,Arjun,Bangalore,Laptop,Electronics,3,55000,52250.0,156750.0,Raj,0.05

5. Get all orders from Delhi and Noida.

In [45]:
result = df[df["City"].isin(["Delhi", "Noida"])]
result

,OrderID,Date,Customer,City,Product,Category,Qty,Original_Price,Unit_Price,Sales,Salesperson,Discount
1,ORD0002,17/01/2025,Amit,Noida,Notebook,Stationery,2,120,102.0,204.0,Simran,0.15
4,ORD0005,22/06/2025,Neha,Noida,Office Chair,Furniture,3,8500,8075.0,24225.0,Meena,0.05
5,ORD0006,06/11/2025,Rohit,Delhi,Mouse,Electronics,6,800,720.0,4320.0,Meena,0.10
7,ORD0008,27/12/2025,Neha,Delhi,Desk,Furniture,10,6500,6175.0,61750.0,Simran,0.05
11,ORD0012,29/01/2025,Priya,Delhi,Notebook,Stationery,4,120,108.0,432.0,Ankit,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...
480,ORD0481,19/06/2025,Neha,Delhi,Printer,Electronics,3,14500,14500.0,43500.0,Meena,0.00
481,ORD0482,22/07/2025,Pooja,Delhi,Laptop,Electronics,3,55000,46750.0,140250.0,Meena,0.15
488,ORD0489,16/01/2025,Rohit,Delhi,Desk,Furniture,10,6500,6175.0,61750.0,Meena,0.05
493,ORD0494,20/01/2025,Neha,Delhi,Office Chair,Furniture,3,8500,7225.0,21675.0,Simran,0.15
494,ORD0495,27/09/2025,Pooja,Delhi,Pen,Stationery,4,30,30.0,120.0,Ankit,0.00

# change the data type

In [52]:
df[["Sales", "Unit_Price"]] = df[["Sales", "Unit_Price"]].astype(int)

In [53]:
df

,OrderID,Date,Customer,City,Product,Category,Qty,Original_Price,Unit_Price,Sales,Salesperson,Discount
0,ORD0001,06/05/2025,Priya,Gurgaon,Mouse,Electronics,1,800,720,720,Raj,0.10
1,ORD0002,17/01/2025,Amit,Noida,Notebook,Stationery,2,120,102,204,Simran,0.15
2,ORD0003,15/10/2025,Priya,Hyderabad,Monitor,Electronics,9,12000,12000,108000,Simran,0.00
3,ORD0004,04/01/2025,Rahul,Hyderabad,Printer,Electronics,10,14500,13050,130500,Ankit,0.10
4,ORD0005,22/06/2025,Neha,Noida,Office Chair,Furniture,3,8500,8075,24225,Meena,0.05
...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD0496,24/06/2025,Rahul,Bangalore,Pen,Stationery,4,30,28,114,Raj,0.05
496,ORD0497,26/02/2025,Arjun,Bangalore,Laptop,Electronics,3,55000,52250,156750,Raj,0.05
497,ORD0498,22/06/2025,Rohit,Bangalore,Desk,Furniture,7,6500,6500,45500,Simran,0.00
498,ORD0499,29/11/2025,Sneha,Gurgaon,Keyboard,Electronics,7,1500,1275,8925,Deepak,0.15
499,ORD0500,07/12/2025,Kiran,Gurgaon,Pen,Stationery,6,30,28,171,Meena,0.05

### Calculations

1. Calculate the Total Sales.

In [56]:
Total_Sales = df["Sales"].sum()
print(Total_Sales)

23370706

2. Calculate the Average Sales.

In [57]:
Avg_Sales = df["Sales"].mean()
print(Avg_Sales)

46741.412

3. Find the Maximum Sales.

In [60]:
Max_Sales = df["Sales"].max()
print(Max_Sales)

522500

4. Find the Minimum Sales.

In [61]:
min_Sales = df["Sales"].min()
print(min_Sales)

25

5. Calculate the Total Quantity Sold.

In [62]:
total_quantity = df["Qty"].sum()
print(total_quantity)

2690

6. Count the Total Number of Orders.

In [63]:
Total_Count = df["OrderID"].count()
print(Total_Count)

500

### Sort + Top/Bottom

1. Sort product-wise total sales from highest to lowest.

In [64]:
product_sales = df.groupby("Product")["Sales"].sum().sort_values(ascending=False)
product_sales

Product
Laptop          12314500
Printer          3999825
Monitor          2258400
Office Chair     2039150
Desk             1511250
Headphones        603350
Keyboard          341700
Mouse             265240
Notebook           30210
Pen                 7081
Name: Sales, dtype: int64

2. Find the top 10 orders with the highest sales.

In [68]:
Top_10_orders = df.sort_values("Sales", ascending=False).head(10)
Top_10_orders

,OrderID,Date,Customer,City,Product,Category,Qty,Original_Price,Unit_Price,Sales,Salesperson,Discount
131,ORD0132,30/12/2025,Rahul,Pune,Laptop,Electronics,10,55000,52250,522500,Deepak,0.05
273,ORD0274,30/11/2025,Priya,Hyderabad,Laptop,Electronics,10,55000,49500,495000,Deepak,0.10
306,ORD0307,23/11/2025,Priya,Delhi,Laptop,Electronics,9,55000,52250,470250,Raj,0.05
392,ORD0393,19/06/2025,Vikas,Noida,Laptop,Electronics,10,55000,46750,467500,Raj,0.15
80,ORD0081,02/09/2025,Amit,Bangalore,Laptop,Electronics,10,55000,46750,467500,Ankit,0.15
177,ORD0178,23/08/2025,Amit,Delhi,Laptop,Electronics,9,55000,49500,445500,Meena,0.10
395,ORD0396,01/06/2025,Vikas,Noida,Laptop,Electronics,8,55000,55000,440000,Raj,0.00
201,ORD0202,10/06/2025,Kiran,Hyderabad,Laptop,Electronics,8,55000,55000,440000,Deepak,0.00
458,ORD0459,25/04/2025,Sneha,Mumbai,Laptop,Electronics,9,55000,46750,420750,Meena,0.15
132,ORD0133,17/02/2025,Priya,Noida,Laptop,Electronics,9,55000,46750,420750,Meena,0.15

3. Find the bottom 10 orders with the lowest sales.

In [70]:
Bottom_10_orders = df.sort_values("Sales", ascending=True).head(10)
Bottom_10_orders

,OrderID,Date,Customer,City,Product,Category,Qty,Original_Price,Unit_Price,Sales,Salesperson,Discount
469,ORD0470,06/12/2025,Rahul,Mumbai,Pen,Stationery,1,30,25,25,Ankit,0.15
336,ORD0337,03/11/2025,Amit,Mumbai,Pen,Stationery,1,30,25,25,Raj,0.15
123,ORD0124,23/10/2025,Amit,Gurgaon,Pen,Stationery,1,30,27,27,Meena,0.10
411,ORD0412,05/01/2025,Pooja,Gurgaon,Pen,Stationery,1,30,27,27,Simran,0.10
256,ORD0257,14/12/2025,Pooja,Bangalore,Pen,Stationery,1,30,28,28,Ankit,0.05
235,ORD0236,10/01/2025,Rohit,Mumbai,Pen,Stationery,1,30,30,30,Simran,0.00
170,ORD0171,20/06/2025,Priya,Gurgaon,Pen,Stationery,1,30,30,30,Deepak,0.00
454,ORD0455,22/08/2025,Arjun,Bangalore,Pen,Stationery,2,30,25,51,Raj,0.15
220,ORD0221,14/10/2025,Vikas,Bangalore,Pen,Stationery,2,30,27,54,Simran,0.10
468,ORD0469,23/11/2025,Vikas,Noida,Pen,Stationery,2,30,28,57,Deepak,0.05

4. Find the top 5 customers based on total sales.

In [74]:
total_sales = df.groupby("Customer")["Sales"].sum().sort_values(ascending=False).head(5)
total_sales

Customer
Priya    3220085
Vikas    2940849
Arjun    2818410
Amit     2596013
Sneha    2475871
Name: Sales, dtype: int64

5. Find the top 5 products based on total sales.

In [76]:
top_five_product = df.groupby("Product")["Sales"].sum().sort_values(ascending=False).head(5)
top_five_product

Product
Laptop          12314500
Printer          3999825
Monitor          2258400
Office Chair     2039150
Desk             1511250
Name: Sales, dtype: int64

6. Find the top 3 salespersons based on total sales.

7. Sort the total sales by product in descending order.

8. Identify the top 10 orders with the highest sales amount.

9. Identify the bottom 10 orders with the lowest sales amount.

10. Identify the top 5 customers based on their total sales.

11. Identify the top 5 products based on their total sales.

12. Identify the top 3 salespersons based on their total sales.

## New Columns

11. Calculate Gross Sales

In [ ]:
df["Gross_Sales"] = df["Qty"] * df["Original_Price"]

1. Create a new column called Profit.
- Formula: Sales - Cost
- Where Cost = Qty × Original_Price × 70%.

In [78]:
df["Profit"] = df["Sales"] - (df["Qty"] * df["Original_Price"] * 0.70)

2. Create a new column called Profit_Margin.
- Formula: (Profit / Sales) × 100.

In [86]:
df["Profit_Margin"] = ((df["Profit"] / df["Sales"]) * 100).apply(int)

3. Create a new column called Discount_Amount.
- Formula: Gross_Sales - Sales.

In [84]:
df["Discount_Amount"] = df["Gross_Sales"] - df["Sales"]

4. Create a new column called Final_Revenue.
- Formula: Sales - Discount_Amount.

In [88]:
df["Final_Revenue"] = df["Sales"] - df["Discount_Amount"]

5. Create a new column called Price_With_GST.
- Add 18% GST to Unit_Price.

In [93]:
df["Price_With_GST"] = (df["Unit_Price"] * 1.18).apply(int)

6. Create a new column called Net_Value.
- Formula: Qty × Unit_Price.

In [91]:
df["Net_Value"] = df["Qty"] * df["Unit_Price"]

7. Create a Revenue_Category column:
- Sales >= 50,000 → Very High
- Sales >= 25,000 → High
- Sales >= 10,000 → Medium
- Sales >= 5,000 → Low
- Otherwise → Very Low

In [95]:
df["Revenue_Category"] = df["Sales"].apply(
    lambda x:"Very High" if x >= 50000
    else "High" if x >= 25000 
    else "Medium" if x >= 10000
    else "Low" if x >= 5000
    else "Very Low" 
)

8. Create a Performance column using both Sales and Discount:
- Sales > 50,000 AND Discount < 10% → Excellent
- Sales > 20,000 AND Discount < 15% → Good
- Sales > 5,000 → Average
- Otherwise → Poor

In [101]:
df["Performance"] = df.apply(
    lambda row: "Excellent" if row["Sales"] > 50000 and row["Discount"] < 0.10
    else "Good" if row["Sales"] > 20000 and row["Discount"] < 0.15
    else "Average" if row["Sales"] > 5000
    else "Poor",
    axis=1
)

9. Create a Quantity_Category column:
- Qty >= 8 → Bulk
- Qty >= 5 → Medium
- Qty >= 2 → Small
- Otherwise → Single

10. Create a Score column:
- Sales > 30,000 → 10 points
- Sales > 15,000 → 7 points
- Sales > 5,000 → 5 points
- Otherwise → 2 points

In [102]:
df.head(10)

,OrderID,Date,Customer,City,Product,Category,Qty,Original_Price,Unit_Price,Sales,...,Discount,Profit,Profit_Margin,Gross_Sales,Discount_Amount,Final_Revenue,Price_With_GST,Net_Value,Revenue_Category,Performance
0,ORD0001,06/05/2025,Priya,Gurgaon,Mouse,Electronics,1,800,720,720,...,0.10,160.0,22,800,80,640,849,720,Very Low,Poor
1,ORD0002,17/01/2025,Amit,Noida,Notebook,Stationery,2,120,102,204,...,0.15,36.0,17,240,36,168,120,204,Very Low,Poor
2,ORD0003,15/10/2025,Priya,Hyderabad,Monitor,Electronics,9,12000,12000,108000,...,0.00,32400.0,30,108000,0,108000,14160,108000,Very High,Excellent
3,ORD0004,04/01/2025,Rahul,Hyderabad,Printer,Electronics,10,14500,13050,130500,...,0.10,29000.0,22,145000,14500,116000,15399,130500,Very High,Good
4,ORD0005,22/06/2025,Neha,Noida,Office Chair,Furniture,3,8500,8075,24225,...,0.05,6375.0,26,25500,1275,22950,9528,24225,Medium,Good
5,ORD0006,06/11/2025,Rohit,Delhi,Mouse,Electronics,6,800,720,4320,...,0.10,960.0,22,4800,480,3840,849,4320,Very Low,Poor
6,ORD0007,10/02/2025,Arjun,Pune,Notebook,Stationery,2,120,102,204,...,0.15,36.0,17,240,36,168,120,204,Very Low,Poor
7,ORD0008,27/12/2025,Neha,Delhi,Desk,Furniture,10,6500,6175,61750,...,0.05,16250.0,26,65000,3250,58500,7286,61750,Very High,Excellent
8,ORD0009,21/02/2025,Vikas,Pune,Office Chair,Furniture,2,8500,8075,16150,...,0.05,4250.0,26,17000,850,15300,9528,16150,Medium,Average
9,ORD0010,01/07/2025,Priya,Pune,Desk,Furniture,3,6500,5850,17550,...,0.10,3900.0,22,19500,1950,15600,6903,17550,Medium,Average