In [2]:
import pandas as pd
import numpy as np

1. Load the dataset using Pandas.

In [7]:
df = pd.read_excel(r"C:\Users\Anish Kumar\Downloads\pandas_data.xlsx")

In [8]:
df

,Employee_ID,Name,Age,City,Department,Salary,Joining_Date,Email
0,1,Suraj,22.0,mumbai,IT,40000.0,15/02/2023,suraj@gmail.com
1,2,Anjali,25.0,NaN,Finance,25000.0,2023-01-15,suraj@gmail.com
2,3,Priya,30.0,Pune,sales,25000.0,NaN,priya@gmail.com
3,4,Anjali,NaN,Mumbai,Finance,45000.0,2023-01-15,rahul@gmail.com
4,5,Pooja,NaN,mumbai,IT,40000.0,2022/03/20,suraj@gmail.com
5,6,Suraj,NaN,delhi,HR,NaN,NaN,neha@gmail.com
6,7,Amit,150.0,Pune,Sales,NaN,2023-01-15,anjali@gmail.com
7,8,Neha,NaN,NaN,IT,30000.0,2023-01-15,priya@gmail.com
8,9,Neha,25.0,Mumbai,NaN,30000.0,01-04-2024,neha@gmail.com
9,10,Vikas,NaN,DELHI,HR,NaN,15/02/2023,neha@gmail.com
10,11,Suraj,28.0,Pune,it,40000.0,15/02/2023,vikas@gmail.com
11,12,Pooja,35.0,Pune,IT,NaN,2023-01-15,priya@gmail.com
12,13,Amit,NaN,Bengaluru,HR,30000.0,15/02/2023,karan@gmail.com
13,14,Ravi,30.0,Kolkata,Finance,999999.0,15/02/2023,neha@gmail.com
14,15,Rahul,30.0,Pune,sales,45000.0,NaN,karan@gmail.com
15,16,Pooja,NaN,Bangalore,IT,35000.0,NaN,vikas@gmail.com
16,17,Suraj,22.0,delhi,IT,35000.0,NaN,pooja@gmail.com
17,18,Karan,25.0,Bengaluru,Finance,999999.0,NaN,neha@gmail.com
18,19,Anjali,22.0,delhi,it,45000.0,NaN,ravi@gmail.com
19,20,Suraj,35.0,Bengaluru,IT,999999.0,2023-01-15,neha@gmail.com
20,21,Anjali,28.0,Pune,Sales,45000.0,NaN,anjali@gmail.com
21,22,Karan,30.0,DELHI,HR,35000.0,NaN,anjali@gmail.com
22,23,Amit,NaN,Kolkata,Sales,30000.0,2022/03/20,neha@gmail.com
23,24,Priya,22.0,Mumbai,sales,30000.0,2023-01-15,vikas@gmail.com
24,25,Suraj,28.0,DELHI,it,999999.0,NaN,rahul@gmail.com
25,26,Neha,NaN,Mumbai,sales,40000.0,NaN,neha@gmail.com
26,27,Pooja,NaN,Kolkata,sales,999999.0,2023-01-15,priya@gmail.com
27,28,Priya,25.0,Bangalore,Sales,40000.0,NaN,priya@gmail.com
28,29,Amit,25.0,Delhi,IT,30000.0,2023-01-15,ravi@gmail.com
29,30,Suraj,30.0,mumbai,it,999999.0,15/02/2023,anjali@gmail.com
30,31,Rahul,150.0,Mumbai,NaN,999999.0,01-04-2024,priya@gmail.com
31,32,Suraj,25.0,Bengaluru,HR,NaN,01-04-2024,vikas@gmail.com
32,33,Amit,25.0,Delhi,Finance,NaN,2023-01-15,priya@gmail.com
33,34,Priya,30.0,Pune,Finance,35000.0,01-04-2024,rahul@gmail.com
34,35,Neha,150.0,Mumbai,NaN,30000.0,01-04-2024,anjali@gmail.com
35,36,Suraj,22.0,Pune,NaN,25000.0,2023-01-15,priya@gmail.com
36,37,Rahul,NaN,Kolkata,Finance,40000.0,01-04-2024,amit@gmail.com
37,38,Rahul,NaN,Delhi,Finance,45000.0,01-04-2024,neha@gmail.com
38,39,Pooja,150.0,DELHI,IT,45000.0,15/02/2023,amit@gmail.com
39,40,Karan,22.0,Bangalore,Sales,25000.0,NaN,vikas@gmail.com
40,41,Anjali,28.0,Delhi,sales,30000.0,15/02/2023,suraj@gmail.com
41,42,Karan,25.0,Mumbai,Finance,30000.0,NaN,priya@gmail.com
42,43,Karan,22.0,NaN,Sales,NaN,NaN,karan@gmail.com
43,44,Karan,NaN,mumbai,IT,NaN,15/02/2023,neha@gmail.com
44,45,Pooja,28.0,mumbai,Finance,NaN,2023-01-15,amit@gmail.com
45,46,Vikas,25.0,delhi,sales,40000.0,NaN,neha@gmail.com
46,47,Rahul,NaN,delhi,IT,NaN,2022/03/20,rahul@gmail.com
47,48,Vikas,35.0,NaN,NaN,25000.0,NaN,anjali@gmail.com
48,49,Neha,25.0,DELHI,HR,30000.0,2023-01-15,anjali@gmail.com
49,50,Rahul,35.0,mumbai,sales,40000.0,NaN,ravi@gmail.com
50,51,Priya,35.0,Pune,Finance,45000.0,2023-01-15,suraj@gmail.com
51,52,Pooja,35.0,Delhi,Sales,NaN,15/02/2023,neha@gmail.com
52,53,Rahul,150.0,Pune,it,NaN,NaN,amit@gmail.com
53,54,Suraj,25.0,DELHI,sales,25000.0,2022/03/20,karan@gmail.com
54,55,Anjali,28.0,Bengaluru,IT,25000.0,2022/03/20,ravi@gmail.com
55,6,Suraj,NaN,delhi,HR,NaN,NaN,neha@gmail.com
56,11,Suraj,28.0,Pune,it,40000.0,15/02/2023,vikas@gmail.com
57,21,Anjali,28.0,Pune,Sales,45000.0,NaN,anjali@gmail.com
58,59,Neha,28.0,delhi,Finance,25000.0,01-04-2024,priya@gmail.com
59,60,Priya,150.0,Bangalore,HR,40000.0,15/02/2023,amit@gmail.com

2. Display the first 5 rows of the dataset.

In [9]:
df.head(5)

,Employee_ID,Name,Age,City,Department,Salary,Joining_Date,Email
0,1,Suraj,22.0,mumbai,IT,40000.0,15/02/2023,suraj@gmail.com
1,2,Anjali,25.0,NaN,Finance,25000.0,2023-01-15,suraj@gmail.com
2,3,Priya,30.0,Pune,sales,25000.0,NaN,priya@gmail.com
3,4,Anjali,NaN,Mumbai,Finance,45000.0,2023-01-15,rahul@gmail.com
4,5,Pooja,NaN,mumbai,IT,40000.0,2022/03/20,suraj@gmail.com

3. Display the last 5 rows of the dataset.

In [10]:
df.tail(5)

,Employee_ID,Name,Age,City,Department,Salary,Joining_Date,Email
55,6,Suraj,NaN,delhi,HR,NaN,NaN,neha@gmail.com
56,11,Suraj,28.0,Pune,it,40000.0,15/02/2023,vikas@gmail.com
57,21,Anjali,28.0,Pune,Sales,45000.0,NaN,anjali@gmail.com
58,59,Neha,28.0,delhi,Finance,25000.0,01-04-2024,priya@gmail.com
59,60,Priya,150.0,Bangalore,HR,40000.0,15/02/2023,amit@gmail.com

4. Check the shape of the dataset.

In [11]:
df.shape

(60, 8)

5. Check the column names.

In [12]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'City', 'Department', 'Salary',
       'Joining_Date', 'Email'],
      dtype='str')

6. Check the data types of all columns.

In [14]:
df.dtypes

Employee_ID       int64
Name                str
Age             float64
City                str
Department          str
Salary          float64
Joining_Date        str
Email               str
dtype: object

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Employee_ID   60 non-null     int64
 1   Name          60 non-null     str
 2   Age           45 non-null     float64
 3   City          56 non-null     str
 4   Department    55 non-null     str
 5   Salary        47 non-null     float64
 6   Joining_Date  39 non-null     str
 7   Email         60 non-null     str
dtypes: float64(2), int64(1), str(5)
memory usage: 3.9 KB

7. Find the total number of missing values in each column.

In [15]:
df.isna().sum()

Employee_ID      0
Name             0
Age             15
City             4
Department       5
Salary          13
Joining_Date    21
Email            0
dtype: int64

8. Replace "N/A" values with NaN.

In [16]:
df.replace("N/A", np.nan, inplace=True)

,Employee_ID,Name,Age,City,Department,Salary,Joining_Date,Email
0,1,Suraj,22.0,mumbai,IT,40000.0,15/02/2023,suraj@gmail.com
1,2,Anjali,25.0,NaN,Finance,25000.0,2023-01-15,suraj@gmail.com
2,3,Priya,30.0,Pune,sales,25000.0,NaN,priya@gmail.com
3,4,Anjali,NaN,Mumbai,Finance,45000.0,2023-01-15,rahul@gmail.com
4,5,Pooja,NaN,mumbai,IT,40000.0,2022/03/20,suraj@gmail.com
5,6,Suraj,NaN,delhi,HR,NaN,NaN,neha@gmail.com
6,7,Amit,150.0,Pune,Sales,NaN,2023-01-15,anjali@gmail.com
7,8,Neha,NaN,NaN,IT,30000.0,2023-01-15,priya@gmail.com
8,9,Neha,25.0,Mumbai,NaN,30000.0,01-04-2024,neha@gmail.com
9,10,Vikas,NaN,DELHI,HR,NaN,15/02/2023,neha@gmail.com
10,11,Suraj,28.0,Pune,it,40000.0,15/02/2023,vikas@gmail.com
11,12,Pooja,35.0,Pune,IT,NaN,2023-01-15,priya@gmail.com
12,13,Amit,NaN,Bengaluru,HR,30000.0,15/02/2023,karan@gmail.com
13,14,Ravi,30.0,Kolkata,Finance,999999.0,15/02/2023,neha@gmail.com
14,15,Rahul,30.0,Pune,sales,45000.0,NaN,karan@gmail.com
15,16,Pooja,NaN,Bangalore,IT,35000.0,NaN,vikas@gmail.com
16,17,Suraj,22.0,delhi,IT,35000.0,NaN,pooja@gmail.com
17,18,Karan,25.0,Bengaluru,Finance,999999.0,NaN,neha@gmail.com
18,19,Anjali,22.0,delhi,it,45000.0,NaN,ravi@gmail.com
19,20,Suraj,35.0,Bengaluru,IT,999999.0,2023-01-15,neha@gmail.com
20,21,Anjali,28.0,Pune,Sales,45000.0,NaN,anjali@gmail.com
21,22,Karan,30.0,DELHI,HR,35000.0,NaN,anjali@gmail.com
22,23,Amit,NaN,Kolkata,Sales,30000.0,2022/03/20,neha@gmail.com
23,24,Priya,22.0,Mumbai,sales,30000.0,2023-01-15,vikas@gmail.com
24,25,Suraj,28.0,DELHI,it,999999.0,NaN,rahul@gmail.com
25,26,Neha,NaN,Mumbai,sales,40000.0,NaN,neha@gmail.com
26,27,Pooja,NaN,Kolkata,sales,999999.0,2023-01-15,priya@gmail.com
27,28,Priya,25.0,Bangalore,Sales,40000.0,NaN,priya@gmail.com
28,29,Amit,25.0,Delhi,IT,30000.0,2023-01-15,ravi@gmail.com
29,30,Suraj,30.0,mumbai,it,999999.0,15/02/2023,anjali@gmail.com
30,31,Rahul,150.0,Mumbai,NaN,999999.0,01-04-2024,priya@gmail.com
31,32,Suraj,25.0,Bengaluru,HR,NaN,01-04-2024,vikas@gmail.com
32,33,Amit,25.0,Delhi,Finance,NaN,2023-01-15,priya@gmail.com
33,34,Priya,30.0,Pune,Finance,35000.0,01-04-2024,rahul@gmail.com
34,35,Neha,150.0,Mumbai,NaN,30000.0,01-04-2024,anjali@gmail.com
35,36,Suraj,22.0,Pune,NaN,25000.0,2023-01-15,priya@gmail.com
36,37,Rahul,NaN,Kolkata,Finance,40000.0,01-04-2024,amit@gmail.com
37,38,Rahul,NaN,Delhi,Finance,45000.0,01-04-2024,neha@gmail.com
38,39,Pooja,150.0,DELHI,IT,45000.0,15/02/2023,amit@gmail.com
39,40,Karan,22.0,Bangalore,Sales,25000.0,NaN,vikas@gmail.com
40,41,Anjali,28.0,Delhi,sales,30000.0,15/02/2023,suraj@gmail.com
41,42,Karan,25.0,Mumbai,Finance,30000.0,NaN,priya@gmail.com
42,43,Karan,22.0,NaN,Sales,NaN,NaN,karan@gmail.com
43,44,Karan,NaN,mumbai,IT,NaN,15/02/2023,neha@gmail.com
44,45,Pooja,28.0,mumbai,Finance,NaN,2023-01-15,amit@gmail.com
45,46,Vikas,25.0,delhi,sales,40000.0,NaN,neha@gmail.com
46,47,Rahul,NaN,delhi,IT,NaN,2022/03/20,rahul@gmail.com
47,48,Vikas,35.0,NaN,NaN,25000.0,NaN,anjali@gmail.com
48,49,Neha,25.0,DELHI,HR,30000.0,2023-01-15,anjali@gmail.com
49,50,Rahul,35.0,mumbai,sales,40000.0,NaN,ravi@gmail.com
50,51,Priya,35.0,Pune,Finance,45000.0,2023-01-15,suraj@gmail.com
51,52,Pooja,35.0,Delhi,Sales,NaN,15/02/2023,neha@gmail.com
52,53,Rahul,150.0,Pune,it,NaN,NaN,amit@gmail.com
53,54,Suraj,25.0,DELHI,sales,25000.0,2022/03/20,karan@gmail.com
54,55,Anjali,28.0,Bengaluru,IT,25000.0,2022/03/20,ravi@gmail.com
55,6,Suraj,NaN,delhi,HR,NaN,NaN,neha@gmail.com
56,11,Suraj,28.0,Pune,it,40000.0,15/02/2023,vikas@gmail.com
57,21,Anjali,28.0,Pune,Sales,45000.0,NaN,anjali@gmail.com
58,59,Neha,28.0,delhi,Finance,25000.0,01-04-2024,priya@gmail.com
59,60,Priya,150.0,Bangalore,HR,40000.0,15/02/2023,amit@gmail.com

9. Find duplicate rows in the dataset.

In [18]:
df.duplicated().sum()

np.int64(3)

10. Find duplicate rows in the dataset.

In [19]:
df[df.duplicated()]

,Employee_ID,Name,Age,City,Department,Salary,Joining_Date,Email
55,6,Suraj,NaN,delhi,HR,NaN,NaN,neha@gmail.com
56,11,Suraj,28.0,Pune,it,40000.0,15/02/2023,vikas@gmail.com
57,21,Anjali,28.0,Pune,Sales,45000.0,NaN,anjali@gmail.com

11. Remove duplicate rows.

In [20]:
df.drop_duplicates()

,Employee_ID,Name,Age,City,Department,Salary,Joining_Date,Email
0,1,Suraj,22.0,mumbai,IT,40000.0,15/02/2023,suraj@gmail.com
1,2,Anjali,25.0,NaN,Finance,25000.0,2023-01-15,suraj@gmail.com
2,3,Priya,30.0,Pune,sales,25000.0,NaN,priya@gmail.com
3,4,Anjali,NaN,Mumbai,Finance,45000.0,2023-01-15,rahul@gmail.com
4,5,Pooja,NaN,mumbai,IT,40000.0,2022/03/20,suraj@gmail.com
5,6,Suraj,NaN,delhi,HR,NaN,NaN,neha@gmail.com
6,7,Amit,150.0,Pune,Sales,NaN,2023-01-15,anjali@gmail.com
7,8,Neha,NaN,NaN,IT,30000.0,2023-01-15,priya@gmail.com
8,9,Neha,25.0,Mumbai,NaN,30000.0,01-04-2024,neha@gmail.com
9,10,Vikas,NaN,DELHI,HR,NaN,15/02/2023,neha@gmail.com
10,11,Suraj,28.0,Pune,it,40000.0,15/02/2023,vikas@gmail.com
11,12,Pooja,35.0,Pune,IT,NaN,2023-01-15,priya@gmail.com
12,13,Amit,NaN,Bengaluru,HR,30000.0,15/02/2023,karan@gmail.com
13,14,Ravi,30.0,Kolkata,Finance,999999.0,15/02/2023,neha@gmail.com
14,15,Rahul,30.0,Pune,sales,45000.0,NaN,karan@gmail.com
15,16,Pooja,NaN,Bangalore,IT,35000.0,NaN,vikas@gmail.com
16,17,Suraj,22.0,delhi,IT,35000.0,NaN,pooja@gmail.com
17,18,Karan,25.0,Bengaluru,Finance,999999.0,NaN,neha@gmail.com
18,19,Anjali,22.0,delhi,it,45000.0,NaN,ravi@gmail.com
19,20,Suraj,35.0,Bengaluru,IT,999999.0,2023-01-15,neha@gmail.com
20,21,Anjali,28.0,Pune,Sales,45000.0,NaN,anjali@gmail.com
21,22,Karan,30.0,DELHI,HR,35000.0,NaN,anjali@gmail.com
22,23,Amit,NaN,Kolkata,Sales,30000.0,2022/03/20,neha@gmail.com
23,24,Priya,22.0,Mumbai,sales,30000.0,2023-01-15,vikas@gmail.com
24,25,Suraj,28.0,DELHI,it,999999.0,NaN,rahul@gmail.com
25,26,Neha,NaN,Mumbai,sales,40000.0,NaN,neha@gmail.com
26,27,Pooja,NaN,Kolkata,sales,999999.0,2023-01-15,priya@gmail.com
27,28,Priya,25.0,Bangalore,Sales,40000.0,NaN,priya@gmail.com
28,29,Amit,25.0,Delhi,IT,30000.0,2023-01-15,ravi@gmail.com
29,30,Suraj,30.0,mumbai,it,999999.0,15/02/2023,anjali@gmail.com
30,31,Rahul,150.0,Mumbai,NaN,999999.0,01-04-2024,priya@gmail.com
31,32,Suraj,25.0,Bengaluru,HR,NaN,01-04-2024,vikas@gmail.com
32,33,Amit,25.0,Delhi,Finance,NaN,2023-01-15,priya@gmail.com
33,34,Priya,30.0,Pune,Finance,35000.0,01-04-2024,rahul@gmail.com
34,35,Neha,150.0,Mumbai,NaN,30000.0,01-04-2024,anjali@gmail.com
35,36,Suraj,22.0,Pune,NaN,25000.0,2023-01-15,priya@gmail.com
36,37,Rahul,NaN,Kolkata,Finance,40000.0,01-04-2024,amit@gmail.com
37,38,Rahul,NaN,Delhi,Finance,45000.0,01-04-2024,neha@gmail.com
38,39,Pooja,150.0,DELHI,IT,45000.0,15/02/2023,amit@gmail.com
39,40,Karan,22.0,Bangalore,Sales,25000.0,NaN,vikas@gmail.com
40,41,Anjali,28.0,Delhi,sales,30000.0,15/02/2023,suraj@gmail.com
41,42,Karan,25.0,Mumbai,Finance,30000.0,NaN,priya@gmail.com
42,43,Karan,22.0,NaN,Sales,NaN,NaN,karan@gmail.com
43,44,Karan,NaN,mumbai,IT,NaN,15/02/2023,neha@gmail.com
44,45,Pooja,28.0,mumbai,Finance,NaN,2023-01-15,amit@gmail.com
45,46,Vikas,25.0,delhi,sales,40000.0,NaN,neha@gmail.com
46,47,Rahul,NaN,delhi,IT,NaN,2022/03/20,rahul@gmail.com
47,48,Vikas,35.0,NaN,NaN,25000.0,NaN,anjali@gmail.com
48,49,Neha,25.0,DELHI,HR,30000.0,2023-01-15,anjali@gmail.com
49,50,Rahul,35.0,mumbai,sales,40000.0,NaN,ravi@gmail.com
50,51,Priya,35.0,Pune,Finance,45000.0,2023-01-15,suraj@gmail.com
51,52,Pooja,35.0,Delhi,Sales,NaN,15/02/2023,neha@gmail.com
52,53,Rahul,150.0,Pune,it,NaN,NaN,amit@gmail.com
53,54,Suraj,25.0,DELHI,sales,25000.0,2022/03/20,karan@gmail.com
54,55,Anjali,28.0,Bengaluru,IT,25000.0,2022/03/20,ravi@gmail.com
58,59,Neha,28.0,delhi,Finance,25000.0,01-04-2024,priya@gmail.com
59,60,Priya,150.0,Bangalore,HR,40000.0,15/02/2023,amit@gmail.com

12. Fill missing values in the Age column using the median.

In [21]:
df["Age"] = df["Age"].fillna(df["Age"].median())

13. Fill missing values in the Salary column using the median.

In [24]:
df["Salary"] = df["Salary"].fillna(df["Salary"].median())

14. Fill missing values in the City column using the mode.

In [26]:
df["City"] = df["City"].fillna(df["City"].mode()[0])

15. Fill missing values in the Department column using the mode.

In [28]:
df["Department"] = df["Department"].fillna(df["Department"].mode()[0])

15. Convert the Age column to numeric data type.
- pd.to_numeric() → values ko numeric type mein convert karta hai

In [33]:
df["Age"] = pd.to_numeric(df["Age"]).apply(int)

16. Convert the Salary column to numeric data type.

In [35]:
df["Salary"] = pd.to_numeric(df["Salary"]).apply(int)

16. Check all unique values in the City column.

In [37]:
df["City"].unique()

<StringArray>
[   'mumbai',      'Pune',    'Mumbai',     'delhi',     'DELHI', 'Bengaluru',
   'Kolkata', 'Bangalore',     'Delhi']
Length: 9, dtype: str

17. Standardize city names such as delhi, DELHI, and Delhi into one format.
- .str.title() → Har word ka first letter capital karta hai.

In [38]:
df["City"] = df["City"].str.title()

18. Check all unique values in the Department column.

In [41]:
df["Department"].unique()

<StringArray>
['IT', 'Finance', 'sales', 'HR', 'Sales', 'it']
Length: 6, dtype: str

19. Standardize department names such as sales and Sales.

In [42]:
df["Department"] = df["Department"].str.title()

19. Remove extra spaces from all text columns.

In [46]:
for col in df.select_dtypes(include="object"):
    df[col] = df[col].str.strip()

C:\Users\Anish Kumar\AppData\Local\Temp\ipykernel_31152\3483331084.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object"):

20. Convert the Joining_Date column into datetime format.

In [49]:
df["Joining_Date"] = pd.to_datetime(
    df["Joining_Date"],
    format="mixed"
).dt.strftime("%d/%m/%Y")

In [54]:
df["Joining_Date"] = pd.to_datetime(
    df["Joining_Date"],
    format="mixed"
)

df["Joining_Date"] = df["Joining_Date"].fillna(
    df["Joining_Date"].median()
)

df["Joining_Date"] = df["Joining_Date"].dt.strftime("%d/%m/%Y")

In [55]:
df

,Employee_ID,Name,Age,City,Department,Salary,Joining_Date,Email
0,1,Suraj,22,Mumbai,It,40000,15/02/2023,suraj@gmail.com
1,2,Anjali,25,Pune,Finance,25000,15/01/2023,suraj@gmail.com
2,3,Priya,30,Pune,Sales,25000,15/02/2023,priya@gmail.com
3,4,Anjali,28,Mumbai,Finance,45000,15/01/2023,rahul@gmail.com
4,5,Pooja,28,Mumbai,It,40000,20/03/2022,suraj@gmail.com
5,6,Suraj,28,Delhi,Hr,40000,15/02/2023,neha@gmail.com
6,7,Amit,150,Pune,Sales,40000,15/01/2023,anjali@gmail.com
7,8,Neha,28,Pune,It,30000,15/01/2023,priya@gmail.com
8,9,Neha,25,Mumbai,Finance,30000,01/04/2024,neha@gmail.com
9,10,Vikas,28,Delhi,Hr,40000,15/02/2023,neha@gmail.com
10,11,Suraj,28,Pune,It,40000,15/02/2023,vikas@gmail.com
11,12,Pooja,35,Pune,It,40000,15/01/2023,priya@gmail.com
12,13,Amit,28,Bengaluru,Hr,30000,15/02/2023,karan@gmail.com
13,14,Ravi,30,Kolkata,Finance,999999,15/02/2023,neha@gmail.com
14,15,Rahul,30,Pune,Sales,45000,15/02/2023,karan@gmail.com
15,16,Pooja,28,Bangalore,It,35000,15/02/2023,vikas@gmail.com
16,17,Suraj,22,Delhi,It,35000,15/02/2023,pooja@gmail.com
17,18,Karan,25,Bengaluru,Finance,999999,15/02/2023,neha@gmail.com
18,19,Anjali,22,Delhi,It,45000,15/02/2023,ravi@gmail.com
19,20,Suraj,35,Bengaluru,It,999999,15/01/2023,neha@gmail.com
20,21,Anjali,28,Pune,Sales,45000,15/02/2023,anjali@gmail.com
21,22,Karan,30,Delhi,Hr,35000,15/02/2023,anjali@gmail.com
22,23,Amit,28,Kolkata,Sales,30000,20/03/2022,neha@gmail.com
23,24,Priya,22,Mumbai,Sales,30000,15/01/2023,vikas@gmail.com
24,25,Suraj,28,Delhi,It,999999,15/02/2023,rahul@gmail.com
25,26,Neha,28,Mumbai,Sales,40000,15/02/2023,neha@gmail.com
26,27,Pooja,28,Kolkata,Sales,999999,15/01/2023,priya@gmail.com
27,28,Priya,25,Bangalore,Sales,40000,15/02/2023,priya@gmail.com
28,29,Amit,25,Delhi,It,30000,15/01/2023,ravi@gmail.com
29,30,Suraj,30,Mumbai,It,999999,15/02/2023,anjali@gmail.com
30,31,Rahul,150,Mumbai,Finance,999999,01/04/2024,priya@gmail.com
31,32,Suraj,25,Bengaluru,Hr,40000,01/04/2024,vikas@gmail.com
32,33,Amit,25,Delhi,Finance,40000,15/01/2023,priya@gmail.com
33,34,Priya,30,Pune,Finance,35000,01/04/2024,rahul@gmail.com
34,35,Neha,150,Mumbai,Finance,30000,01/04/2024,anjali@gmail.com
35,36,Suraj,22,Pune,Finance,25000,15/01/2023,priya@gmail.com
36,37,Rahul,28,Kolkata,Finance,40000,01/04/2024,amit@gmail.com
37,38,Rahul,28,Delhi,Finance,45000,01/04/2024,neha@gmail.com
38,39,Pooja,150,Delhi,It,45000,15/02/2023,amit@gmail.com
39,40,Karan,22,Bangalore,Sales,25000,15/02/2023,vikas@gmail.com
40,41,Anjali,28,Delhi,Sales,30000,15/02/2023,suraj@gmail.com
41,42,Karan,25,Mumbai,Finance,30000,15/02/2023,priya@gmail.com
42,43,Karan,22,Pune,Sales,40000,15/02/2023,karan@gmail.com
43,44,Karan,28,Mumbai,It,40000,15/02/2023,neha@gmail.com
44,45,Pooja,28,Mumbai,Finance,40000,15/01/2023,amit@gmail.com
45,46,Vikas,25,Delhi,Sales,40000,15/02/2023,neha@gmail.com
46,47,Rahul,28,Delhi,It,40000,20/03/2022,rahul@gmail.com
47,48,Vikas,35,Pune,Finance,25000,15/02/2023,anjali@gmail.com
48,49,Neha,25,Delhi,Hr,30000,15/01/2023,anjali@gmail.com
49,50,Rahul,35,Mumbai,Sales,40000,15/02/2023,ravi@gmail.com
50,51,Priya,35,Pune,Finance,45000,15/01/2023,suraj@gmail.com
51,52,Pooja,35,Delhi,Sales,40000,15/02/2023,neha@gmail.com
52,53,Rahul,150,Pune,It,40000,15/02/2023,amit@gmail.com
53,54,Suraj,25,Delhi,Sales,25000,20/03/2022,karan@gmail.com
54,55,Anjali,28,Bengaluru,It,25000,20/03/2022,ravi@gmail.com
55,6,Suraj,28,Delhi,Hr,40000,15/02/2023,neha@gmail.com
56,11,Suraj,28,Pune,It,40000,15/02/2023,vikas@gmail.com
57,21,Anjali,28,Pune,Sales,45000,15/02/2023,anjali@gmail.com
58,59,Neha,28,Delhi,Finance,25000,01/04/2024,priya@gmail.com
59,60,Priya,150,Bangalore,Hr,40000,15/02/2023,amit@gmail.com