In [26]:
import numpy as np
import pandas as pd

In [28]:
df = pd.read_excel(r"C:\Users\Anish Kumar\Downloads\Pandas_Data_S.xlsx")

In [29]:
df

,OrderID,Date,Customer,City,Product,Category,Qty,UnitPrice,Sales,Email,Phone,Salesperson,Channel,PaymentStatus,Region
0,ORD1001,2024-01-01 00:00:00.000,Ankit Verma,Pune,Webcam,Accessories,8,2499,19992,ankit.verma@gmail.com,9692674377,Rahul,ONLine,Pending,West
1,ORD1002,2024-01-02 11:06:36.794,Pooja Kumar,Hyderabad,Monitor,Electronics,5,499,2495,pooja.kumar@gmail.com,9958092638,Rahul,ONLine,paid,East
2,ORD1003,2024-01-03 22:13:13.587,Ravi Sharma,Kolkata,Mouse,Accessories,4,49999,199996,ravi.sharma@gmail.com,9198941367,Rahul,Online,Cancelled,South
3,ORD1004,2024-01-05 09:19:50.381,Sneha Verma,Noida,Printer,Electronics,6,4999,29994,sneha.verma@gmail.com,9935191937,Karan,Offline,Paid,South
4,ORD1005,2024-01-06 00:00:00.000,Sneha Gupta,Hyderabad,Headphones,Accessories,2,2499,4998,sneha.gupta@gmail.com,9798808687,Amit,Offline,Cancelled,West
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD1496,2025-12-25 03:33:32.826,Priya Verma,Mumbai,Tablet,Electronics,4,49999,199996,priya.verma@gmail.com,9851968526,Vikas,Online,paid,North
496,ORD1497,2025-12-26 14:40:09.619,Ankit Singh,Bengaluru,Headphones,Accessories,1,4999,4999,ankit.singh@gmail.com,9701318977,Pooja,ONLine,Cancelled,North
497,ORD1498,2025-12-28 01:46:46.413,Vikas Gupta,Noida,Headphones,Accessories,8,799,6392,vikas.gupta@gmail.com,NaN,Neha,ONLine,Paid,West
498,ORD1499,2025-12-29 12:53:23.206,Priya Sharma,Pune,Laptop,Electronics,10,4999,49990,priya.sharma@gmail.com,9866768856,Neha,Online,Cancelled,North
499,ORD1500,2025-12-31 00:00:00.000,Rahul Sharma,Gurgaon,Monitor,Electronics,6,2499,14994,rahul.sharma@gmail.com,9189334793,Vikas,Offline,Cancelled,South

In [30]:
df.head(5)

,OrderID,Date,Customer,City,Product,Category,Qty,UnitPrice,Sales,Email,Phone,Salesperson,Channel,PaymentStatus,Region
0,ORD1001,2024-01-01 00:00:00.000,Ankit Verma,Pune,Webcam,Accessories,8,2499,19992,ankit.verma@gmail.com,9692674377,Rahul,ONLine,Pending,West
1,ORD1002,2024-01-02 11:06:36.794,Pooja Kumar,Hyderabad,Monitor,Electronics,5,499,2495,pooja.kumar@gmail.com,9958092638,Rahul,ONLine,paid,East
2,ORD1003,2024-01-03 22:13:13.587,Ravi Sharma,Kolkata,Mouse,Accessories,4,49999,199996,ravi.sharma@gmail.com,9198941367,Rahul,Online,Cancelled,South
3,ORD1004,2024-01-05 09:19:50.381,Sneha Verma,Noida,Printer,Electronics,6,4999,29994,sneha.verma@gmail.com,9935191937,Karan,Offline,Paid,South
4,ORD1005,2024-01-06 00:00:00.000,Sneha Gupta,Hyderabad,Headphones,Accessories,2,2499,4998,sneha.gupta@gmail.com,9798808687,Amit,Offline,Cancelled,West

In [31]:
df.tail(5)

,OrderID,Date,Customer,City,Product,Category,Qty,UnitPrice,Sales,Email,Phone,Salesperson,Channel,PaymentStatus,Region
495,ORD1496,2025-12-25 03:33:32.826,Priya Verma,Mumbai,Tablet,Electronics,4,49999,199996,priya.verma@gmail.com,9851968526,Vikas,Online,paid,North
496,ORD1497,2025-12-26 14:40:09.619,Ankit Singh,Bengaluru,Headphones,Accessories,1,4999,4999,ankit.singh@gmail.com,9701318977,Pooja,ONLine,Cancelled,North
497,ORD1498,2025-12-28 01:46:46.413,Vikas Gupta,Noida,Headphones,Accessories,8,799,6392,vikas.gupta@gmail.com,NaN,Neha,ONLine,Paid,West
498,ORD1499,2025-12-29 12:53:23.206,Priya Sharma,Pune,Laptop,Electronics,10,4999,49990,priya.sharma@gmail.com,9866768856,Neha,Online,Cancelled,North
499,ORD1500,2025-12-31 00:00:00.000,Rahul Sharma,Gurgaon,Monitor,Electronics,6,2499,14994,rahul.sharma@gmail.com,9189334793,Vikas,Offline,Cancelled,South

In [32]:
df["Date"] = pd.to_datetime(df["Date"]).dt.strftime("%d/%m/%Y")

In [33]:
df

,OrderID,Date,Customer,City,Product,Category,Qty,UnitPrice,Sales,Email,Phone,Salesperson,Channel,PaymentStatus,Region
0,ORD1001,01/01/2024,Ankit Verma,Pune,Webcam,Accessories,8,2499,19992,ankit.verma@gmail.com,9692674377,Rahul,ONLine,Pending,West
1,ORD1002,02/01/2024,Pooja Kumar,Hyderabad,Monitor,Electronics,5,499,2495,pooja.kumar@gmail.com,9958092638,Rahul,ONLine,paid,East
2,ORD1003,03/01/2024,Ravi Sharma,Kolkata,Mouse,Accessories,4,49999,199996,ravi.sharma@gmail.com,9198941367,Rahul,Online,Cancelled,South
3,ORD1004,05/01/2024,Sneha Verma,Noida,Printer,Electronics,6,4999,29994,sneha.verma@gmail.com,9935191937,Karan,Offline,Paid,South
4,ORD1005,06/01/2024,Sneha Gupta,Hyderabad,Headphones,Accessories,2,2499,4998,sneha.gupta@gmail.com,9798808687,Amit,Offline,Cancelled,West
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD1496,25/12/2025,Priya Verma,Mumbai,Tablet,Electronics,4,49999,199996,priya.verma@gmail.com,9851968526,Vikas,Online,paid,North
496,ORD1497,26/12/2025,Ankit Singh,Bengaluru,Headphones,Accessories,1,4999,4999,ankit.singh@gmail.com,9701318977,Pooja,ONLine,Cancelled,North
497,ORD1498,28/12/2025,Vikas Gupta,Noida,Headphones,Accessories,8,799,6392,vikas.gupta@gmail.com,NaN,Neha,ONLine,Paid,West
498,ORD1499,29/12/2025,Priya Sharma,Pune,Laptop,Electronics,10,4999,49990,priya.sharma@gmail.com,9866768856,Neha,Online,Cancelled,North
499,ORD1500,31/12/2025,Rahul Sharma,Gurgaon,Monitor,Electronics,6,2499,14994,rahul.sharma@gmail.com,9189334793,Vikas,Offline,Cancelled,South

In [142]:
df.isna().sum()

OrderID          0
Date             0
Customer         0
City             0
Product          0
Category         0
Qty              0
UnitPrice        0
Sales            0
Email            0
Phone            0
Salesperson      0
Channel          0
PaymentStatus    0
Region           0
dtype: int64

--> Remove all extra space from all string column

In [131]:
for col in df.select_dtypes(include="str"):
    df[col] = df[col].str.strip()

In [138]:
for col in df.select_dtypes(include="str"):
    df[col] = df[col].str.title()

In [134]:
df["Email"] = df["Email"].str.lower()

In [140]:
# String columns
for col in df.select_dtypes(include="str"):
    df[col] = df[col].fillna("N/A")

# Integer columns
for col in df.select_dtypes(include="number"):
    df[col] = df[col].fillna(0)

In [141]:
df.head(5)

,OrderID,Date,Customer,City,Product,Category,Qty,UnitPrice,Sales,Email,Phone,Salesperson,Channel,PaymentStatus,Region
0,Ord1001,01/01/2024,Ankit Verma,Pune,Webcam,Accessories,8,2499,19992,Ankit.Verma@Gmail.Com,9692674377,Rahul,Online,Pending,West
1,Ord1002,02/01/2024,Pooja Kumar,Hyderabad,Monitor,Electronics,5,499,2495,Pooja.Kumar@Gmail.Com,9958092638,Rahul,Online,Paid,East
2,Ord1003,03/01/2024,Ravi Sharma,Kolkata,Mouse,Accessories,4,49999,199996,Ravi.Sharma@Gmail.Com,9198941367,Rahul,Online,Cancelled,South
3,Ord1004,05/01/2024,Sneha Verma,Noida,Printer,Electronics,6,4999,29994,Sneha.Verma@Gmail.Com,9935191937,Karan,Offline,Paid,South
4,Ord1005,06/01/2024,Sneha Gupta,Hyderabad,Headphones,Accessories,2,2499,4998,Sneha.Gupta@Gmail.Com,9798808687,Amit,Offline,Cancelled,West

Total duplicate rows kitni hain

In [143]:
df.duplicated().sum()

np.int64(0)

Duplicate rows ko dekhna ho

In [144]:
df[df.duplicated()]

Empty DataFrame
Columns: [OrderID, Date, Customer, City, Product, Category, Qty, UnitPrice, Sales, Email, Phone, Salesperson, Channel, PaymentStatus, Region]
Index: []

Duplicate rows remove karna ho

In [163]:
df = df.drop_duplicates()

In [161]:
df.describe()

              Qty     UnitPrice          Sales
count    8.000000      8.000000       8.000000
mean    66.899843  11526.160342   92986.890021
std    175.022830  16656.687930  168863.781204
min      1.000000    499.000000     499.000000
25%      2.966686    874.250000    3720.500000
50%      5.166000   6249.000000   35243.500000
75%      8.500000  12569.070685   72602.214043
max    500.000000  49999.000000  499990.000000