In [22]:
import pandas as pd
import numpy as np

### Basic Data Inspection

1. How do you check the shape of a DataFrame?

In [3]:
df = pd.read_excel(r"C:\Users\Anish Kumar\Downloads\Pandas_Data_S.xlsx")

2. How do you check the column names and data types of a DataFrame?

In [4]:
df.head(5)

,OrderID,Date,Customer,City,Product,Category,Qty,UnitPrice,Sales,Email,Phone,Salesperson,Channel,PaymentStatus,Region
0,ORD1001,2024-01-01 00:00:00.000,Ankit Verma,Pune,Webcam,Accessories,8,2499,19992,ankit.verma@gmail.com,9692674377,Rahul,ONLine,Pending,West
1,ORD1002,2024-01-02 11:06:36.794,Pooja Kumar,Hyderabad,Monitor,Electronics,5,499,2495,pooja.kumar@gmail.com,9958092638,Rahul,ONLine,paid,East
2,ORD1003,2024-01-03 22:13:13.587,Ravi Sharma,Kolkata,Mouse,Accessories,4,49999,199996,ravi.sharma@gmail.com,9198941367,Rahul,Online,Cancelled,South
3,ORD1004,2024-01-05 09:19:50.381,Sneha Verma,Noida,Printer,Electronics,6,4999,29994,sneha.verma@gmail.com,9935191937,Karan,Offline,Paid,South
4,ORD1005,2024-01-06 00:00:00.000,Sneha Gupta,Hyderabad,Headphones,Accessories,2,2499,4998,sneha.gupta@gmail.com,9798808687,Amit,Offline,Cancelled,West

In [6]:
df.tail(5)

,OrderID,Date,Customer,City,Product,Category,Qty,UnitPrice,Sales,Email,Phone,Salesperson,Channel,PaymentStatus,Region
495,ORD1496,2025-12-25 03:33:32.826,Priya Verma,Mumbai,Tablet,Electronics,4,49999,199996,priya.verma@gmail.com,9851968526,Vikas,Online,paid,North
496,ORD1497,2025-12-26 14:40:09.619,Ankit Singh,Bengaluru,Headphones,Accessories,1,4999,4999,ankit.singh@gmail.com,9701318977,Pooja,ONLine,Cancelled,North
497,ORD1498,2025-12-28 01:46:46.413,Vikas Gupta,Noida,Headphones,Accessories,8,799,6392,vikas.gupta@gmail.com,NaN,Neha,ONLine,Paid,West
498,ORD1499,2025-12-29 12:53:23.206,Priya Sharma,Pune,Laptop,Electronics,10,4999,49990,priya.sharma@gmail.com,9866768856,Neha,Online,Cancelled,North
499,ORD1500,2025-12-31 00:00:00.000,Rahul Sharma,Gurgaon,Monitor,Electronics,6,2499,14994,rahul.sharma@gmail.com,9189334793,Vikas,Offline,Cancelled,South

In [7]:
df.columns

Index(['OrderID', 'Date', 'Customer', 'City', 'Product', 'Category', 'Qty',
       'UnitPrice', 'Sales', 'Email', 'Phone', 'Salesperson', 'Channel',
       'PaymentStatus', 'Region'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        500 non-null    str
 1   Date           500 non-null    datetime64[us]
 2   Customer       492 non-null    str
 3   City           492 non-null    str
 4   Product        500 non-null    str
 5   Category       500 non-null    str
 6   Qty            500 non-null    int64
 7   UnitPrice      500 non-null    int64
 8   Sales          500 non-null    int64
 9   Email          493 non-null    str
 10  Phone          492 non-null    str
 11  Salesperson    492 non-null    str
 12  Channel        500 non-null    str
 13  PaymentStatus  500 non-null    str
 14  Region         500 non-null    str
dtypes: datetime64[us](1), int64(3), str(11)
memory usage: 58.7 KB

3. How do you find missing values in a DataFrame?

In [13]:
df.isna().sum()

OrderID          0
Date             0
Customer         8
City             8
Product          0
Category         0
Qty              0
UnitPrice        0
Sales            0
Email            7
Phone            8
Salesperson      8
Channel          0
PaymentStatus    0
Region           0
dtype: int64

4. How do you check the number of null values in each column?

In [10]:
df.isna().sum()

OrderID          0
Date             0
Customer         8
City             8
Product          0
Category         0
Qty              0
UnitPrice        0
Sales            0
Email            7
Phone            8
Salesperson      8
Channel          0
PaymentStatus    0
Region           0
dtype: int64

5. How do you find duplicate rows in a DataFrame?

In [16]:
df[df.duplicated()]

Empty DataFrame
Columns: [OrderID, Date, Customer, City, Product, Category, Qty, UnitPrice, Sales, Email, Phone, Salesperson, Channel, PaymentStatus, Region]
Index: []

6. How do you remove duplicate rows from a DataFrame?

In [18]:
df.drop_duplicates()

,OrderID,Date,Customer,City,Product,Category,Qty,UnitPrice,Sales,Email,Phone,Salesperson,Channel,PaymentStatus,Region
0,ORD1001,2024-01-01 00:00:00.000,Ankit Verma,Pune,Webcam,Accessories,8,2499,19992,ankit.verma@gmail.com,9692674377,Rahul,ONLine,Pending,West
1,ORD1002,2024-01-02 11:06:36.794,Pooja Kumar,Hyderabad,Monitor,Electronics,5,499,2495,pooja.kumar@gmail.com,9958092638,Rahul,ONLine,paid,East
2,ORD1003,2024-01-03 22:13:13.587,Ravi Sharma,Kolkata,Mouse,Accessories,4,49999,199996,ravi.sharma@gmail.com,9198941367,Rahul,Online,Cancelled,South
3,ORD1004,2024-01-05 09:19:50.381,Sneha Verma,Noida,Printer,Electronics,6,4999,29994,sneha.verma@gmail.com,9935191937,Karan,Offline,Paid,South
4,ORD1005,2024-01-06 00:00:00.000,Sneha Gupta,Hyderabad,Headphones,Accessories,2,2499,4998,sneha.gupta@gmail.com,9798808687,Amit,Offline,Cancelled,West
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD1496,2025-12-25 03:33:32.826,Priya Verma,Mumbai,Tablet,Electronics,4,49999,199996,priya.verma@gmail.com,9851968526,Vikas,Online,paid,North
496,ORD1497,2025-12-26 14:40:09.619,Ankit Singh,Bengaluru,Headphones,Accessories,1,4999,4999,ankit.singh@gmail.com,9701318977,Pooja,ONLine,Cancelled,North
497,ORD1498,2025-12-28 01:46:46.413,Vikas Gupta,Noida,Headphones,Accessories,8,799,6392,vikas.gupta@gmail.com,NaN,Neha,ONLine,Paid,West
498,ORD1499,2025-12-29 12:53:23.206,Priya Sharma,Pune,Laptop,Electronics,10,4999,49990,priya.sharma@gmail.com,9866768856,Neha,Online,Cancelled,North
499,ORD1500,2025-12-31 00:00:00.000,Rahul Sharma,Gurgaon,Monitor,Electronics,6,2499,14994,rahul.sharma@gmail.com,9189334793,Vikas,Offline,Cancelled,South

### Missing Data

7. How do you handle missing values using fillna()?

8. How do you fill missing values with the mean?

9. Missing values ko median se kaise fill karenge?

10. How do you remove rows containing missing values using dropna()?

11. How do you handle null values in a specific column?


🟠 Level 3 — Text Cleaning

12. Text columns se extra spaces kaise remove karenge?

13. Uppercase/lowercase ko standardize kaise karenge?

14. "Delhi", "delhi", " DELHI " ko same format me kaise convert karenge?

15. Column ke andar spelling/misspelled values ko kaise replace karenge?

16. Special characters ko text se kaise remove karenge?

17. Email addresses ko validate/clean kaise karenge?

🔵 Level 4 — Data Types

18. Numbers stored as text ko numeric me kaise convert karenge?

19. Date column ko datetime me kaise convert karenge?

20. Invalid dates ko kaise handle karenge?

21. pd.to_numeric() ka use kab karte hain?

22. pd.to_datetime() ka use kab karte hain?

🟣 Level 5 — Duplicates

23. Duplicate OrderID kaise find karenge?

24. Duplicate CustomerID kaise remove karenge?

25. Duplicate records me first/last record kaise keep karenge?

🔴 Level 6 — Outliers & Invalid Data

26. Negative Sales values kaise find karenge?

27. Invalid Age values jaise -5 ya 150 kaise find karenge?

28. Sales me outliers kaise identify karenge?

29. Invalid phone numbers kaise find karenge?

30. Invalid email IDs kaise identify karenge?