In [1]:
import pyodbc
import pandas as pd

In [3]:
conn = pyodbc.connect(
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=localhost\\SQLEXPRESS;"
    "DATABASE=Excel;"
    "UID=AS;"
    "PWD=Sur7aj6@;"
    "Encrypt=yes;"
    "TrustServerCertificate=yes;"
)

print("✅ SQL Server Connected Successfully!")

✅ SQL Server Connected Successfully!

In [6]:
df = pd.read_sql("SELECT * FROM Employee_Data", conn)

C:\Users\Anish Kumar\AppData\Local\Temp\ipykernel_29572\2263573685.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM Employee_Data", conn)

In [8]:
df.head(5)

  Employee_ID Employee_Name  Department Employee_City  Salary
0       E0001  Aarav Sharma          HR         Delhi   68617
1       E0002  Vivaan Kumar  Operations     Bengaluru   34695
2       E0003  Aditya Singh  Operations       Chennai   60380
3       E0004   Arjun Verma     Support       Kolkata   44763
4       E0005   Rahul Gupta       Sales         Delhi   51513

In [17]:
df.shape

(500, 5)

In [18]:
df.columns

Index(['Employee_ID', 'Employee_Name', 'Department', 'Employee_City',
       'Salary'],
      dtype='str')

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employee_ID    500 non-null    str
 1   Employee_Name  500 non-null    str
 2   Department     500 non-null    str
 3   Employee_City  500 non-null    str
 4   Salary         500 non-null    int64
dtypes: int64(1), str(4)
memory usage: 19.7 KB

In [9]:
cd = pd.read_sql("SELECT * FROM Customer_Data", conn)

C:\Users\Anish Kumar\AppData\Local\Temp\ipykernel_29572\2193415839.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cd = pd.read_sql("SELECT * FROM Customer_Data", conn)

In [10]:
cd.head(5)

  Customer_ID Customer_Name       City Gender  Age
0    CUST0001  Aarav Sharma     Mumbai   Male   35
1    CUST0002  Vivaan Kumar    Gurgaon   Male   26
2    CUST0003  Aditya Singh     Mumbai   Male   55
3    CUST0004   Arjun Verma  Hyderabad   Male   19
4    CUST0005   Rahul Gupta     Mumbai   Male   32

In [29]:
cd.shape

(500, 5)

In [30]:
cd.columns

Index(['Customer_ID', 'Customer_Name', 'City', 'Gender', 'Age'], dtype='str')

In [31]:
cd.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    500 non-null    str
 1   Customer_Name  500 non-null    str
 2   City           500 non-null    str
 3   Gender         500 non-null    str
 4   Age            500 non-null    int64
dtypes: int64(1), str(4)
memory usage: 19.7 KB

In [11]:
od = pd.read_sql("SELECT * FROM Order_data", conn)

C:\Users\Anish Kumar\AppData\Local\Temp\ipykernel_29572\623865056.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  od = pd.read_sql("SELECT * FROM Order_data", conn)

In [13]:
od.head(5)

,Order_ID,Order_Date,Customer_ID,Product_ID,Employee_ID,Quantity,Sales,Order_Status,Channel,Payment_Method
0,ORD0001,2025-07-29,CUST0397,P0174,E0348,10,7363,Cancelled,Distributor,UPI
1,ORD0002,2025-02-03,CUST0169,P0049,E0286,7,37743,Pending,Distributor,Card
2,ORD0003,2025-06-20,CUST0042,P0299,E0340,3,46351,Pending,Distributor,Bank Transfer
3,ORD0004,2025-03-08,CUST0305,P0363,E0481,2,41077,Cancelled,Store,UPI
4,ORD0005,2025-03-07,CUST0344,P0360,E0425,9,12749,Cancelled,Distributor,Bank Transfer

In [22]:
od.shape

(500, 10)

In [23]:
od.columns

Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Employee_ID',
       'Quantity', 'Sales', 'Order_Status', 'Channel', 'Payment_Method'],
      dtype='str')

In [28]:
od.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        500 non-null    str
 1   Order_Date      500 non-null    object
 2   Customer_ID     500 non-null    str
 3   Product_ID      500 non-null    str
 4   Employee_ID     500 non-null    str
 5   Quantity        500 non-null    int64
 6   Sales           500 non-null    int64
 7   Order_Status    500 non-null    str
 8   Channel         500 non-null    str
 9   Payment_Method  500 non-null    str
dtypes: int64(2), object(1), str(7)
memory usage: 39.2+ KB

In [14]:
pd = pd.read_sql("SELECT * FROM Product_Data", conn)

C:\Users\Anish Kumar\AppData\Local\Temp\ipykernel_29572\723357632.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd = pd.read_sql("SELECT * FROM Product_Data", conn)

In [16]:
pd.head(5)

  Product_ID Product_Name         Category  Unit_Price Product_Status
0      P0001        Shirt  Office Supplies       49214       Inactive
1      P0002          Pen        Furniture       12251         Active
2      P0003     Keyboard        Furniture       43586       Inactive
3      P0004      Monitor        Furniture       11138       Inactive
4      P0005      Monitor      Electronics        4380       Inactive

In [25]:
pd.shape

(500, 5)

In [26]:
pd.columns

Index(['Product_ID', 'Product_Name', 'Category', 'Unit_Price',
       'Product_Status'],
      dtype='str')

In [27]:
pd.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Product_ID      500 non-null    str
 1   Product_Name    500 non-null    str
 2   Category        500 non-null    str
 3   Unit_Price      500 non-null    int64
 4   Product_Status  500 non-null    str
dtypes: int64(1), str(4)
memory usage: 19.7 KB

In [32]:
print("Customer:", df.columns.tolist())
print("Employee:", cd.columns.tolist())
print("Order:", od.columns.tolist())
print("Product:", pd.columns.tolist())

Customer: ['Employee_ID', 'Employee_Name', 'Department', 'Employee_City', 'Salary']
Employee: ['Customer_ID', 'Customer_Name', 'City', 'Gender', 'Age']
Order: ['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Employee_ID', 'Quantity', 'Sales', 'Order_Status', 'Channel', 'Payment_Method']
Product: ['Product_ID', 'Product_Name', 'Category', 'Unit_Price', 'Product_Status']

1. 4 table ,me sa,e lam kiya hu

In [44]:
cd["Customer_ID"].unique()

<StringArray>
['CUST0001', 'CUST0002', 'CUST0003', 'CUST0004', 'CUST0005', 'CUST0006',
 'CUST0007', 'CUST0008', 'CUST0009', 'CUST0010',
 ...
 'CUST0491', 'CUST0492', 'CUST0493', 'CUST0494', 'CUST0495', 'CUST0496',
 'CUST0497', 'CUST0498', 'CUST0499', 'CUST0500']
Length: 500, dtype: str

In [41]:
cd

    Customer_ID   Customer_Name       City  Gender  Age
0      CUST0001    Aarav Sharma     Mumbai    Male   35
1      CUST0002    Vivaan Kumar    Gurgaon    Male   26
2      CUST0003    Aditya Singh     Mumbai    Male   55
3      CUST0004     Arjun Verma  Hyderabad    Male   19
4      CUST0005     Rahul Gupta     Mumbai    Male   32
..          ...             ...        ...     ...  ...
495    CUST0496    Naveen Patel     Mumbai  Female   23
496    CUST0497     Gaurav Jain    Kolkata    Male   20
497    CUST0498     Sumit Gupta    Gurgaon  Female   46
498    CUST0499    Vivek Tiwari    Kolkata    Male   41
499    CUST0500  Rajiv Malhotra  Bengaluru  Female   42

[500 rows x 5 columns]