In [1]:
import pandas as pd
import pyodbc
import numpy as np

In [4]:
sql_conn = pyodbc.connect(
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=localhost\\SQLEXPRESS;"
    "DATABASE=Excel;"
    "UID=AS;"
    "PWD=Sur7aj6@;"
    "Encrypt=yes;"
    "TrustServerCertificate=yes;"
)
print("SQL Server Connected Successfully!")

SQL Server Connected Successfully!

In [5]:
df = pd.read_sql("SELECT * FROM Sales_Data", sql_conn)

C:\Users\Anish Kumar\AppData\Local\Temp\ipykernel_24192\470251366.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM Sales_Data", sql_conn)

In [6]:
df.head(5)

,OrderID,OrderDate,Customer,City,Product,Category,Quantity,UnitPrice,Sales,Salesperson,Region,PaymentMode
0,ORD10001,2025-04-19,Customer_001,Delhi,Printer,Office,7,8500.0,59500.0,Anjali,North,Cash
1,ORD10002,2025-03-16,Customer_002,Bangalore,Keyboard,Accessories,4,1800.0,7200.0,Vikas,South,Credit Card
2,ORD10003,2025-05-26,Customer_003,Delhi,Chair,Furniture,7,7000.0,49000.0,Neha,North,Debit Card
3,ORD10004,2025-05-08,Customer_004,Delhi,Mouse,Accessories,6,900.0,5400.0,Priya,North,Net Banking
4,ORD10005,2025-02-11,Customer_005,Bangalore,Printer,Office,2,8500.0,17000.0,Vikas,South,Cash

In [7]:
df.tail(5)

,OrderID,OrderDate,Customer,City,Product,Category,Quantity,UnitPrice,Sales,Salesperson,Region,PaymentMode
495,ORD10496,2025-12-01,Customer_496,Noida,Laptop,Electronics,6,55000.0,330000.0,Neha,North,Debit Card
496,ORD10497,2026-02-22,Customer_497,Gurgaon,Printer,Office,4,8500.0,34000.0,Priya,North,Cash
497,ORD10498,2025-10-22,Customer_498,Delhi,Printer,Office,2,8500.0,17000.0,Pooja,North,Cash
498,ORD10499,2026-01-06,Customer_499,Pune,Desk,Furniture,2,11000.0,22000.0,Vikas,West,Credit Card
499,ORD10500,2025-07-05,Customer_500,Noida,Headphones,Accessories,5,2500.0,12500.0,Pooja,North,UPI

In [8]:
df.columns

Index(['OrderID', 'OrderDate', 'Customer', 'City', 'Product', 'Category',
       'Quantity', 'UnitPrice', 'Sales', 'Salesperson', 'Region',
       'PaymentMode'],
      dtype='str')

In [9]:
df.describe()

         Quantity     UnitPrice          Sales
count  500.000000    500.000000     500.000000
mean     4.098000  14667.000000   57241.000000
std      2.031909  16466.019269   75252.935542
min      1.000000    900.000000     900.000000
25%      2.000000   2500.000000    9000.000000
50%      4.000000   8500.000000   35000.000000
75%      6.000000  18000.000000   66000.000000
max      7.000000  55000.000000  385000.000000

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderID      500 non-null    str
 1   OrderDate    500 non-null    object
 2   Customer     500 non-null    str
 3   City         500 non-null    str
 4   Product      500 non-null    str
 5   Category     500 non-null    str
 6   Quantity     500 non-null    int64
 7   UnitPrice    500 non-null    float64
 8   Sales        500 non-null    float64
 9   Salesperson  500 non-null    str
 10  Region       500 non-null    str
 11  PaymentMode  500 non-null    str
dtypes: float64(2), int64(1), object(1), str(8)
memory usage: 47.0+ KB

In [11]:
df.dtypes

OrderID            str
OrderDate       object
Customer           str
City               str
Product            str
Category           str
Quantity         int64
UnitPrice      float64
Sales          float64
Salesperson        str
Region             str
PaymentMode        str
dtype: object

In [12]:
df.isna().sum()

OrderID        0
OrderDate      0
Customer       0
City           0
Product        0
Category       0
Quantity       0
UnitPrice      0
Sales          0
Salesperson    0
Region         0
PaymentMode    0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.drop_duplicates()

,OrderID,OrderDate,Customer,City,Product,Category,Quantity,UnitPrice,Sales,Salesperson,Region,PaymentMode
0,ORD10001,2025-04-19,Customer_001,Delhi,Printer,Office,7,8500.0,59500.0,Anjali,North,Cash
1,ORD10002,2025-03-16,Customer_002,Bangalore,Keyboard,Accessories,4,1800.0,7200.0,Vikas,South,Credit Card
2,ORD10003,2025-05-26,Customer_003,Delhi,Chair,Furniture,7,7000.0,49000.0,Neha,North,Debit Card
3,ORD10004,2025-05-08,Customer_004,Delhi,Mouse,Accessories,6,900.0,5400.0,Priya,North,Net Banking
4,ORD10005,2025-02-11,Customer_005,Bangalore,Printer,Office,2,8500.0,17000.0,Vikas,South,Cash
...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD10496,2025-12-01,Customer_496,Noida,Laptop,Electronics,6,55000.0,330000.0,Neha,North,Debit Card
496,ORD10497,2026-02-22,Customer_497,Gurgaon,Printer,Office,4,8500.0,34000.0,Priya,North,Cash
497,ORD10498,2025-10-22,Customer_498,Delhi,Printer,Office,2,8500.0,17000.0,Pooja,North,Cash
498,ORD10499,2026-01-06,Customer_499,Pune,Desk,Furniture,2,11000.0,22000.0,Vikas,West,Credit Card
499,ORD10500,2025-07-05,Customer_500,Noida,Headphones,Accessories,5,2500.0,12500.0,Pooja,North,UPI

In [15]:
df["OrderDate"] = pd.to_datetime(df["OrderDate"],format="mixed").dt.strftime("%d/%m/%Y")

In [16]:
df

,OrderID,OrderDate,Customer,City,Product,Category,Quantity,UnitPrice,Sales,Salesperson,Region,PaymentMode
0,ORD10001,19/04/2025,Customer_001,Delhi,Printer,Office,7,8500.0,59500.0,Anjali,North,Cash
1,ORD10002,16/03/2025,Customer_002,Bangalore,Keyboard,Accessories,4,1800.0,7200.0,Vikas,South,Credit Card
2,ORD10003,26/05/2025,Customer_003,Delhi,Chair,Furniture,7,7000.0,49000.0,Neha,North,Debit Card
3,ORD10004,08/05/2025,Customer_004,Delhi,Mouse,Accessories,6,900.0,5400.0,Priya,North,Net Banking
4,ORD10005,11/02/2025,Customer_005,Bangalore,Printer,Office,2,8500.0,17000.0,Vikas,South,Cash
...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD10496,01/12/2025,Customer_496,Noida,Laptop,Electronics,6,55000.0,330000.0,Neha,North,Debit Card
496,ORD10497,22/02/2026,Customer_497,Gurgaon,Printer,Office,4,8500.0,34000.0,Priya,North,Cash
497,ORD10498,22/10/2025,Customer_498,Delhi,Printer,Office,2,8500.0,17000.0,Pooja,North,Cash
498,ORD10499,06/01/2026,Customer_499,Pune,Desk,Furniture,2,11000.0,22000.0,Vikas,West,Credit Card
499,ORD10500,05/07/2025,Customer_500,Noida,Headphones,Accessories,5,2500.0,12500.0,Pooja,North,UPI

In [17]:
np.random.seed(42)
first_names = [
    "Aarav", "Aditi", "Aditya", "Akash", "Aman", "Amit", "Ananya", "Anjali", "Ankit", "Arjun",
    "Ashish", "Ayush", "Deepak", "Divya", "Gaurav", "Isha", "Karan", "Kavita", "Kunal", "Manish",
    "Meera", "Mohit", "Neha", "Nikhil", "Nisha", "Pankaj", "Pooja", "Prakash", "Priya", "Rahul",
    "Raj", "Rajat", "Rakesh", "Ravi", "Riya", "Rohit", "Sachin", "Sakshi", "Sameer", "Sandeep",
    "Sanjay", "Shivam", "Shreya", "Simran", "Sonali", "Sourav", "Sunil", "Swati", "Tarun", "Vikas",
    "Vikram", "Vineet", "Vishal", "Yash", "Yogesh", "Varun", "Komal", "Muskan", "Naveen", "Nitin",
    "Pawan", "Pranav", "Raghav", "Rajat", "Ramesh", "Rani", "Rashmi", "Reena", "Renu", "Richa",
    "Ritu", "Riya", "Rupali", "Sahil", "Sakshi", "Salman", "Samir", "Sana", "Sanjana", "Sarika",
    "Seema", "Shalini", "Shankar", "Shikha", "Shruti", "Siddharth", "Sneha", "Sonia", "Srishti", "Sumit",
    "Suraj", "Suresh", "Tanisha", "Tanya", "Tanu", "Tushar", "Uday", "Uma", "Vaibhav", "Varsha",
    "Vedant", "Veer", "Vijay", "Vinay", "Vivek", "Waseem", "Zaid", "Zoya", "Abhay", "Abhishek",
    "Adarsh", "Ajay", "Ajit", "Alok", "Amar", "Amisha", "Amol", "Anand", "Anil", "Anirudh",
    "Anisha", "Ansh", "Anshu", "Antara", "Apoorva", "Archana", "Arnav", "Arpita", "Aryan", "Ashok",
    "Avinash", "Bharat", "Bhavna", "Bhavesh", "Bhumika", "Chetan", "Chirag", "Darshan", "Daya", "Dev",
    "Devansh", "Dhanush", "Diksha", "Dinesh", "Ekta", "Farhan", "Faisal", "Garima", "Geeta", "Harish",
    "Harsh", "Harsha", "Himanshu", "Hina", "Inder", "Ishaan", "Jagdish", "Jatin", "Jaya", "Jayant",
    "Jeevan", "Jyoti", "Kabir", "Kajal", "Kamal", "Kanika", "Kartik", "Kashish", "Kavya", "Khushi",
    "Kirti", "Krishna", "Kriti", "Kunal", "Lakshay", "Lalit", "Lavanya", "Lokesh", "Madhav", "Madhu",
    "Mahesh", "Mahi", "Malini", "Mamta", "Mansi", "Mayank", "Meena", "Mihir", "Milan", "Mira",
    "Mohan", "Monika", "Mukesh", "Naina", "Naksh", "Namita", "Nandini", "Naresh", "Navin", "Nayan",
    "Neel", "Neelam", "Neeraj", "Nidhi", "Nikita", "Nilesh", "Nirmal", "Nitin", "Nivedita", "Ojas",
    "Om", "Palak", "Parag", "Pari", "Parth", "Payal", "Piyush", "Preeti", "Pritam", "Purva",
    "Rachit", "Radha", "Ragini", "Rajeev", "Rajesh", "Rajiv", "Ranjit", "Rashid", "Ravi", "Rekha",
    "Ritesh", "Rohini", "Roshan", "Ruchi", "Sachin", "Sagar", "Saloni", "Sameera", "Sanjay", "Santosh",
    "Saroj", "Saurabh", "Shahid", "Shailesh", "Shanaya", "Shashank", "Shekhar", "Shivani", "Shubham", "Shweta",
    "Siddhi", "Smita", "Sonal", "Sonam", "Sourabh", "Sparsh", "Suman", "Sunita", "Surabhi", "Sushant",
    "Sushil", "Swara", "Tanuja", "Tejas", "Tina", "Trisha", "Ujjwal", "Umesh", "Upasana", "Utkarsh",
    "Vandana", "Varun", "Vasu", "Vatsal", "Vidhi", "Vidya", "Vikas", "Vimal", "Vineeta", "Vipul",
    "Vishakha", "Vishnu", "Yamini", "Yatin", "Yuvraj", "Zara", "Ayesha", "Bilal", "Danish", "Imran",
    "Irfan", "Javed", "Kashif", "Nadeem", "Nazia", "Rizwan", "Saif", "Shabnam", "Shadab", "Shahnawaz",
    "Shoaib", "Sohail", "Tabassum", "Wasim", "Aaliya", "Aamir", "Afreen", "Alisha", "Armaan", "Asif",
    "Azhar", "Faizan", "Hammad", "Haseeb", "Humaira", "Kiran", "Lubna", "Mariam", "Mehreen", "Nusrat",
    "Rafia", "Rehan", "Rubina", "Saba", "Sabina", "Sadia", "Sahil", "Samina", "Shakir", "Shazia",
    "Aakash", "Aarohi", "Aastha", "Aayush", "Aditi", "Aishwarya", "Akansha", "Akshat", "Akshara", "Amrita",
    "Apoorv", "Aradhya", "Bharti", "Charu", "Damini", "Esha", "Gauri", "Ishita", "Jhanvi", "Juhi",
    "Kanchan", "Karishma", "Kriti", "Madhuri", "Mahima", "Manisha", "Manya", "Mitali", "Nandita", "Navya",
    "Niharika", "Pallavi", "Poonam", "Pragya", "Preeti", "Radhika", "Rajni", "Rashika", "Raveena", "Riddhi",
    "Roshni", "Sakina", "Salma", "Sapna", "Shanvi", "Shivangi", "Shreya", "Sonali", "Tanvi", "Tara",
    "Tulika", "Vaishali", "Vani", "Vasudha", "Veda", "Vidushi", "Yashika", "Zeenat", "Aarti", "Aarav",
    "Abhinav", "Advik", "Ahan", "Akhil", "Anmol", "Arpit", "Atharv", "Dhruv", "Harshit", "Hrithik",
    "Keshav", "Krish", "Laksh", "Manav", "Mudit", "Naman", "Nakul", "Parveen", "Prateek", "Raghav",
    "Ranveer", "Rituraj", "Shivam", "Shrey", "Tanish", "Tanu", "Utsav", "Vansh", "Varad", "Vivaan",
    "Yuvika", "Zubin", "Aarush", "Abeer", "Adit", "Aditiya", "Anshul", "Avni", "Bhavya", "Dhara",
    "Harshita", "Ishika", "Janvi", "Kashvi", "Kiana", "Myra", "Navneet", "Nitya", "Pari", "Prisha",
    "Rhea", "Saanvi", "Samaira", "Shanaya", "Siya", "Tia", "Vanya", "Zoya", "Ayesha", "Diya",
    "Ishani", "Mahi", "Mishka", "Ruhani", "Suhani", "Anvi", "Aarna", "Kiara", "Aadhya", "Aaradhya",
    "Aahana", "Anvika", "Charvi", "Devika", "Ira", "Jiya", "Kaira", "Navya", "Nyla", "Pranavi",
    "Riddhima", "Samaira", "Sharanya", "Shivanya", "Suhana", "Tanishka", "Vamika", "Vritika", "Yashvi", "Ziva"
]

last_names = [
    "Sharma", "Verma", "Kumar", "Singh", "Gupta",
    "Yadav", "Mishra", "Pandey", "Tiwari", "Jha",
    "Chauhan", "Rajput", "Thakur", "Sinha", "Prasad",
    "Agarwal", "Bansal", "Jain", "Sahu", "Saxena",
    "Srivastava", "Tripathi", "Dubey", "Dwivedi", "Shukla",
    "Pathak", "Joshi", "Mehta", "Shah", "Patel",
    "Desai", "Rao", "Reddy", "Naidu", "Iyer",
    "Nair", "Menon", "Pillai", "Kapoor", "Malhotra",
    "Arora", "Khanna", "Chopra", "Bhatia", "Sethi",
    "Ahuja", "Chawla", "Goyal", "Mittal", "Goel",
    "Kohli", "Bhardwaj", "Bhatt", "Rawat", "Negi",
    "Bisht", "Rana", "Dixit", "Prajapati", "Maurya",
    "Kushwaha", "Mandal", "Das", "Dutta", "Ghosh",
    "Bose", "Banerjee", "Mukherjee", "Chatterjee", "Sen",
    "Roy", "Pal", "Sarkar", "Nath", "Dey",
    "Soni", "Gupta", "Khatri", "Wadhwa", "Tandon",
    "Bajaj", "Singhal", "Aggarwal", "Puri", "Batra",
    "Khurana", "Anand", "Vohra", "Sachdeva", "Luthra",
    "Madan", "Bedi", "Talwar", "Oberoi", "Handa",
    "Mathur", "Kulkarni", "Deshmukh", "Patil", "More"
]
df["Customer"] = (
    np.random.choice(first_names, size=len(df)) + " " + np.random.choice(last_names, size=len(df))
)

In [18]:
df.head(10)

,OrderID,OrderDate,Customer,City,Product,Category,Quantity,UnitPrice,Sales,Salesperson,Region,PaymentMode
0,ORD10001,19/04/2025,Vijay Patil,Delhi,Printer,Office,7,8500.0,59500.0,Anjali,North,Cash
1,ORD10002,16/03/2025,Myra Goel,Bangalore,Keyboard,Accessories,4,1800.0,7200.0,Vikas,South,Credit Card
2,ORD10003,26/05/2025,Jhanvi Shukla,Delhi,Chair,Furniture,7,7000.0,49000.0,Neha,North,Debit Card
3,ORD10004,08/05/2025,Vandana Dwivedi,Delhi,Mouse,Accessories,6,900.0,5400.0,Priya,North,Net Banking
4,ORD10005,11/02/2025,Zaid Thakur,Bangalore,Printer,Office,2,8500.0,17000.0,Vikas,South,Cash
5,ORD10006,22/12/2025,Riya Maurya,Mumbai,Tablet,Electronics,7,18000.0,126000.0,Rahul,West,Credit Card
6,ORD10007,10/02/2025,Milan Mishra,Patna,Headphones,Accessories,1,2500.0,2500.0,Pooja,East,Cash
7,ORD10008,03/02/2025,Meera Rana,Delhi,Printer,Office,4,8500.0,34000.0,Vikas,North,Debit Card
8,ORD10009,17/01/2025,Vijay Nair,Bangalore,Chair,Furniture,3,7000.0,21000.0,Rohit,South,Cash
9,ORD10010,02/06/2025,Ansh Sethi,Pune,Mouse,Accessories,2,900.0,1800.0,Amit,West,UPI

In [19]:
df.tail(5)

,OrderID,OrderDate,Customer,City,Product,Category,Quantity,UnitPrice,Sales,Salesperson,Region,PaymentMode
495,ORD10496,01/12/2025,Sameer Singh,Noida,Laptop,Electronics,6,55000.0,330000.0,Neha,North,Debit Card
496,ORD10497,22/02/2026,Vamika Bisht,Gurgaon,Printer,Office,4,8500.0,34000.0,Priya,North,Cash
497,ORD10498,22/10/2025,Khushi Shukla,Delhi,Printer,Office,2,8500.0,17000.0,Pooja,North,Cash
498,ORD10499,06/01/2026,Shekhar Banerjee,Pune,Desk,Furniture,2,11000.0,22000.0,Vikas,West,Credit Card
499,ORD10500,05/07/2025,Pankaj Mathur,Noida,Headphones,Accessories,5,2500.0,12500.0,Pooja,North,UPI

In [20]:
df["Customer"].iloc[4]

'Zaid Thakur'

In [22]:
df

,OrderID,OrderDate,Customer,City,Product,Category,Quantity,UnitPrice,Sales,Salesperson,Region,PaymentMode
0,ORD10001,19/04/2025,Vijay Patil,Delhi,Printer,Office,7,8500.0,59500.0,Anjali,North,Cash
1,ORD10002,16/03/2025,Myra Goel,Bangalore,Keyboard,Accessories,4,1800.0,7200.0,Vikas,South,Credit Card
2,ORD10003,26/05/2025,Jhanvi Shukla,Delhi,Chair,Furniture,7,7000.0,49000.0,Neha,North,Debit Card
3,ORD10004,08/05/2025,Vandana Dwivedi,Delhi,Mouse,Accessories,6,900.0,5400.0,Priya,North,Net Banking
4,ORD10005,11/02/2025,Zaid Thakur,Bangalore,Printer,Office,2,8500.0,17000.0,Vikas,South,Cash
...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD10496,01/12/2025,Sameer Singh,Noida,Laptop,Electronics,6,55000.0,330000.0,Neha,North,Debit Card
496,ORD10497,22/02/2026,Vamika Bisht,Gurgaon,Printer,Office,4,8500.0,34000.0,Priya,North,Cash
497,ORD10498,22/10/2025,Khushi Shukla,Delhi,Printer,Office,2,8500.0,17000.0,Pooja,North,Cash
498,ORD10499,06/01/2026,Shekhar Banerjee,Pune,Desk,Furniture,2,11000.0,22000.0,Vikas,West,Credit Card
499,ORD10500,05/07/2025,Pankaj Mathur,Noida,Headphones,Accessories,5,2500.0,12500.0,Pooja,North,UPI

1. Remove One Column

In [23]:
Column_remove = df.drop("Customer", axis=1)

In [24]:
Column_remove

,OrderID,OrderDate,City,Product,Category,Quantity,UnitPrice,Sales,Salesperson,Region,PaymentMode
0,ORD10001,19/04/2025,Delhi,Printer,Office,7,8500.0,59500.0,Anjali,North,Cash
1,ORD10002,16/03/2025,Bangalore,Keyboard,Accessories,4,1800.0,7200.0,Vikas,South,Credit Card
2,ORD10003,26/05/2025,Delhi,Chair,Furniture,7,7000.0,49000.0,Neha,North,Debit Card
3,ORD10004,08/05/2025,Delhi,Mouse,Accessories,6,900.0,5400.0,Priya,North,Net Banking
4,ORD10005,11/02/2025,Bangalore,Printer,Office,2,8500.0,17000.0,Vikas,South,Cash
...,...,...,...,...,...,...,...,...,...,...,...
495,ORD10496,01/12/2025,Noida,Laptop,Electronics,6,55000.0,330000.0,Neha,North,Debit Card
496,ORD10497,22/02/2026,Gurgaon,Printer,Office,4,8500.0,34000.0,Priya,North,Cash
497,ORD10498,22/10/2025,Delhi,Printer,Office,2,8500.0,17000.0,Pooja,North,Cash
498,ORD10499,06/01/2026,Pune,Desk,Furniture,2,11000.0,22000.0,Vikas,West,Credit Card
499,ORD10500,05/07/2025,Noida,Headphones,Accessories,5,2500.0,12500.0,Pooja,North,UPI

2. multiple column delet
- inplace=True = permanently apply the change to the current DataFrame.
- Example  
df.drop("Customer", axis=1, inplace=True)

In [25]:
mul_column = df.drop(["Customer", "City", "PaymentMode"], axis=1)

In [26]:
mul_column

,OrderID,OrderDate,Product,Category,Quantity,UnitPrice,Sales,Salesperson,Region
0,ORD10001,19/04/2025,Printer,Office,7,8500.0,59500.0,Anjali,North
1,ORD10002,16/03/2025,Keyboard,Accessories,4,1800.0,7200.0,Vikas,South
2,ORD10003,26/05/2025,Chair,Furniture,7,7000.0,49000.0,Neha,North
3,ORD10004,08/05/2025,Mouse,Accessories,6,900.0,5400.0,Priya,North
4,ORD10005,11/02/2025,Printer,Office,2,8500.0,17000.0,Vikas,South
...,...,...,...,...,...,...,...,...,...
495,ORD10496,01/12/2025,Laptop,Electronics,6,55000.0,330000.0,Neha,North
496,ORD10497,22/02/2026,Printer,Office,4,8500.0,34000.0,Priya,North
497,ORD10498,22/10/2025,Printer,Office,2,8500.0,17000.0,Pooja,North
498,ORD10499,06/01/2026,Desk,Furniture,2,11000.0,22000.0,Vikas,West
499,ORD10500,05/07/2025,Headphones,Accessories,5,2500.0,12500.0,Pooja,North

3. Select Data from a Column Based on a Condition

In [31]:
Condition = df[df["Sales"] > 5000]

In [33]:
Condition

,OrderID,OrderDate,Customer,City,Product,Category,Quantity,UnitPrice,Sales,Salesperson,Region,PaymentMode
0,ORD10001,19/04/2025,Vijay Patil,Delhi,Printer,Office,7,8500.0,59500.0,Anjali,North,Cash
1,ORD10002,16/03/2025,Myra Goel,Bangalore,Keyboard,Accessories,4,1800.0,7200.0,Vikas,South,Credit Card
2,ORD10003,26/05/2025,Jhanvi Shukla,Delhi,Chair,Furniture,7,7000.0,49000.0,Neha,North,Debit Card
3,ORD10004,08/05/2025,Vandana Dwivedi,Delhi,Mouse,Accessories,6,900.0,5400.0,Priya,North,Net Banking
4,ORD10005,11/02/2025,Zaid Thakur,Bangalore,Printer,Office,2,8500.0,17000.0,Vikas,South,Cash
...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD10496,01/12/2025,Sameer Singh,Noida,Laptop,Electronics,6,55000.0,330000.0,Neha,North,Debit Card
496,ORD10497,22/02/2026,Vamika Bisht,Gurgaon,Printer,Office,4,8500.0,34000.0,Priya,North,Cash
497,ORD10498,22/10/2025,Khushi Shukla,Delhi,Printer,Office,2,8500.0,17000.0,Pooja,North,Cash
498,ORD10499,06/01/2026,Shekhar Banerjee,Pune,Desk,Furniture,2,11000.0,22000.0,Vikas,West,Credit Card
499,ORD10500,05/07/2025,Pankaj Mathur,Noida,Headphones,Accessories,5,2500.0,12500.0,Pooja,North,UPI

4. Select only the Customer names where Sales is greater than 50000:

In [34]:
df.loc[df["Sales"] > 50000, "Customer"]

0           Vijay Patil
5           Riya Maurya
16         Varsha Anand
18          Harsha Bedi
19     Avinash Deshmukh
             ...
479    Bilal Chatterjee
486         Vidushi Dey
490         Utsav Handa
493     Shashank Pandey
495        Sameer Singh
Name: Customer, Length: 191, dtype: str

5. Make a Specific Value Blank

In [45]:
df["Customer"] = df["Customer"].replace("Varsha Anand", "")

6. Replace a Value with NaN

In [54]:
df["Customer"] = df["Customer"].replace("Aarav Sharma", np.nan)

7. Remove a Value Based on a Condition

In [49]:
df.loc[df["Sales"] == 0, "Customer"] = ""

In [50]:
df

,OrderID,OrderDate,Customer,City,Product,Category,Quantity,UnitPrice,Sales,Salesperson,Region,PaymentMode
0,ORD10001,19/04/2025,Vijay Patil,Delhi,Printer,Office,7,8500.0,59500.0,Anjali,North,Cash
1,ORD10002,16/03/2025,Myra Goel,Bangalore,Keyboard,Accessories,4,1800.0,7200.0,Vikas,South,Credit Card
2,ORD10003,26/05/2025,Jhanvi Shukla,Delhi,Chair,Furniture,7,7000.0,49000.0,Neha,North,Debit Card
3,ORD10004,08/05/2025,Vandana Dwivedi,Delhi,Mouse,Accessories,6,900.0,5400.0,Priya,North,Net Banking
4,ORD10005,11/02/2025,Zaid Thakur,Bangalore,Printer,Office,2,8500.0,17000.0,Vikas,South,Cash
...,...,...,...,...,...,...,...,...,...,...,...,...
495,ORD10496,01/12/2025,Sameer Singh,Noida,Laptop,Electronics,6,55000.0,330000.0,Neha,North,Debit Card
496,ORD10497,22/02/2026,Vamika Bisht,Gurgaon,Printer,Office,4,8500.0,34000.0,Priya,North,Cash
497,ORD10498,22/10/2025,Khushi Shukla,Delhi,Printer,Office,2,8500.0,17000.0,Pooja,North,Cash
498,ORD10499,06/01/2026,Shekhar Banerjee,Pune,Desk,Furniture,2,11000.0,22000.0,Vikas,West,Credit Card
499,ORD10500,05/07/2025,Pankaj Mathur,Noida,Headphones,Accessories,5,2500.0,12500.0,Pooja,North,UPI