# ➕ Arithmetic Operators in Pandas
- Pandas supports element-wise arithmetic operations on Series and DataFrames.

# 🔢 List of Arithmetic Operators

- add() --> `+` --> Addition         
- sub() -->  `-` --> Subtraction      
- mul() --> `*` --> Multiplication   
- div() -->  `/` --> Division         
- floordiv() -->  `//` --> Floor Division   
- mod() -->  `%` --> Modulus          
- pow() -->  `**` --> Power (Exponent)

In [ ]:
import pandas as pd

s1 = pd.Series([10, 20, 30])
s2 = pd.Series([2, 4, 6])

# ➕ Addition

In [3]:
s1 + s2

0    12
1    24
2    36
dtype: int64

# ➖ Subtraction

In [9]:
s1 - s2

0     8
1    16
2    24
dtype: int64

# ✖ Multiplication

In [8]:
s1 * s2

0     20
1     80
2    180
dtype: int64

# ➗ Division

In [7]:
s1 / s2

0    5.0
1    5.0
2    5.0
dtype: float64

# ➗➗ Floor Division

In [6]:
s1 // s2

0    5
1    5
2    5
dtype: int64

# 🔁 Modulus

In [5]:
s1 % s2

0    0
1    0
2    0
dtype: int64

# ⬆ Power

In [4]:
s1 ** s2

0          100
1       160000
2    729000000
dtype: int64

In [10]:
var1 = pd.DataFrame({"A":[10, 20, 30],"B":[15,16,18]})
var1

    A   B
0  10  15
1  20  16
2  30  18

# INSERT DATA IN PANDAS

# 🗑️ Delete and Insert Data in Pandas
- we can insert (add) or delete (remove) data in rows and columns of a DataFrame.

1️⃣ Insert a New Column
- Insert in Pandas means adding new data (a row or a column) into a DataFrame.

In [15]:
var = pd.DataFrame({"A":[1, 2, 3, 4, 5], "B":[10, 9, 8, 7, 6, ]})
print(var)

   A   B
0  1  10
1  2   9
2  3   8
3  4   7
4  5   6

In [16]:
var.insert(1,"python",var["A"])
var

   A  python   B
0  1       1  10
1  2       2   9
2  3       3   8
3  4       4   7
4  5       5   6

In [17]:
var['A'] = [20, 21, 22, 23, 24]
var

    A  python   B
0  20       1  10
1  21       2   9
2  22       3   8
3  23       4   7
4  24       5   6