# 🔥 Duplicate Data in pandas

### 📌 What is Duplicate Data?
Duplicate data means same rows or values appearing more than once in a dataset

### 1️⃣ Detect Duplicate Data
1. duplicated()
- Checks whether a row is duplicate or not.

# 🧠 Syntax

In [ ]:
df.duplicated()

### ✨ Example

In [1]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['A', 'B', 'A', 'C', 'B'],
    'Marks': [50, 60, 50, 70, 60]
})

print(df.duplicated())

0    False
1    False
2     True
3    False
4     True
dtype: bool

# 2️⃣ Remove Duplicate Rows
### 📌 What is `drop_duplicates()`
Removes duplicate rows from DataFrame.

# 🧠 Syntax

In [2]:
df.drop_duplicates()

  Name  Marks
0    A     50
1    B     60
3    C     70

# 3️⃣ Remove Duplicates from Specific Columns

In [3]:
df.drop_duplicates(subset=['Name'])

  Name  Marks
0    A     50
1    B     60
3    C     70

# 4️⃣ Keep First / Last Duplicate
- 🔹 Keep first (default)

In [4]:
df.drop_duplicates(keep='first')

  Name  Marks
0    A     50
1    B     60
3    C     70

🔹 Keep last

In [5]:
df.drop_duplicates(keep='last')

  Name  Marks
2    A     50
3    C     70
4    B     60

🔹 Remove all duplicates

In [6]:
df.drop_duplicates(keep=False)

  Name  Marks
3    C     70

5️⃣ Remove Duplicates In-Place

In [7]:
df.drop_duplicates(inplace=True)

7️⃣ Detect Duplicate Values in a Column

In [8]:
df['Name'].duplicated()

0    False
1    False
3    False
Name: Name, dtype: bool

8️⃣ Count Duplicate Rows

In [9]:
df.duplicated().sum()

np.int64(0)