# 1️⃣ Filtering Data in pandas

# 📌 What is Filtering Data?
- Filtering means selecting specific rows or columns based on conditions.

1️⃣ Filter Rows using Condition
- DataFrame se sirf wahi rows select karna jo kisi condition ko satisfy karti ho.

🧠 Syntax

In [1]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['A', 'B', 'C', 'D'],
    'Marks': [35, 55, 70, 40]
})

print(df[df['Marks'] > 40])

  Name  Marks
1    B     55
2    C     70

# Multiple Conditions (AND / OR)

🔹 AND (`&`)

In [2]:
df[(df['Marks'] > 40) & (df['Marks'] < 70)]

  Name  Marks
1    B     55

🔹 OR (`|`)

In [3]:
df[(df['Marks'] < 40) | (df['Marks'] > 60)]

  Name  Marks
0    A     35
2    C     70

### 🔹 What is isin() in Pandas?
isin() ka use hota hai check karne ke liye

- 👉 koi value given list / set / array ke andar hai ya nahi.

🔹 Filter using isin()

In [4]:
df[df['Name'].isin(['A', 'C'])]

  Name  Marks
0    A     35
2    C     70

Filter using between()

In [5]:
df[df['Marks'].between(40, 60)]

  Name  Marks
1    B     55
3    D     40

# 🔥 Filter using String Conditions

🔹 Starts with

In [6]:
df[df['Name'].str.startswith('A')]

  Name  Marks
0    A     35

🔹 Contains

In [7]:
df[df['Name'].str.contains('B')]

  Name  Marks
1    B     55

🪶 Filter Missing Values
- DataFrame se un rows ko select karna jisme missing data (`NaN` / `None`) ho ya na ho.

🔹 isnull()

In [8]:
df[df['Marks'].isnull()]

Empty DataFrame
Columns: [Name, Marks]
Index: []

🔹 What is `notnull()`
- `notnull()` ka use hota hai check karne ke liye
- value missing (NaN / None) nahi hai.

In [9]:
df[df['Marks'].notnull()]

  Name  Marks
0    A     35
1    B     55
2    C     70
3    D     40