# Group By

# 1️⃣ What is GroupBy?
GroupBy in pandas is used to:
- Group rows based on one or more columns (keys)
- Perform aggregate operations on each group (like sum, mean, count, etc.)

# 2️⃣ Syntax
`df.groupby('column_name').agg_function()`
- `column_name` → column(s) to group by (key)
- `agg_function()` → aggregation like `sum()`, `mean()`, `count()`, `max()`, `min()`

In [4]:
import pandas as pd

data = {
    'Department': ['HR', 'HR', 'IT', 'IT', 'Sales', 'Sales'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank'],
    'Salary': [50000, 60000, 70000, 80000, 55000, 65000]
}

df = pd.DataFrame(data)
df

  Department Employee  Salary
0         HR    Alice   50000
1         HR      Bob   60000
2         IT  Charlie   70000
3         IT    David   80000
4      Sales      Eve   55000
5      Sales    Frank   65000

In [9]:
var = df.groupby("Department")
var

In [10]:
for x, y in var:
    print(x)
    print(y)

HR
  Department Employee  Salary
0         HR    Alice   50000
1         HR      Bob   60000
IT
  Department Employee  Salary
2         IT  Charlie   70000
3         IT    David   80000
Sales
  Department Employee  Salary
4      Sales      Eve   55000
5      Sales    Frank   65000

# 1️⃣ What is get_group?
- `groupby()`, pandas creates a GroupBy object.

- `get_group(key)` allows you to extract a single group from that object as a DataFrame.

In [12]:
var.get_group("IT")

  Department Employee  Salary
2         IT  Charlie   70000
3         IT    David   80000

In [13]:
var.min()

           Employee  Salary
Department
HR            Alice   50000
IT          Charlie   70000
Sales           Eve   55000

In [14]:
var.max()

           Employee  Salary
Department
HR              Bob   60000
IT            David   80000
Sales         Frank   65000

In [15]:
li = list(var)
li

[('HR',
    Department Employee  Salary
  0         HR    Alice   50000
  1         HR      Bob   60000),
 ('IT',
    Department Employee  Salary
  2         IT  Charlie   70000
  3         IT    David   80000),
 ('Sales',
    Department Employee  Salary
  4      Sales      Eve   55000
  5      Sales    Frank   65000)]