# 🟢 Handling Missing Data in Pandas
1. Missing data means kisi column ya row me value ka na hona.

2. Pandas me missing values ko mostly NaN (Not a Number) se represent kiya jata hai.

Missing values usually appear as:
- `NaN`  --> Numeric missing value
- `None` --> Python ka null value
- `NaT`  --> Date/Time missing value

In [13]:
import pandas as pd
df = pd.read_excel(r"C:\EXCEL\converted_excel.xlsx")
df

,SYMBOL,SECURITY,TODAY-VOLUME,AVG_VOLUME,CHANGE
0,ELECTHERM,Electrotherm (India) Limited,473907.0,9457.0,50.110003
1,NBIFIN,N. B. I. Industrial Finance Company,5754.0,154.0,37.202586
2,HINDCON,Hindcon Chemicals Limited,304759.0,NaN,32.953450
3,GKWLIMITED,GKW Limited,NaN,711.0,30.049203
4,21STCENMGM,21st Century Management Services,110375.0,3879.0,28.450831
5,ALPHAGEO,NaN,232755.0,8356.0,27.852613
6,UNIENTer,Uniphos Enterprises Limited,162601.0,NaN,NaN
7,NaN,Jagsonpal Pharmaceuticals Limited,1301892.0,73134.0,17.801420
8,SKMEGGPROD,SKM Egg Products Export (India) Limited,1541130.0,87775.0,17.557733
9,SWELECTES,Swelect Energy Systems Limited,207954.0,12276.0,16.938733
10,NAHARPOLY,Nahar Poly Films Limited,NaN,38574.0,15.555297
11,PODDARHOUS,Poddar Housing and Development,46040.0,3012.0,NaN
12,LINC,Linc Limited,60551.0,4076.0,14.853673
13,SHIVAMILLS,Shiva Mills Limited,NaN,10391.0,13.755541
14,PDMJEPAPER,Pudumjee Paper Products Limited,1316284.0,102646.0,12.823425
15,DSSL,Dynacons Systems & Solutions Limited,263641.0,23439.0,11.247963
16,ANDREWYU,Andrew Yule & Company Limited,2448026.0,230048.0,NaN
17,LAXMICOT,Laxmi Cotspin Limited,NaN,19007.0,10.443312
18,REPL,Rudrabhishek Enterprises Limited,660281.0,65700.0,10.049914
19,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080.0,685602.0,10.011751
20,BHAGYAPROP,Bhagyanagar Properties Limited,305594.0,30596.0,9.987766
21,MUNJALAU,Munjal Auto Industries Limited,705322.0,82307.0,8.569318
22,ALKALI,NaN,NaN,NaN,NaN
23,INTENTECH,Intense Technologies Limited,1252606.0,164644.0,7.607959
24,INDORAMA,Indo Rama Synthetics (India) Limited,679204.0,89288.0,7.606862

# 1️⃣ Detect Missing Data
- Detect Missing Data means identifying the values in a dataset that are missing or null.

# 🔹 What .isnull() / isna()
- `isnull()` is used to detect missing values in a Pandas DataFrame.

- `isna()` same as `isnull()`

1. 🔹 Check missing values
- `df.isna()`
- `df.isnull()`   # same as isna()

In [14]:
df.isnull()

    SYMBOL  SECURITY  TODAY-VOLUME  AVG_VOLUME  CHANGE
0    False     False         False       False   False
1    False     False         False       False   False
2    False     False         False        True   False
3    False     False          True       False   False
4    False     False         False       False   False
5    False      True         False       False   False
6    False     False         False        True    True
7     True     False         False       False   False
8    False     False         False       False   False
9    False     False         False       False   False
10   False     False          True       False   False
11   False     False         False       False    True
12   False     False         False       False   False
13   False     False          True       False   False
14   False     False         False       False   False
15   False     False         False       False   False
16   False     False         False       False    True
17   False     False          True       False   False
18   False     False         False       False   False
19   False     False         False       False   False
20   False     False         False       False   False
21   False     False         False       False   False
22   False      True          True        True    True
23   False     False         False       False   False
24   False     False         False       False   False

# 🔹 Count missing values
`df.isna().sum()` is used to count missing values in each column of a Pandas DataFrame.
- `df.isna().sum()`

In [15]:
df.isnull().sum()

SYMBOL          1
SECURITY        2
TODAY-VOLUME    5
AVG_VOLUME      3
CHANGE          4
dtype: int64

# 2️⃣ Remove Missing Data
Remove Missing Data means deleting rows or columns that contain missing values (`NaN, None, NaT`) from a dataset.

### 📌 dropna() Method
dropna() is used to remove missing (null) values from a Pandas DataFrame or Series.

### 🔹 Syntax
df.dropna()

In [16]:
df.dropna()

,SYMBOL,SECURITY,TODAY-VOLUME,AVG_VOLUME,CHANGE
0,ELECTHERM,Electrotherm (India) Limited,473907.0,9457.0,50.110003
1,NBIFIN,N. B. I. Industrial Finance Company,5754.0,154.0,37.202586
4,21STCENMGM,21st Century Management Services,110375.0,3879.0,28.450831
8,SKMEGGPROD,SKM Egg Products Export (India) Limited,1541130.0,87775.0,17.557733
9,SWELECTES,Swelect Energy Systems Limited,207954.0,12276.0,16.938733
12,LINC,Linc Limited,60551.0,4076.0,14.853673
14,PDMJEPAPER,Pudumjee Paper Products Limited,1316284.0,102646.0,12.823425
15,DSSL,Dynacons Systems & Solutions Limited,263641.0,23439.0,11.247963
18,REPL,Rudrabhishek Enterprises Limited,660281.0,65700.0,10.049914
19,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080.0,685602.0,10.011751
20,BHAGYAPROP,Bhagyanagar Properties Limited,305594.0,30596.0,9.987766
21,MUNJALAU,Munjal Auto Industries Limited,705322.0,82307.0,8.569318
23,INTENTECH,Intense Technologies Limited,1252606.0,164644.0,7.607959
24,INDORAMA,Indo Rama Synthetics (India) Limited,679204.0,89288.0,7.606862

1️⃣ Remove columns with missing values
- `df.dropna(axis=1)`

In [17]:
df.dropna(axis=0)

,SYMBOL,SECURITY,TODAY-VOLUME,AVG_VOLUME,CHANGE
0,ELECTHERM,Electrotherm (India) Limited,473907.0,9457.0,50.110003
1,NBIFIN,N. B. I. Industrial Finance Company,5754.0,154.0,37.202586
4,21STCENMGM,21st Century Management Services,110375.0,3879.0,28.450831
8,SKMEGGPROD,SKM Egg Products Export (India) Limited,1541130.0,87775.0,17.557733
9,SWELECTES,Swelect Energy Systems Limited,207954.0,12276.0,16.938733
12,LINC,Linc Limited,60551.0,4076.0,14.853673
14,PDMJEPAPER,Pudumjee Paper Products Limited,1316284.0,102646.0,12.823425
15,DSSL,Dynacons Systems & Solutions Limited,263641.0,23439.0,11.247963
18,REPL,Rudrabhishek Enterprises Limited,660281.0,65700.0,10.049914
19,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080.0,685602.0,10.011751
20,BHAGYAPROP,Bhagyanagar Properties Limited,305594.0,30596.0,9.987766
21,MUNJALAU,Munjal Auto Industries Limited,705322.0,82307.0,8.569318
23,INTENTECH,Intense Technologies Limited,1252606.0,164644.0,7.607959
24,INDORAMA,Indo Rama Synthetics (India) Limited,679204.0,89288.0,7.606862

 2️⃣ Remove rows where all values are missing
- `df.dropna(how='all')`

In [18]:
df.dropna(how="all")

,SYMBOL,SECURITY,TODAY-VOLUME,AVG_VOLUME,CHANGE
0,ELECTHERM,Electrotherm (India) Limited,473907.0,9457.0,50.110003
1,NBIFIN,N. B. I. Industrial Finance Company,5754.0,154.0,37.202586
2,HINDCON,Hindcon Chemicals Limited,304759.0,NaN,32.953450
3,GKWLIMITED,GKW Limited,NaN,711.0,30.049203
4,21STCENMGM,21st Century Management Services,110375.0,3879.0,28.450831
5,ALPHAGEO,NaN,232755.0,8356.0,27.852613
6,UNIENTer,Uniphos Enterprises Limited,162601.0,NaN,NaN
7,NaN,Jagsonpal Pharmaceuticals Limited,1301892.0,73134.0,17.801420
8,SKMEGGPROD,SKM Egg Products Export (India) Limited,1541130.0,87775.0,17.557733
9,SWELECTES,Swelect Energy Systems Limited,207954.0,12276.0,16.938733
10,NAHARPOLY,Nahar Poly Films Limited,NaN,38574.0,15.555297
11,PODDARHOUS,Poddar Housing and Development,46040.0,3012.0,NaN
12,LINC,Linc Limited,60551.0,4076.0,14.853673
13,SHIVAMILLS,Shiva Mills Limited,NaN,10391.0,13.755541
14,PDMJEPAPER,Pudumjee Paper Products Limited,1316284.0,102646.0,12.823425
15,DSSL,Dynacons Systems & Solutions Limited,263641.0,23439.0,11.247963
16,ANDREWYU,Andrew Yule & Company Limited,2448026.0,230048.0,NaN
17,LAXMICOT,Laxmi Cotspin Limited,NaN,19007.0,10.443312
18,REPL,Rudrabhishek Enterprises Limited,660281.0,65700.0,10.049914
19,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080.0,685602.0,10.011751
20,BHAGYAPROP,Bhagyanagar Properties Limited,305594.0,30596.0,9.987766
21,MUNJALAU,Munjal Auto Industries Limited,705322.0,82307.0,8.569318
22,ALKALI,NaN,NaN,NaN,NaN
23,INTENTECH,Intense Technologies Limited,1252606.0,164644.0,7.607959
24,INDORAMA,Indo Rama Synthetics (India) Limited,679204.0,89288.0,7.606862

3️⃣ Remove rows based on specific columns
- `df.dropna(subset=['Column1', 'Column2'])`

In [20]:
df.dropna("SYMBOL", "TODAY-VOLUME", "AVG_VOLUME")

TypeError: DataFrame.dropna() takes 1 positional argument but 4 were given

4️⃣ Apply changes to original DataFrame
- `df.dropna(inplace=True)`

In [21]:
df.dropna(inplace=True)

In [22]:
df.isnull().sum()

SYMBOL          0
SECURITY        0
TODAY-VOLUME    0
AVG_VOLUME      0
CHANGE          0
dtype: int64

# 3️⃣ Fill Missing Data
Fill Missing Data means replacing the missing or null values (`NaN, None, NaT`) in a dataset with meaningful values instead of removing them.

### 📌 `fillna()` Method
- fillna() is used to fill (replace) missing values in a Pandas DataFrame or Series.

### 🔹 Syntax
`df.fillna(value)`

In [24]:
df.fillna({"SYMBOL":"PYTHON","SECURITY":"C","TODAY-VOLUME":"jAVA"})

,SYMBOL,SECURITY,TODAY-VOLUME,AVG_VOLUME,CHANGE
0,ELECTHERM,Electrotherm (India) Limited,473907.0,9457.0,50.110003
1,NBIFIN,N. B. I. Industrial Finance Company,5754.0,154.0,37.202586
4,21STCENMGM,21st Century Management Services,110375.0,3879.0,28.450831
8,SKMEGGPROD,SKM Egg Products Export (India) Limited,1541130.0,87775.0,17.557733
9,SWELECTES,Swelect Energy Systems Limited,207954.0,12276.0,16.938733
12,LINC,Linc Limited,60551.0,4076.0,14.853673
14,PDMJEPAPER,Pudumjee Paper Products Limited,1316284.0,102646.0,12.823425
15,DSSL,Dynacons Systems & Solutions Limited,263641.0,23439.0,11.247963
18,REPL,Rudrabhishek Enterprises Limited,660281.0,65700.0,10.049914
19,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080.0,685602.0,10.011751
20,BHAGYAPROP,Bhagyanagar Properties Limited,305594.0,30596.0,9.987766
21,MUNJALAU,Munjal Auto Industries Limited,705322.0,82307.0,8.569318
23,INTENTECH,Intense Technologies Limited,1252606.0,164644.0,7.607959
24,INDORAMA,Indo Rama Synthetics (India) Limited,679204.0,89288.0,7.606862

#### 🔹 Common Examples
1️⃣ Fill with a constant value :- 
- `df.fillna(0)`

2️⃣ Fill a specific column :- 
- `df['Age'].fillna(25)`

3️⃣ Fill with mean value
- `df['Marks'].fillna(df['Marks'].mean())`

4️⃣ Forward fill (previous value)
- `df.fillna(method='ffill')`

5️⃣ Backward fill (next value)
- `df.fillna(method='bfill')`

6️⃣ Change original DataFrame :-  
- `df.fillna(0, inplace=True)`

# 4️⃣ Replace Missing / Wrong Values
Replace Missing Data means filling or substituting missing values (`NaN, None, NaT`) with meaningful values instead of removing them.

### Syntax
`df.replace()`

In [25]:
arr = pd.read_excel(r"C:\EXCEL\Converted_Excel_File.xlsx")
arr

,NO.,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOLUME,CHANGE
0,1,ELECTHERM,Electrotherm (India) Limited,473907,9457,50.110003
1,2,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586
2,3,HINDCON,Hindcon Chemicals Limited,304759,9248,32.953450
3,4,GKWLIMITED,GKW Limited,21375,711,30.049203
4,5,21STCENMGM,21st Century Management Services,110375,3879,31.049203
5,6,ALPHAGEO,Alphageo (India) Limited,1,8356,27.852613
6,7,UNIPENTER,Uniphos Enterprises Limited,1,8357,21.528002
7,8,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1,73134,17.801420
8,9,SKMEGGPROD,SKM Egg Products Export (India),1,87775,18.801420
9,10,SWELECTES,Swelect Energy Systems Limited,1,87776,16.938733
10,11,NAHARPOLY,Nahar Poly Films Limited,1,38574,15.555297
11,12,PODDARHOUS,Poddar Housing and Development,1,3012,15.283833
12,13,LINC,Linc Limited,60551,4076,14.853673
13,14,LINC123,Linc Limited123,60550,4075,15.853673

In [27]:
arr.replace(to_replace=1, value=22)

,NO.,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOLUME,CHANGE
0,22,ELECTHERM,Electrotherm (India) Limited,473907,9457,50.110003
1,2,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586
2,3,HINDCON,Hindcon Chemicals Limited,304759,9248,32.953450
3,4,GKWLIMITED,GKW Limited,21375,711,30.049203
4,5,21STCENMGM,21st Century Management Services,110375,3879,31.049203
5,6,ALPHAGEO,Alphageo (India) Limited,22,8356,27.852613
6,7,UNIPENTER,Uniphos Enterprises Limited,22,8357,21.528002
7,8,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,22,73134,17.801420
8,9,SKMEGGPROD,SKM Egg Products Export (India),22,87775,18.801420
9,10,SWELECTES,Swelect Energy Systems Limited,22,87776,16.938733
10,11,NAHARPOLY,Nahar Poly Films Limited,22,38574,15.555297
11,12,PODDARHOUS,Poddar Housing and Development,22,3012,15.283833
12,13,LINC,Linc Limited,60551,4076,14.853673
13,14,LINC123,Linc Limited123,60550,4075,15.853673

### 🔹 Common Ways to Replace Missing Data
🔹 Replace value with NaN
- `df.replace(-1, np.nan)`

In [29]:
arr.replace(1, method="ffill", limit=3)

C:\Users\Anish Kumar\AppData\Local\Temp\ipykernel_49200\4225981708.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  arr.replace(1, method="ffill", limit=3)

,NO.,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOLUME,CHANGE
0,1,ELECTHERM,Electrotherm (India) Limited,473907,9457,50.110003
1,2,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586
2,3,HINDCON,Hindcon Chemicals Limited,304759,9248,32.953450
3,4,GKWLIMITED,GKW Limited,21375,711,30.049203
4,5,21STCENMGM,21st Century Management Services,110375,3879,31.049203
5,6,ALPHAGEO,Alphageo (India) Limited,110375,8356,27.852613
6,7,UNIPENTER,Uniphos Enterprises Limited,110375,8357,21.528002
7,8,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,110375,73134,17.801420
8,9,SKMEGGPROD,SKM Egg Products Export (India),1,87775,18.801420
9,10,SWELECTES,Swelect Energy Systems Limited,1,87776,16.938733
10,11,NAHARPOLY,Nahar Poly Films Limited,1,38574,15.555297
11,12,PODDARHOUS,Poddar Housing and Development,1,3012,15.283833
12,13,LINC,Linc Limited,60551,4076,14.853673
13,14,LINC123,Linc Limited123,60550,4075,15.853673

🔹 Replace multiple values
- `df.replace(["NA", "null"], np.nan)`

🔹 Column-wise replace
- `df.replace({"Marks": {0: np.nan}})`

# 5️⃣ Interpolate Missing Data
Interpolate Missing Data means estimating and filling missing values using existing data patterns, instead of using a fixed value like 0 or mean.

### 🔹 Syntax
`df.interpolate()`

In [30]:
ar = pd.read_excel(r"C:\EXCEL\Converted_Excel_File.xlsx")
ar

,NO.,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOLUME,CHANGE
0,1,ELECTHERM,Electrotherm (India) Limited,473907,9457,50.110003
1,2,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586
2,3,HINDCON,Hindcon Chemicals Limited,304759,9248,32.953450
3,4,GKWLIMITED,GKW Limited,21375,711,30.049203
4,5,21STCENMGM,21st Century Management Services,110375,3879,31.049203
5,6,ALPHAGEO,Alphageo (India) Limited,1,8356,27.852613
6,7,UNIPENTER,Uniphos Enterprises Limited,1,8357,21.528002
7,8,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1,73134,17.801420
8,9,SKMEGGPROD,SKM Egg Products Export (India),1,87775,18.801420
9,10,SWELECTES,Swelect Energy Systems Limited,1,87776,16.938733
10,11,NAHARPOLY,Nahar Poly Films Limited,1,38574,15.555297
11,12,PODDARHOUS,Poddar Housing and Development,1,3012,15.283833
12,13,LINC,Linc Limited,60551,4076,14.853673
13,14,LINC123,Linc Limited123,60550,4075,15.853673

### 🔹 Common Interpolation Methods

1️⃣ Linear interpolation (default)
- `df.interpolate()`
- Fills missing values in a straight-line manner.

2️⃣ Time-based interpolation
- `df.interpolate(method='time')`
- Used when index is DateTime.

3️⃣ Forward / Backward direction
- `df.interpolate(limit_direction='forward')`