# Pandas Function

In [1]:
import pandas as pd
var = pd.read_excel(r"C:\EXCEL\converted_excel.xlsx")
var

,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOLUME,CHANGE
0,ELECTHERM,Electrotherm (India) Limited,473907,9457,50.110003
1,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586
2,HINDCON,Hindcon Chemicals Limited,304759,9248,32.953450
3,GKWLIMITED,GKW Limited,21375,711,30.049203
4,21STCENMGM,21st Century Management Services,110375,3879,28.450831
5,ALPHAGEO,Alphageo (India) Limited,232755,8356,27.852613
6,UNIENTer,Uniphos Enterprises Limited,162601,7553,21.528002
7,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1301892,73134,17.801420
8,SKMEGGPROD,SKM Egg Products Export (India) Limited,1541130,87775,17.557733
9,SWELECTES,Swelect Energy Systems Limited,207954,12276,16.938733
10,NAHARPOLY,Nahar Poly Films Limited,600043,38574,15.555297
11,PODDARHOUS,Poddar Housing and Development,46040,3012,15.283833
12,LINC,Linc Limited,60551,4076,14.853673
13,SHIVAMILLS,Shiva Mills Limited,142943,10391,13.755541
14,PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,12.823425
15,DSSL,Dynacons Systems & Solutions Limited,263641,23439,11.247963
16,ANDREWYU,Andrew Yule & Company Limited,2448026,230048,10.641332
17,LAXMICOT,Laxmi Cotspin Limited,198503,19007,10.443312
18,REPL,Rudrabhishek Enterprises Limited,660281,65700,10.049914
19,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,10.011751
20,BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987766
21,MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569318
22,ALKALI,Alkali Metals Limited,157496,19059,8.263313
23,INTENTECH,Intense Technologies Limited,1252606,164644,7.607959
24,INDORAMA,Indo Rama Synthetics (India) Limited,679204,89288,7.606862

# 🔹 Index Function in Pandas
- Index is NOT a function, it is a data structure used to label rows in a DataFrame or Series.

In [2]:
var.index

RangeIndex(start=0, stop=25, step=1)

# 🔹 columns in Pandas
- columns is an attribute used to view, change, or select column names in a DataFrame.

### 1️⃣ Check Column Names
`df.columns`

In [3]:
var.columns

Index(['SYMBOL', 'SECURITY', 'TODAY - VOLUME', 'AVG. VOLUME', 'CHANGE'], dtype='object')

# 🔹 `head()` in Pandas

`head()` is used to display the first few rows of a DataFrame or Series.

# 1️⃣ Basic Syntax
`df.head()`

In [6]:
var.head()

,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOLUME,CHANGE
0,ELECTHERM,Electrotherm (India) Limited,473907,9457,50.110003
1,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586
2,HINDCON,Hindcon Chemicals Limited,304759,9248,32.953450
3,GKWLIMITED,GKW Limited,21375,711,30.049203
4,21STCENMGM,21st Century Management Services,110375,3879,28.450831

# 🔹 describe() in Pandas
- describe() is used to get a statistical summary of a DataFrame or Series.

### 1️⃣ Basic Syntax
- `df.describe()`

### 2️⃣ What Does `describe()` Show?
- numeric columns, it returns: 

-  Statistic  -->        Meaning
-    count    --> Number of non-null values
-    mean     --> Average
-    std      --> Standard deviation
-    min      --> Minimum value
-    25%      --> First quartile
-    50%      --> Median
-    75%      --> Third quartile
-    max      --> Maximum value

In [5]:
var.describe()

       TODAY - VOLUME    AVG. VOLUME     CHANGE
count    2.500000e+01      25.000000  25.000000
mean     8.025246e+05   71237.280000  17.885833
std      1.397036e+06  139964.776177  10.809391
min      5.754000e+03     154.000000   7.606862
25%      1.574960e+05    8356.000000  10.049914
50%      3.047590e+05   19059.000000  14.853673
75%      7.053220e+05   82307.000000  21.528002
max      6.864080e+06  685602.000000  50.110003

# 🔹 tail() in Pandas
- `tail()` is used to display the last few rows of a DataFrame or Series.

In [7]:
var.tail()

,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOLUME,CHANGE
20,BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987766
21,MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569318
22,ALKALI,Alkali Metals Limited,157496,19059,8.263313
23,INTENTECH,Intense Technologies Limited,1252606,164644,7.607959
24,INDORAMA,Indo Rama Synthetics (India) Limited,679204,89288,7.606862

# 🔹 type in Pandas
- `type()` is a Python built-in function, used in Pandas to check the data type of an object.

In [8]:
print(type(var))

<class 'pandas.core.frame.DataFrame'>

# 🔹 index.array in Pandas
- `index.array` is used to get the underlying array data of a DataFrame or Series Index.

In [9]:
var.index.array

<NumpyExtensionArray>
[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
 19, 20, 21, 22, 23, 24]
Length: 25, dtype: int64

# 🔹 to_numpy() in Pandas
- `to_numpy()` is used to convert Pandas data (DataFrame, Series, Index) into a NumPy array.

In [10]:
var.to_numpy()

array([['ELECTHERM', 'Electrotherm (India) Limited', 473907, 9457,
        50.11000282],
       ['NBIFIN', 'N. B. I. Industrial Finance Company', 5754, 154,
        37.20258621],
       ['HINDCON', 'Hindcon Chemicals Limited', 304759, 9248,
        32.95345023],
       ['GKWLIMITED', 'GKW Limited', 21375, 711, 30.04920337],
       ['21STCENMGM', '21st Century Management Services', 110375, 3879,
        28.45083129],
       ['ALPHAGEO', 'Alphageo (India) Limited', 232755, 8356,
        27.85261268],
       ['UNIENTer', 'Uniphos Enterprises Limited', 162601, 7553,
        21.52800212],
       ['JAGSNPHARM', 'Jagsonpal Pharmaceuticals Limited', 1301892,
        73134, 17.80141977],
       ['SKMEGGPROD', 'SKM Egg Products Export (India) Limited', 1541130,
        87775, 17.55773284],
       ['SWELECTES', 'Swelect Energy Systems Limited', 207954, 12276,
        16.93873284],
       ['NAHARPOLY', 'Nahar Poly Films Limited', 600043, 38574,
        15.55529728],
       ['PODDARHOUS', 'Poddar Housing and Development', 46040, 3012,
        15.28383313],
       ['LINC', 'Linc Limited', 60551, 4076, 14.85367349],
       ['SHIVAMILLS', 'Shiva Mills Limited', 142943, 10391, 13.7555413],
       ['PDMJEPAPER', 'Pudumjee Paper Products Limited', 1316284, 102646,
        12.8234253],
       ['DSSL', 'Dynacons Systems & Solutions Limited', 263641, 23439,
        11.2479628],
       ['ANDREWYU', 'Andrew Yule & Company Limited', 2448026, 230048,
        10.64133195],
       ['LAXMICOT', 'Laxmi Cotspin Limited', 198503, 19007, 10.44331235],
       ['REPL', 'Rudrabhishek Enterprises Limited', 660281, 65700,
        10.04991362],
       ['PILITA', 'PIL ITALICA LIFESTYLE LIMITED', 6864080, 685602,
        10.01175122],
       ['BHAGYAPROP', 'Bhagyanagar Properties Limited', 305594, 30596,
        9.987765618],
       ['MUNJALAU', 'Munjal Auto Industries Limited', 705322, 82307,
        8.569318028],
       ['ALKALI', 'Alkali Metals Limited', 157496, 19059, 8.263313454],
       ['INTENTECH', 'Intense Technologies Limited', 1252606, 164644,
        7.607958577],
       ['INDORAMA', 'Indo Rama Synthetics (India) Limited', 679204,
        89288, 7.606861665]], dtype=object)

# 🔹 np.asarray()
`np.asarray()` converts any array-like object into a NumPy array.

### 1️⃣ Syntax
`np.asarray(a, dtype=None, order=None)`

In [12]:
import numpy as np
v = np.asarray(var)
v

array([['ELECTHERM', 'Electrotherm (India) Limited', 473907, 9457,
        50.11000282],
       ['NBIFIN', 'N. B. I. Industrial Finance Company', 5754, 154,
        37.20258621],
       ['HINDCON', 'Hindcon Chemicals Limited', 304759, 9248,
        32.95345023],
       ['GKWLIMITED', 'GKW Limited', 21375, 711, 30.04920337],
       ['21STCENMGM', '21st Century Management Services', 110375, 3879,
        28.45083129],
       ['ALPHAGEO', 'Alphageo (India) Limited', 232755, 8356,
        27.85261268],
       ['UNIENTer', 'Uniphos Enterprises Limited', 162601, 7553,
        21.52800212],
       ['JAGSNPHARM', 'Jagsonpal Pharmaceuticals Limited', 1301892,
        73134, 17.80141977],
       ['SKMEGGPROD', 'SKM Egg Products Export (India) Limited', 1541130,
        87775, 17.55773284],
       ['SWELECTES', 'Swelect Energy Systems Limited', 207954, 12276,
        16.93873284],
       ['NAHARPOLY', 'Nahar Poly Films Limited', 600043, 38574,
        15.55529728],
       ['PODDARHOUS', 'Poddar Housing and Development', 46040, 3012,
        15.28383313],
       ['LINC', 'Linc Limited', 60551, 4076, 14.85367349],
       ['SHIVAMILLS', 'Shiva Mills Limited', 142943, 10391, 13.7555413],
       ['PDMJEPAPER', 'Pudumjee Paper Products Limited', 1316284, 102646,
        12.8234253],
       ['DSSL', 'Dynacons Systems & Solutions Limited', 263641, 23439,
        11.2479628],
       ['ANDREWYU', 'Andrew Yule & Company Limited', 2448026, 230048,
        10.64133195],
       ['LAXMICOT', 'Laxmi Cotspin Limited', 198503, 19007, 10.44331235],
       ['REPL', 'Rudrabhishek Enterprises Limited', 660281, 65700,
        10.04991362],
       ['PILITA', 'PIL ITALICA LIFESTYLE LIMITED', 6864080, 685602,
        10.01175122],
       ['BHAGYAPROP', 'Bhagyanagar Properties Limited', 305594, 30596,
        9.987765618],
       ['MUNJALAU', 'Munjal Auto Industries Limited', 705322, 82307,
        8.569318028],
       ['ALKALI', 'Alkali Metals Limited', 157496, 19059, 8.263313454],
       ['INTENTECH', 'Intense Technologies Limited', 1252606, 164644,
        7.607958577],
       ['INDORAMA', 'Indo Rama Synthetics (India) Limited', 679204,
        89288, 7.606861665]], dtype=object)

# 🔹 `sort_index()` in Pandas
`sort_index()` is used to sort a DataFrame or Series by its index.

### 🔹 axis in Pandas
`axis` tells Pandas which direction to work on
- axis=0 --> Rows (vertical)
- axis=1 --> Columns (horizontal)

### 1️⃣ Basic Syntax
`df.sort_index()`

### 3️⃣ Sort in Descending Order
`df.sort_index(ascending=False)`

### 5️⃣ Inplace Sorting
`df.sort_index(inplace=True)`

In [13]:
var.sort_index(axis=0,ascending=False)

,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOLUME,CHANGE
24,INDORAMA,Indo Rama Synthetics (India) Limited,679204,89288,7.606862
23,INTENTECH,Intense Technologies Limited,1252606,164644,7.607959
22,ALKALI,Alkali Metals Limited,157496,19059,8.263313
21,MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569318
20,BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987766
19,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,10.011751
18,REPL,Rudrabhishek Enterprises Limited,660281,65700,10.049914
17,LAXMICOT,Laxmi Cotspin Limited,198503,19007,10.443312
16,ANDREWYU,Andrew Yule & Company Limited,2448026,230048,10.641332
15,DSSL,Dynacons Systems & Solutions Limited,263641,23439,11.247963
14,PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,12.823425
13,SHIVAMILLS,Shiva Mills Limited,142943,10391,13.755541
12,LINC,Linc Limited,60551,4076,14.853673
11,PODDARHOUS,Poddar Housing and Development,46040,3012,15.283833
10,NAHARPOLY,Nahar Poly Films Limited,600043,38574,15.555297
9,SWELECTES,Swelect Energy Systems Limited,207954,12276,16.938733
8,SKMEGGPROD,SKM Egg Products Export (India) Limited,1541130,87775,17.557733
7,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1301892,73134,17.801420
6,UNIENTer,Uniphos Enterprises Limited,162601,7553,21.528002
5,ALPHAGEO,Alphageo (India) Limited,232755,8356,27.852613
4,21STCENMGM,21st Century Management Services,110375,3879,28.450831
3,GKWLIMITED,GKW Limited,21375,711,30.049203
2,HINDCON,Hindcon Chemicals Limited,304759,9248,32.953450
1,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586
0,ELECTHERM,Electrotherm (India) Limited,473907,9457,50.110003

# 🔹 loc kya karta hai?
- loc = label-based selection & modification

In [18]:
var.loc[0,"SYMBOL"]="Python"
var

,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOLUME,CHANGE
0,Python,Electrotherm (India) Limited,473907,9457,50.110003
1,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586
2,HINDCON,Hindcon Chemicals Limited,304759,9248,32.953450
3,GKWLIMITED,GKW Limited,21375,711,30.049203
4,21STCENMGM,21st Century Management Services,110375,3879,28.450831
5,ALPHAGEO,Alphageo (India) Limited,232755,8356,27.852613
6,UNIENTer,Uniphos Enterprises Limited,162601,7553,21.528002
7,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1301892,73134,17.801420
8,SKMEGGPROD,SKM Egg Products Export (India) Limited,1541130,87775,17.557733
9,SWELECTES,Swelect Energy Systems Limited,207954,12276,16.938733
10,NAHARPOLY,Nahar Poly Films Limited,600043,38574,15.555297
11,PODDARHOUS,Poddar Housing and Development,46040,3012,15.283833
12,LINC,Linc Limited,60551,4076,14.853673
13,SHIVAMILLS,Shiva Mills Limited,142943,10391,13.755541
14,PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,12.823425
15,DSSL,Dynacons Systems & Solutions Limited,263641,23439,11.247963
16,ANDREWYU,Andrew Yule & Company Limited,2448026,230048,10.641332
17,LAXMICOT,Laxmi Cotspin Limited,198503,19007,10.443312
18,REPL,Rudrabhishek Enterprises Limited,660281,65700,10.049914
19,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,10.011751
20,BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987766
21,MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569318
22,ALKALI,Alkali Metals Limited,157496,19059,8.263313
23,INTENTECH,Intense Technologies Limited,1252606,164644,7.607959
24,INDORAMA,Indo Rama Synthetics (India) Limited,679204,89288,7.606862