# 🔹 Sorting Data in pandas

# 📌 What is Sorting Data in Pandas?

Sorting data in Pandas means arranging the rows of a DataFrame or Series in a specific order based on:

- column values
- index values

🔹 Why do we sort data?
- To analyze data easily
- To find highest / lowest values
- To make reports clean and readable

In [1]:
import pandas as pd
df = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "Marks": [78, 45, 90, 60]
})

# 🔹 Types of Sorting in Pandas

### 1️⃣ Sort by Values (Column-based sorting)
Used when you want to sort rows based on column values.

`sort_values()`

In [2]:
df.sort_values(by="Marks")

  Name  Marks
1    B     45
3    D     60
0    A     78
2    C     90

# 2️⃣ Sort by Index
Used when you want to sort rows based on index.
- sort_index()`

In [3]:
df.sort_index()

  Name  Marks
0    A     78
1    B     45
2    C     90
3    D     60

# 🔹 Sort data in ascending order (default)

In [4]:
df.sort_values(by="Marks")

  Name  Marks
1    B     45
3    D     60
0    A     78
2    C     90

🔹 Sort data in descending order

In [5]:
df.sort_values(by="Marks", ascending=False)

  Name  Marks
2    C     90
0    A     78
3    D     60
1    B     45

🔹 Sort by multiple columns

In [6]:
df.sort_values(by=["Marks", "Name"])

  Name  Marks
1    B     45
3    D     60
0    A     78
2    C     90

🔹 Sorting with missing values

In [7]:
df.sort_values(by="Marks", na_position="last")

  Name  Marks
1    B     45
3    D     60
0    A     78
2    C     90