In [1]:
import pandas as pd
import numpy as np

1. Series from lists

In [13]:
data = ['india', 'Pakistan', 'USA', 'Nepal']
df = pd.Series(data, index=["A", "B", "C", "D"], name="Cuntry Name")
df

A       india
B    Pakistan
C         USA
D       Nepal
Name: Cuntry Name, dtype: str

3. integers

In [14]:
runs = [12, 123, 13, 45]
pd.Series(runs)

0     12
1    123
2     13
3     45
dtype: int64

Custom Index

In [15]:
data_01 = [67, 57, 89, 100]
subject = ['Math', 'English', 'Science', 'Hindi']
df = pd.Series(data_01, index = subject)
df

Math        67
English     57
Science     89
Hindi      100
dtype: int64

3. setting name

In [16]:
df = pd.Series(data_01, index = subject, name="Suraj Marks")
df

Math        67
English     57
Science     89
Hindi      100
Name: Suraj Marks, dtype: int64

Series from dict

In [20]:
dict = {
    'Math':67,
    'English':57,
    'science':89,
    'Hindi':100
}
marks_series = pd.Series(dict, name="Suraj All Marks ")
marks_series

Math        67
English     57
science     89
Hindi      100
Name: Suraj All Marks , dtype: int64

### Series Attributes

index

In [25]:
marks_series.index

Index(['Math', 'English', 'science', 'Hindi'], dtype='str')

values

In [26]:
marks_series.values

array([ 67,  57,  89, 100])

dtype

In [22]:
marks_series.dtype

dtype('int64')

name

In [23]:
marks_series.name

'Suraj All Marks '

shape:- DataFrame ya Series ki dimensions batata hai.

In [27]:
marks_series.shape

(4,)

size:- Total elements ki count batata hai.

In [21]:
marks_series.size

4

is_unique:- check karta hai ki Series ke sabhi values unique hain ya nahi.
- Agar koi duplicate value nahi hai → True
- Agar duplicate value hai → False

In [28]:
marks_series.is_unique

True

### Series using read_csv

with one col

In [36]:
holly = pd.read_csv(r"C:\Users\Anish Kumar\OneDrive\Documents\GitHub\PANDAS-CURSE\DOC\datasets-session-16\subs.csv")
holly

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

with two col

In [38]:
kohli = pd.read_csv(r"C:\Users\Anish Kumar\OneDrive\Documents\GitHub\PANDAS-CURSE\DOC\datasets-session-16\kohli_ipl.csv")
print(kohli)

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [41]:
bollybood = pd.read_csv(r"C:\Users\Anish Kumar\OneDrive\Documents\GitHub\PANDAS-CURSE\DOC\datasets-session-16\bollywood.csv")
print(bollybood)

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

# Series methods

heda and tail

In [46]:
kohli.tail(10)

     match_no  runs
205       206     0
206       207     0
207       208     9
208       209    58
209       210    30
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

In [44]:
holly.head(10)

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44
5                  46
6                  33
7                  40
8                  44
9                  74

sample

In [48]:
bollybood.sample(5)

                    movie                lead
1359         Khamosh Pani          Kiron Kher
1112         Om Shanti Om      Shah Rukh Khan
243   Qarib Qarib Singlle         Irrfan Khan
64            Ujda Chaman  Sunny Singh Nijjar
105         Omerta (film)       Rajkummar Rao

value_counts -> movies

In [52]:
bollybood.value_counts()

movie                     lead
Tanu Weds Manu: Returns   Kangana Ranaut      2
Gabbar Is Back            Akshay Kumar        2
Andaaz                    Akshay Kumar        2
Uri: The Surgical Strike  Vicky Kaushal       1
Battalion 609             Vicky Ahuja         1
                                             ..
Hum Tumhare Hain Sanam    Shah Rukh Khan      1
Aankhen (2002 film)       Amitabh Bachchan    1
Saathiya (film)           Vivek Oberoi        1
Company (film)            Ajay Devgn          1
Awara Paagal Deewana      Akshay Kumar        1
Name: count, Length: 1497, dtype: int64

Sort_values -> inplace

In [73]:
kohli.sort_values(by='runs', ascending=False).head(1).values[0]

array([128, 113])

sort_index -> inplace -> movies

In [80]:
bollybood.sort_index(inplace=True)
bollybood

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

# Series maths Methods

count

In [81]:
kohli.count()

match_no    215
runs        215
dtype: int64

sum

In [82]:
holly.sum()

Subscribers gained    49510
dtype: int64

mean -> median -> mode -> std -> var

In [86]:
holly.mean()

Subscribers gained    135.643836
dtype: float64

In [87]:
print(kohli.median())

match_no    108.0
runs         24.0
dtype: float64

In [94]:
bollybood.mode()

                     movie          lead
0                   Andaaz  Akshay Kumar
1           Gabbar Is Back           NaN
2  Tanu Weds Manu: Returns           NaN

In [96]:
print(holly.std())

Subscribers gained    62.675023
dtype: float64

In [98]:
print(kohli.var())

match_no    3870.000000
runs         688.002478
dtype: float64

min/max

In [99]:
holly.min()

Subscribers gained    33
dtype: int64

In [100]:
holly.max()

Subscribers gained    396
dtype: int64

describe

In [101]:
kohli.describe()

         match_no        runs
count  215.000000  215.000000
mean   108.000000   30.855814
std     62.209324   26.229801
min      1.000000    0.000000
25%     54.500000    9.000000
50%    108.000000   24.000000
75%    161.500000   48.000000
max    215.000000  113.000000

# Series Index