In [1]:
import pandas as pd
import numpy as np

1. Series from lists

In [5]:
data = ['india', 'Pakistan', 'USA', 'Nepal']
df = pd.Series(data, index=["A", "B", "C", "D"], name="Cuntry Name")
df

A       india
B    Pakistan
C         USA
D       Nepal
Name: Cuntry Name, dtype: str

3. integers

In [55]:
runs = [12, 123, 13, 45]
runs_ser = pd.Series(runs)

Custom Index

In [7]:
data_01 = [67, 57, 89, 100]
subject = ['Math', 'English', 'Science', 'Hindi']
df = pd.Series(data_01, index = subject)
df

Math        67
English     57
Science     89
Hindi      100
dtype: int64

3. setting name

In [8]:
df = pd.Series(data_01, index = subject, name="Suraj Marks")
df

Math        67
English     57
Science     89
Hindi      100
Name: Suraj Marks, dtype: int64

Series from dict

In [9]:
dict = {
    'Math':67,
    'English':57,
    'science':89,
    'Hindi':100
}
marks_series = pd.Series(dict, name="Suraj All Marks ")
marks_series

Math        67
English     57
science     89
Hindi      100
Name: Suraj All Marks , dtype: int64

### Series Attributes

index

In [10]:
marks_series.index

Index(['Math', 'English', 'science', 'Hindi'], dtype='str')

values

In [11]:
marks_series.values

array([ 67,  57,  89, 100])

dtype

In [12]:
marks_series.dtype

dtype('int64')

name

In [13]:
marks_series.name

'Suraj All Marks '

shape:- DataFrame ya Series ki dimensions batata hai.

In [14]:
marks_series.shape

(4,)

size:- Total elements ki count batata hai.

In [15]:
marks_series.size

4

is_unique:- check karta hai ki Series ke sabhi values unique hain ya nahi.
- Agar koi duplicate value nahi hai → True
- Agar duplicate value hai → False

In [16]:
marks_series.is_unique

True

### Series using read_csv

with one col

In [17]:
holly = pd.read_csv(r"C:\Users\Anish Kumar\OneDrive\Documents\GitHub\PANDAS-CURSE\DOC\datasets-session-16\subs.csv")
holly

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

with two col

In [18]:
kohli = pd.read_csv(r"C:\Users\Anish Kumar\OneDrive\Documents\GitHub\PANDAS-CURSE\DOC\datasets-session-16\kohli_ipl.csv")
print(kohli)

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [19]:
bollybood = pd.read_csv(r"C:\Users\Anish Kumar\OneDrive\Documents\GitHub\PANDAS-CURSE\DOC\datasets-session-16\bollywood.csv")
print(bollybood)

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

# Series methods

heda and tail

In [20]:
kohli.tail(10)

     match_no  runs
205       206     0
206       207     0
207       208     9
208       209    58
209       210    30
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

In [21]:
holly.head(10)

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44
5                  46
6                  33
7                  40
8                  44
9                  74

sample

In [22]:
bollybood.sample(5)

                              movie              lead
934                      Barah Aana  Naseeruddin Shah
1073                  Dil Dosti Etc   Imaaduddin Shah
942                   Paying Guests   Shreyas Talpade
1100        Manorama Six Feet Under        Abhay Deol
1060  The Blue Umbrella (2005 film)      Pankaj Kapur

value_counts -> movies

In [23]:
bollybood.value_counts()

movie                     lead
Tanu Weds Manu: Returns   Kangana Ranaut      2
Gabbar Is Back            Akshay Kumar        2
Andaaz                    Akshay Kumar        2
Uri: The Surgical Strike  Vicky Kaushal       1
Battalion 609             Vicky Ahuja         1
                                             ..
Hum Tumhare Hain Sanam    Shah Rukh Khan      1
Aankhen (2002 film)       Amitabh Bachchan    1
Saathiya (film)           Vivek Oberoi        1
Company (film)            Ajay Devgn          1
Awara Paagal Deewana      Akshay Kumar        1
Name: count, Length: 1497, dtype: int64

Sort_values -> inplace

In [24]:
kohli.sort_values(by='runs', ascending=False).head(1).values[0]

array([128, 113])

sort_index -> inplace -> movies

In [25]:
bollybood.sort_index(inplace=True)
bollybood

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

# Series maths Methods

count

In [26]:
kohli.count()

match_no    215
runs        215
dtype: int64

sum

In [27]:
holly.sum()

Subscribers gained    49510
dtype: int64

mean -> median -> mode -> std -> var

In [28]:
holly.mean()

Subscribers gained    135.643836
dtype: float64

In [29]:
print(kohli.median())

match_no    108.0
runs         24.0
dtype: float64

In [30]:
bollybood.mode()

                     movie          lead
0                   Andaaz  Akshay Kumar
1           Gabbar Is Back           NaN
2  Tanu Weds Manu: Returns           NaN

In [31]:
print(holly.std())

Subscribers gained    62.675023
dtype: float64

In [32]:
print(kohli.var())

match_no    3870.000000
runs         688.002478
dtype: float64

min/max

In [33]:
holly.min()

Subscribers gained    33
dtype: int64

In [34]:
holly.max()

Subscribers gained    396
dtype: int64

describe

In [35]:
kohli.describe()

         match_no        runs
count  215.000000  215.000000
mean   108.000000   30.855814
std     62.209324   26.229801
min      1.000000    0.000000
25%     54.500000    9.000000
50%    108.000000   24.000000
75%    161.500000   48.000000
max    215.000000  113.000000

# Series Index

integer indexing

In [45]:
x = pd.Series([12, 13, 14, 15])
x[1]

np.int64(13)

negative indexing

In [46]:
x[-1]

KeyError: -1

slicing

In [ ]:
bollybood[5:16]

                               movie                  lead
5                        Soni (film)  Geetika Vidya Ohlyan
6                      Fraud Saiyaan          Arshad Warsi
7                         Bombairiya          Radhika Apte
8   Manikarnika: The Queen of Jhansi        Kangana Ranaut
9                   Thackeray (film)   Nawazuddin Siddiqui
10                            Amavas             Ali Asgar
11                         Gully Boy         Ranveer Singh
12                         Hum Chaar           Prit Kamani
13                     Total Dhamaal            Ajay Devgn
14                        Sonchiriya  Sushant Singh Rajput
15                 Badla (2019 film)      Amitabh Bachchan

negative slicing

In [ ]:
kohli[-5:]

     match_no  runs
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

fancy indexing

In [ ]:
kohli[[1,3,4,5]]

KeyError: "None of [Index([1, 3, 4, 5], dtype='int64')] are in the [columns]"

indexing with labels -> fancy indexing

In [ ]:
bollybood['2 States (2014 file)']

KeyError: '2 States (2014 file)'

Editing Series

Using indexing

In [49]:
marks_series[1] = 100
marks_series

Math        67
English     57
science     89
Hindi      100
1          100
Name: Suraj All Marks , dtype: int64

What if an index does not exist

In [51]:
marks_series['sst'] = 90
marks_series

Math        67
English     57
science     89
Hindi      100
1          100
sst         90
Name: Suraj All Marks , dtype: int64

Slicing

In [56]:
runs_ser[2:4] = [100, 100]
runs_ser

0     12
1    123
2    100
3    100
dtype: int64

fancy indexing

In [57]:
runs_ser[[0,3,4]] = [0,0,0]
runs_ser

KeyError: '[4] not in index'

using index label

In [58]:

bollybood['2 States (2014 film)'] = 'Alia Bhatt'
bollybood

,movie,lead,2 States (2014 film)
0,Uri: The Surgical Strike,Vicky Kaushal,Alia Bhatt
1,Battalion 609,Vicky Ahuja,Alia Bhatt
2,The Accidental Prime Minister (film),Anupam Kher,Alia Bhatt
3,Why Cheat India,Emraan Hashmi,Alia Bhatt
4,Evening Shadows,Mona Ambegaonkar,Alia Bhatt
...,...,...,...
1495,Hum Tumhare Hain Sanam,Shah Rukh Khan,Alia Bhatt
1496,Aankhen (2002 film),Amitabh Bachchan,Alia Bhatt
1497,Saathiya (film),Vivek Oberoi,Alia Bhatt
1498,Company (film),Ajay Devgn,Alia Bhatt
1499,Awara Paagal Deewana,Akshay Kumar,Alia Bhatt

## Series with Python Functionalities

len/type/dir/sorted/max/min

In [60]:
print(len(holly))
print(type(holly))
print(dir(holly))
print(sorted(holly))
print(min(holly))
print(max(holly))

365
<class 'pandas.DataFrame'>
['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append_internal', '_arith_method', '_arith_method_with_reindex', '_attrs', '_box_col_values', '_can_fast_transpose', '_check_copy_deprecation', '_check_inplace_and_allows_duplicate_labels', '_check_label_or_level_ambiguity', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_combine_frame', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_from_mgr', '_constructor_sliced', '_constructor_sliced_from_mgr', '_dir_additions', '_dir_deletions', '_dispatch_frame_op', '_drop_axis', '_drop_labels_or_levels', '_ensure_valid_index', '_find_valid_index', '_flags', '_flex_arith_method', '_flex_cmp_method', '_from_arrays', '_from_mgr', '_get_agg_axis', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_column_array', '_get_index_resolvers', '_get_item', '_get_label_or_level_values', '_get_numeric_data', '_get_value', '_get_values_for_csv', '_getitem_bool_array', '_getitem_multilevel', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_info_repr', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_homogeneous_type', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_iset_item', '_iset_item_mgr', '_iset_not_inplace', '_iter_column_arrays', '_ixs', '_logical_func', '_logical_method', '_maybe_align_series_as_frame', '_metadata', '_mgr', '_min_count_stat_function', '_needs_reindex_multi', '_pad_or_backfill', '_reduce', '_reduce_axis1', '_reindex_axes', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_columnwise', '_repr_data_resource_', '_repr_fits_horizontal_', '_repr_fits_vertical_', '_repr_html_', '_repr_latex_', '_reset_cache', '_sanitize_column', '_series', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_item', '_set_item_frame_value', '_set_item_mgr', '_set_value', '_setitem_array', '_setitem_frame', '_setitem_slice', '_shift_with_freq', '_should_reindex_frame_op', '_slice', '_stat_function', '_stat_function_ddof', '_to_dict_of_blocks', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'asfreq', 'asof', 'assign', 'astype', 'at', 'at_time', 'attrs', 'axes', 'between_time', 'bfill', 'boxplot', 'clip', 'columns', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'corrwith', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'eval', 'ewm', 'expanding', 'explode', 'ffill', 'fillna', 'filter', 'first_valid_index', 'flags', 'floordiv', 'from_arrow', 'from_dict', 'from_records', 'ge', 'get', 'groupby', 'gt', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'insert', 'interpolate', 'isetitem', 'isin', 'isna', 'isnull', 'items', 'iterrows', 'itertuples', 'join', 'keys', 'kurt', 'kurtosis', 'last_valid_index', 'le', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'melt', 'memory_usage', 'merge', 'min', 'mod', 'mode', 'mul', 'multiply', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pct_change', 'pipe', 'pivot', 'pivot_table', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'query', 'radd', 'rank', 'rdiv', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'select_dtypes', 'sem', 'set_axis', 'set_flags', 'set_index', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'stack', 'std', 'style', 'sub', 'subtract', 'sum', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_feather', 'to_hdf', 'to_html', 'to_iceberg', 'to_json', 'to_latex', 'to_markdown', 'to_numpy', 'to_orc', 'to_parquet', 'to_period', 'to_pickle', 'to_records', 'to_sql', 'to_stata', 'to_string', 'to_timestamp', 'to_xarray', 'to_xml', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']
['Subscribers gained']
Subscribers gained
Subscribers gained

type conversion

In [61]:
list(marks_series)

[67, 57, 89, 100, 100, 90]

membership operator

In [62]:
'2 States (2014 film)' in bollybood

True

In [63]:
'Alia Bhatt' in bollybood.values

True

looping

In [59]:
for i in holly.index:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364

Arithmetic Operators(Broadcasting)

In [64]:
100 + marks_series

Math       167
English    157
science    189
Hindi      200
1          200
sst        190
Name: Suraj All Marks , dtype: int64

Relational Operators

In [65]:
kohli >= 50

     match_no   runs
0       False  False
1       False  False
2       False  False
3       False  False
4       False  False
..        ...    ...
210      True  False
211      True  False
212      True   True
213      True  False
214      True  False

[215 rows x 2 columns]