# 🟢 Handling Missing Data in Pandas
1. Missing data means kisi column ya row me value ka na hona.

2. Pandas me missing values ko mostly NaN (Not a Number) se represent kiya jata hai.

Missing values usually appear as:
- `NaN`  --> Numeric missing value
- `None` --> Python ka null value
- `NaT`  --> Date/Time missing value

In [3]:
import pandas as pd
df = pd.read_excel(r"C:\EXCEL\company_data.xlsx")
df

,Code,Company Name,Value C,Value D,Value E
0,HINDCON,Hindcon Chemicals Limited,304759.0,9248.0,32.953450
1,GKWLIMITED,GKW Limited,21375.0,711.0,30.049203
2,21STCENMGM,21st Century Management Services Limited,110375.0,3879.0,NaN
3,ALPHAGEO,Alphageo (India) Limited,232755.0,8356.0,27.852613
4,UNIENT,Uniphos Enterprises Limited,162601.0,NaN,21.528002
5,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1301892.0,73134.0,17.801420
6,SKMEGGPROD,SKM Egg Products Export (India) Limited,1541130.0,87775.0,NaN
7,SWELECTES,Swelect Energy Systems Limited,NaN,87776.0,16.938733
8,NAHARPOLY,Nahar Poly Films Limited,600043.0,38574.0,15.555297
9,PODDARHOUS,Poddar Housing and Development Limited,46040.0,3012.0,15.283833
10,LINC,Linc Limited,60551.0,4076.0,14.853673
11,SHIVAMILLS,Shiva Mills Limited,142943.0,10391.0,NaN
12,PDMJEPAPER,Pudumjee Paper Products Limited,1316284.0,102646.0,12.823425
13,DSSL,Dynacons Systems & Solutions Limited,263641.0,23439.0,11.247963
14,ANDREWYU,Andrew Yule & Company Limited,2448026.0,230048.0,10.641332
15,LAXMICOT,Laxmi Cotspin Limited,NaN,NaN,10.443312
16,REPL,Rudrabhishek Enterprises Limited,660281.0,657.0,10.049914
17,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080.0,685602.0,10.011751
18,BHAGYAPROP,Bhagyanagar Properties Limited,305594.0,30596.0,NaN
19,MUNJALAU,Munjal Auto Industries Limited,705322.0,82307.0,8.569318
20,ALKALI,Alkali Metals Limited,157496.0,19059.0,8.263313
21,INTENTECH,Intense Technologies Limited,1252606.0,164644.0,7.607959
22,INDORAMA,Indo Rama Synthetics (India) Limited,679204.0,89288.0,7.606862

# 1️⃣ Detect Missing Data
- Detect Missing Data means identifying the values in a dataset that are missing or null.

# 🔹 What .isnull() / isna()
- `isnull()` is used to detect missing values in a Pandas DataFrame.

- `isna()` same as `isnull()`

1. 🔹 Check missing values
- `df.isna()`
- `df.isnull()`   # same as isna()

In [4]:
df.isnull()

     Code  Company Name  Value C  Value D  Value E
0   False         False    False    False    False
1   False         False    False    False    False
2   False         False    False    False     True
3   False         False    False    False    False
4   False         False    False     True    False
5   False         False    False    False    False
6   False         False    False    False     True
7   False         False     True    False    False
8   False         False    False    False    False
9   False         False    False    False    False
10  False         False    False    False    False
11  False         False    False    False     True
12  False         False    False    False    False
13  False         False    False    False    False
14  False         False    False    False    False
15  False         False     True     True    False
16  False         False    False    False    False
17  False         False    False    False    False
18  False         False    False    False     True
19  False         False    False    False    False
20  False         False    False    False    False
21  False         False    False    False    False
22  False         False    False    False    False

# 🔹 Count missing values
`df.isna().sum()` is used to count missing values in each column of a Pandas DataFrame.
- `df.isna().sum()`

In [5]:
df.isnull().sum()

Code            0
Company Name    0
Value C         2
Value D         2
Value E         4
dtype: int64

# 2️⃣ Remove Missing Data
Remove Missing Data means deleting rows or columns that contain missing values (`NaN, None, NaT`) from a dataset.

### 📌 dropna() Method
dropna() is used to remove missing (null) values from a Pandas DataFrame or Series.

### 🔹 Syntax
df.dropna()

In [8]:
df.dropna()

,Code,Company Name,Value C,Value D,Value E
0,HINDCON,Hindcon Chemicals Limited,304759.0,9248.0,32.953450
1,GKWLIMITED,GKW Limited,21375.0,711.0,30.049203
3,ALPHAGEO,Alphageo (India) Limited,232755.0,8356.0,27.852613
5,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1301892.0,73134.0,17.801420
8,NAHARPOLY,Nahar Poly Films Limited,600043.0,38574.0,15.555297
9,PODDARHOUS,Poddar Housing and Development Limited,46040.0,3012.0,15.283833
10,LINC,Linc Limited,60551.0,4076.0,14.853673
12,PDMJEPAPER,Pudumjee Paper Products Limited,1316284.0,102646.0,12.823425
13,DSSL,Dynacons Systems & Solutions Limited,263641.0,23439.0,11.247963
14,ANDREWYU,Andrew Yule & Company Limited,2448026.0,230048.0,10.641332
16,REPL,Rudrabhishek Enterprises Limited,660281.0,657.0,10.049914
17,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080.0,685602.0,10.011751
19,MUNJALAU,Munjal Auto Industries Limited,705322.0,82307.0,8.569318
20,ALKALI,Alkali Metals Limited,157496.0,19059.0,8.263313
21,INTENTECH,Intense Technologies Limited,1252606.0,164644.0,7.607959
22,INDORAMA,Indo Rama Synthetics (India) Limited,679204.0,89288.0,7.606862

1️⃣ Remove columns with missing values
- `df.dropna(axis=1)`

In [9]:
df.dropna(axis=0)

,Code,Company Name,Value C,Value D,Value E
0,HINDCON,Hindcon Chemicals Limited,304759.0,9248.0,32.953450
1,GKWLIMITED,GKW Limited,21375.0,711.0,30.049203
3,ALPHAGEO,Alphageo (India) Limited,232755.0,8356.0,27.852613
5,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1301892.0,73134.0,17.801420
8,NAHARPOLY,Nahar Poly Films Limited,600043.0,38574.0,15.555297
9,PODDARHOUS,Poddar Housing and Development Limited,46040.0,3012.0,15.283833
10,LINC,Linc Limited,60551.0,4076.0,14.853673
12,PDMJEPAPER,Pudumjee Paper Products Limited,1316284.0,102646.0,12.823425
13,DSSL,Dynacons Systems & Solutions Limited,263641.0,23439.0,11.247963
14,ANDREWYU,Andrew Yule & Company Limited,2448026.0,230048.0,10.641332
16,REPL,Rudrabhishek Enterprises Limited,660281.0,657.0,10.049914
17,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080.0,685602.0,10.011751
19,MUNJALAU,Munjal Auto Industries Limited,705322.0,82307.0,8.569318
20,ALKALI,Alkali Metals Limited,157496.0,19059.0,8.263313
21,INTENTECH,Intense Technologies Limited,1252606.0,164644.0,7.607959
22,INDORAMA,Indo Rama Synthetics (India) Limited,679204.0,89288.0,7.606862

 2️⃣ Remove rows where all values are missing
- `df.dropna(how='all')`

In [10]:
df.dropna(how="all")

,Code,Company Name,Value C,Value D,Value E
0,HINDCON,Hindcon Chemicals Limited,304759.0,9248.0,32.953450
1,GKWLIMITED,GKW Limited,21375.0,711.0,30.049203
2,21STCENMGM,21st Century Management Services Limited,110375.0,3879.0,NaN
3,ALPHAGEO,Alphageo (India) Limited,232755.0,8356.0,27.852613
4,UNIENT,Uniphos Enterprises Limited,162601.0,NaN,21.528002
5,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1301892.0,73134.0,17.801420
6,SKMEGGPROD,SKM Egg Products Export (India) Limited,1541130.0,87775.0,NaN
7,SWELECTES,Swelect Energy Systems Limited,NaN,87776.0,16.938733
8,NAHARPOLY,Nahar Poly Films Limited,600043.0,38574.0,15.555297
9,PODDARHOUS,Poddar Housing and Development Limited,46040.0,3012.0,15.283833
10,LINC,Linc Limited,60551.0,4076.0,14.853673
11,SHIVAMILLS,Shiva Mills Limited,142943.0,10391.0,NaN
12,PDMJEPAPER,Pudumjee Paper Products Limited,1316284.0,102646.0,12.823425
13,DSSL,Dynacons Systems & Solutions Limited,263641.0,23439.0,11.247963
14,ANDREWYU,Andrew Yule & Company Limited,2448026.0,230048.0,10.641332
15,LAXMICOT,Laxmi Cotspin Limited,NaN,NaN,10.443312
16,REPL,Rudrabhishek Enterprises Limited,660281.0,657.0,10.049914
17,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080.0,685602.0,10.011751
18,BHAGYAPROP,Bhagyanagar Properties Limited,305594.0,30596.0,NaN
19,MUNJALAU,Munjal Auto Industries Limited,705322.0,82307.0,8.569318
20,ALKALI,Alkali Metals Limited,157496.0,19059.0,8.263313
21,INTENTECH,Intense Technologies Limited,1252606.0,164644.0,7.607959
22,INDORAMA,Indo Rama Synthetics (India) Limited,679204.0,89288.0,7.606862

3️⃣ Remove rows based on specific columns
- `df.dropna(subset=['Column1', 'Column2'])`

In [ ]:
df.dropna("Value C", "Value D", "Value E")

4️⃣ Apply changes to original DataFrame
- `df.dropna(inplace=True)`

In [12]:
df.dropna(inplace=True)

In [17]:
df.isnull().sum()

Code            0
Company Name    0
Value C         0
Value D         0
Value E         0
dtype: int64

# 3️⃣ Fill Missing Data
Fill Missing Data means replacing the missing or null values (`NaN, None, NaT`) in a dataset with meaningful values instead of removing them.

### 📌 `fillna()` Method
- fillna() is used to fill (replace) missing values in a Pandas DataFrame or Series.

### 🔹 Syntax
`df.fillna(value)`

In [ ]:
df.fillna({'SYM'})

,Code,Company Name,Value C,Value D,Value E
0,HINDCON,Hindcon Chemicals Limited,304759.0,9248.0,32.953450
1,GKWLIMITED,GKW Limited,21375.0,711.0,30.049203
3,ALPHAGEO,Alphageo (India) Limited,232755.0,8356.0,27.852613
5,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1301892.0,73134.0,17.801420
8,NAHARPOLY,Nahar Poly Films Limited,600043.0,38574.0,15.555297
9,PODDARHOUS,Poddar Housing and Development Limited,46040.0,3012.0,15.283833
10,LINC,Linc Limited,60551.0,4076.0,14.853673
12,PDMJEPAPER,Pudumjee Paper Products Limited,1316284.0,102646.0,12.823425
13,DSSL,Dynacons Systems & Solutions Limited,263641.0,23439.0,11.247963
14,ANDREWYU,Andrew Yule & Company Limited,2448026.0,230048.0,10.641332
16,REPL,Rudrabhishek Enterprises Limited,660281.0,657.0,10.049914
17,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080.0,685602.0,10.011751
19,MUNJALAU,Munjal Auto Industries Limited,705322.0,82307.0,8.569318
20,ALKALI,Alkali Metals Limited,157496.0,19059.0,8.263313
21,INTENTECH,Intense Technologies Limited,1252606.0,164644.0,7.607959
22,INDORAMA,Indo Rama Synthetics (India) Limited,679204.0,89288.0,7.606862

#### 🔹 Common Examples
1️⃣ Fill with a constant value :- 
- `df.fillna(0)`

2️⃣ Fill a specific column :- 
- `df['Age'].fillna(25)`

3️⃣ Fill with mean value
- `df['Marks'].fillna(df['Marks'].mean())`

4️⃣ Forward fill (previous value)
- `df.fillna(method='ffill')`

5️⃣ Backward fill (next value)
- `df.fillna(method='bfill')`

6️⃣ Change original DataFrame :-  
- `df.fillna(0, inplace=True)`

# 4️⃣ Replace Missing / Wrong Values
Replace Missing Data means filling or substituting missing values (`NaN, None, NaT`) with meaningful values instead of removing them.

### Syntax
`df.replace()`

### 🔹 Common Ways to Replace Missing Data
🔹 Replace value with NaN
- `df.replace(-1, np.nan)`

🔹 Replace multiple values
- `df.replace(["NA", "null"], np.nan)`

🔹 Column-wise replace
- `df.replace({"Marks": {0: np.nan}})`

# 5️⃣ Interpolate Missing Data
Interpolate Missing Data means estimating and filling missing values using existing data patterns, instead of using a fixed value like 0 or mean.

### 🔹 Syntax
`df.interpolate()`

### 🔹 Common Interpolation Methods

1️⃣ Linear interpolation (default)
- `df.interpolate()`
- Fills missing values in a straight-line manner.

2️⃣ Time-based interpolation
- `df.interpolate(method='time')`
- Used when index is DateTime.

3️⃣ Forward / Backward direction
- `df.interpolate(limit_direction='forward')`