# 🔹 Indexing and Selecting in Pandas

# 🔸 What is Indexing
Indexing in pandas is the way to label and identify rows in a DataFrame or Series.

Syntax Examples

In [1]:
import pandas as pd

df = pd.DataFrame({'Name':['A','B','C'], 'Age':[20,25,30]})
print(df.index)  # Shows row labels

RangeIndex(start=0, stop=3, step=1)

# 🔹 Types of Indexing

# 1️⃣ Default Index
When you create a Pandas DataFrame or Series without specifying an index, Pandas automatically assigns a default index.

In [2]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35]
})

print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

- 0, 1, 2 → Default Index

# 2️⃣ Custom Index
Manually assigned row labels in Pandas to replace default integer index.

In [4]:
df = pd.DataFrame({'Name':['A','B','C']}, index=['x','y','z'])
df

  Name
x    A
y    B
z    C

# 3️⃣ Set a Column as Index
- Use a column’s values as row labels in Pandas with `set_index()`.

In [6]:
df = pd.DataFrame({
    'ID': [101, 102, 103],
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35]
})

# Set 'ID' column as index
df = df.set_index('ID')
print(df)

        Name  Age
ID
101    Alice   25
102      Bob   30
103  Charlie   35

# 4️⃣ Reset Index
`.reset_index()` restores the DataFrame’s index to the default integer index (0,1,2…), optionally keeping the old index as a column.

In [7]:
# Create DataFrame with custom index
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35]
}, index=['a', 'b', 'c'])

# Reset index
df_reset = df.reset_index()
print(df_reset)

  index     Name  Age
0     a    Alice   25
1     b      Bob   30
2     c  Charlie   35

# 5️⃣ Rename Index
- Definition: Use .rename() to change the name of the index (row labels) in a DataFrame or Series.

- The index values remain the same, only the name of the index changes.

In [8]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35]
})

# Rename index
df.index.rename('ID', inplace=True)
print(df)

       Name  Age
ID
0     Alice   25
1       Bob   30
2   Charlie   35

# 🔸 What is Selecting
- Selecting means extracting rows, columns, or values from a DataFrame.

- Pandas provides label-based, position-based, and conditional selection methods.

# 🔹 1. Column Selection
- Column Selection means choosing one or more columns from a DataFrame to access or manipulate their data.

1. Select single column

In [9]:
df['Name']

ID
0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

2. Select multiple columns

In [10]:
df[['Name', 'Age']]

       Name  Age
ID
0     Alice   25
1       Bob   30
2   Charlie   35

# 🔹 2. Row Selection
- Row Selection means choosing one or more rows from a DataFrame based on position, label, or condition.

- Can be done using iloc (by position), loc (by label), or boolean conditions.

1. position (`iloc`)

In [11]:
df.iloc[0]  # First row

Name    Alice
Age        25
Name: 0, dtype: object

2. label (`loc`)

In [12]:
df.loc[2]   # Row with index 2

Name    Charlie
Age          35
Name: 2, dtype: object

3. condition

In [13]:
df[df['Age'] > 25]  # Rows where Age > 25

       Name  Age
ID
1       Bob   30
2   Charlie   35

# 🔹 3. Fast Single Value Access
- access a single element in a DataFrame using row and column references.

- Done using `.at[]` (by label) or `.iat[]` (by position) for fast performance.

# Example

1. label (`.at`)

In [14]:
df.at[0, 'Name']  # Value in row 0, column 'Name'

'Alice'

2. position (`.iat`)

In [15]:
df.iat[0, 1]      # Value in first row, second column

np.int64(25)