# Write CSV

In [1]:
import pandas as pd

dis = {"A":[1, 2, 3, 4, 5, 6],"B":[1, 2, 3, 4, 5, 6], "C":[1, 2, 3, 4, 5, 6]}
d = pd.DataFrame(dis)
print(d)

d.to_csv("Test_new1.csv", index=False)

   A  B  C
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5
5  6  6  6

# Read CSV using Pandas

In [ ]:
var = pd.read_excel(r"C:\EXCEL\converted_excel.xlsx")
var

,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOLUME,CHANGE
0,ELECTHERM,Electrotherm (India) Limited,473907,9457,50.110003
1,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586
2,HINDCON,Hindcon Chemicals Limited,304759,9248,32.953450
3,GKWLIMITED,GKW Limited,21375,711,30.049203
4,21STCENMGM,21st Century Management Services,110375,3879,28.450831
5,ALPHAGEO,Alphageo (India) Limited,232755,8356,27.852613
6,UNIENTer,Uniphos Enterprises Limited,162601,7553,21.528002
7,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1301892,73134,17.801420
8,SKMEGGPROD,SKM Egg Products Export (India) Limited,1541130,87775,17.557733
9,SWELECTES,Swelect Energy Systems Limited,207954,12276,16.938733
10,NAHARPOLY,Nahar Poly Films Limited,600043,38574,15.555297
11,PODDARHOUS,Poddar Housing and Development,46040,3012,15.283833
12,LINC,Linc Limited,60551,4076,14.853673
13,SHIVAMILLS,Shiva Mills Limited,142943,10391,13.755541
14,PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,12.823425
15,DSSL,Dynacons Systems & Solutions Limited,263641,23439,11.247963
16,ANDREWYU,Andrew Yule & Company Limited,2448026,230048,10.641332
17,LAXMICOT,Laxmi Cotspin Limited,198503,19007,10.443312
18,REPL,Rudrabhishek Enterprises Limited,660281,65700,10.049914
19,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,10.011751
20,BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987766
21,MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569318
22,ALKALI,Alkali Metals Limited,157496,19059,8.263313
23,INTENTECH,Intense Technologies Limited,1252606,164644,7.607959
24,INDORAMA,Indo Rama Synthetics (India) Limited,679204,89288,7.606862

# 🔹 What is nrows in Pandas?

- nrows is a parameter used in `pd.read_csv()` (and read_excel) to read only a fixed number of rows from a file.

### 🔹 Syntax
`pd.read_csv("file.csv", nrows=number)`

# 🔹 What is `usecols`?
- usecols is used with `pd.read_csv()` / pd.`read_excel()` to read only selected columns from a file.

### 🔹 Syntax
-`pd.read_csv("file.csv", usecols=[...])`

pd.read_csv("file.csv", nrows=number)

In [8]:
var = pd.read_excel(r"C:\EXCEL\converted_excel.xlsx", usecols=[0])
var

        SYMBOL
0    ELECTHERM
1       NBIFIN
2      HINDCON
3   GKWLIMITED
4   21STCENMGM
5     ALPHAGEO
6     UNIENTer
7   JAGSNPHARM
8   SKMEGGPROD
9    SWELECTES
10   NAHARPOLY
11  PODDARHOUS
12        LINC
13  SHIVAMILLS
14  PDMJEPAPER
15        DSSL
16    ANDREWYU
17    LAXMICOT
18        REPL
19      PILITA
20  BHAGYAPROP
21    MUNJALAU
22      ALKALI
23   INTENTECH
24    INDORAMA

# 🔹 What is header in Pandas?

- header tells Pandas which row should be used as column names.

### header=0
`df = pd.read_csv("data.csv", header=0)`

In [ ]:
var = pd.read_excel(r"C:\EXCEL\converted_excel.xlsx", header=2)
var

,SYMBOL,SECURITY,TODAY - VOLUME,AVG. VOLUME,CHANGE
0,ELECTHERM,Electrotherm (India) Limited,473907,9457,50.110003
1,NBIFIN,N. B. I. Industrial Finance Company,5754,154,37.202586
2,HINDCON,Hindcon Chemicals Limited,304759,9248,32.953450
3,GKWLIMITED,GKW Limited,21375,711,30.049203
4,21STCENMGM,21st Century Management Services,110375,3879,28.450831
5,ALPHAGEO,Alphageo (India) Limited,232755,8356,27.852613
6,UNIENTer,Uniphos Enterprises Limited,162601,7553,21.528002
7,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1301892,73134,17.801420
8,SKMEGGPROD,SKM Egg Products Export (India) Limited,1541130,87775,17.557733
9,SWELECTES,Swelect Energy Systems Limited,207954,12276,16.938733
10,NAHARPOLY,Nahar Poly Films Limited,600043,38574,15.555297
11,PODDARHOUS,Poddar Housing and Development,46040,3012,15.283833
12,LINC,Linc Limited,60551,4076,14.853673
13,SHIVAMILLS,Shiva Mills Limited,142943,10391,13.755541
14,PDMJEPAPER,Pudumjee Paper Products Limited,1316284,102646,12.823425
15,DSSL,Dynacons Systems & Solutions Limited,263641,23439,11.247963
16,ANDREWYU,Andrew Yule & Company Limited,2448026,230048,10.641332
17,LAXMICOT,Laxmi Cotspin Limited,198503,19007,10.443312
18,REPL,Rudrabhishek Enterprises Limited,660281,65700,10.049914
19,PILITA,PIL ITALICA LIFESTYLE LIMITED,6864080,685602,10.011751
20,BHAGYAPROP,Bhagyanagar Properties Limited,305594,30596,9.987766
21,MUNJALAU,Munjal Auto Industries Limited,705322,82307,8.569318
22,ALKALI,Alkali Metals Limited,157496,19059,8.263313
23,INTENTECH,Intense Technologies Limited,1252606,164644,7.607959
24,INDORAMA,Indo Rama Synthetics (India) Limited,679204,89288,7.606862