# 🔹 Sorting Data in pandas

# 📌 What is Sorting Data in Pandas?

Sorting data in Pandas means arranging the rows of a DataFrame or Series in a specific order based on:

- column values
- index values

🔹 Why do we sort data?
- To analyze data easily
- To find highest / lowest values
- To make reports clean and readable

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "Marks": [78, 45, 90, 60]
})

# 🔹 Types of Sorting in Pandas

### 1️⃣ Sort by Values (Column-based sorting)
Used when you want to sort rows based on column values.

`sort_values()`

In [2]:
df.sort_values(by="Marks")

  Name  Marks
1    B     45
3    D     60
0    A     78
2    C     90

# 2️⃣ Sort by Index
Used when you want to sort rows based on index.
- sort_index()`

In [3]:
df.sort_index()

  Name  Marks
0    A     78
1    B     45
2    C     90
3    D     60

# 🔹 Sort data in ascending order (default)

In [4]:
df.sort_values(by="Marks")

  Name  Marks
1    B     45
3    D     60
0    A     78
2    C     90

🔹 Sort data in descending order

In [5]:
df.sort_values(by="Marks", ascending=False)

  Name  Marks
2    C     90
0    A     78
3    D     60
1    B     45

🔹 Sort by multiple columns

In [6]:
df.sort_values(by=["Marks", "Name"])

  Name  Marks
1    B     45
3    D     60
0    A     78
2    C     90

🔹 Sorting with missing values

In [7]:
df.sort_values(by="Marks", na_position="last")

  Name  Marks
1    B     45
3    D     60
0    A     78
2    C     90

# 3️⃣ Extract Date Components – .dt accessor

- `df['Year'] = df['Date'].dt.year`
- `df['Month'] = df['Date'].dt.month`
- `df['Day'] = df['Date'].dt.day`
- `df['Weekday'] = df['Date'].dt.day_name()`

# 4️⃣ Set Date as Index
`df.set_index('Date', inplace=True)`

# 5️⃣ Date Range – `date_range()`

In [9]:
dates = pd.date_range(start='2024-01-01', periods=5, freq='D')
print(dates)

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05'],
              dtype='datetime64[ns]', freq='D')

# 🔹 Common Frequencies
 `D` -->  Daily       
 `M` -->  Month end   
 `MS`-->  Month start 
 `Y` -->  Year end    
 `H` -->  Hourly

6️⃣ Time-Based Filtering 🔥
- `df.loc['2024-01-01':'2024-01-10']`
- `df.loc['2024-01-01':'2024-01-10']`

In [ ]:
a