In [2]:
import pandas as pd

In [9]:
dict = {'Name':['Priyang', 'Aadhya', 'Krisha', 'Vedant', 'Parshv', 'Mittal', 'Archana'],
        'Marks':[98, 89, 99, 87, 90, 83, 99],
        'Gender':['Male', 'Female', 'Female', 'Male', 'Male', 'Female', 'Female']
    }

df = pd.DataFrame(dict)
df

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

#### 1. Display Top 3 Rows of The Dataset

In [13]:
df.head(3)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female

#### 2. Check Last 3 Rows of The DataSet

In [12]:
df.tail(3)

      Name  Marks  Gender
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

#### 3. Find Shape of Our Dataset(Number of Rows & Number of Columns)

In [14]:
df.shape

(7, 3)

In [15]:
print('Number of rows', df.shape[0])
print('Number of columns', df.shape[1])

Number of rows 7
Number of columns 3

#### 4. Get Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column And Memory Requirement

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

5. Check Null Value In The DataSet

In [18]:
df.isnull().sum()

Name      0
Marks     0
Gender    0
dtype: int64

6. Get Overall Statistics About The Dataframe

In [19]:
df.describe(include='all')

           Name      Marks  Gender
count         7   7.000000       7
unique        7        NaN       2
top     Priyang        NaN  Female
freq          1        NaN       4
mean        NaN  92.142857     NaN
std         NaN   6.491753     NaN
min         NaN  83.000000     NaN
25%         NaN  88.000000     NaN
50%         NaN  90.000000     NaN
75%         NaN  98.500000     NaN
max         NaN  99.000000     NaN

7. Find Unique Value From The Gender Column

In [21]:
df

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

In [22]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

8. Find the Number of Unique value from the Gender column

In [23]:
df['Gender'].nunique()

2

Gender
Female    4
Male      3
Name: count, dtype: int64

9. Display Count of Unique Values in Gender Column

In [25]:
df['Gender'].value_counts()

Gender
Female    4
Male      3
Name: count, dtype: int64

10. Find Total Number of Student Having Between 90 To 100 (Inclusive) Using Between Method

11. Find Average Marks

12. Apply Method

13. Drop the Column(s)

14. Print Name of the Columns