# 1️⃣ Melt in pandas

# 1️⃣ What is melt?
melt in pandas is used to convert a DataFrame from wide format to long format.
- Wide format: each variable has its own column
- Long format: each variable becomes a row, with key-value pairs

# 2️⃣ Syntax
Parameter:
- `frame` --> The DataFrame to transform
- `id_vars` --> Columns to keep
- `value_vars` --> Columns to convert into rows
- `var_name` --> Name of the new column for the variable names
- `value_name` --> Name of the new column for the values

In [4]:
import pandas as pd

data = {
    'Department': ['HR', 'IT', 'Sales'],
    'F': [50000, 0, 55000],
    'M': [60000, 150000, 65000]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# Using melt
melted = pd.melt(
    df,
    id_vars=['Department'],
    value_vars=['F', 'M'],
    var_name='Gender',
    value_name='Salary'
)
print("\nMelted DataFrame:\n", melted)

Original DataFrame:
   Department      F       M
0         HR  50000   60000
1         IT      0  150000
2      Sales  55000   65000

Melted DataFrame:
   Department Gender  Salary
0         HR      F   50000
1         IT      F       0
2      Sales      F   55000
3         HR      M   60000
4         IT      M  150000
5      Sales      M   65000

In [5]:
import pandas as pd
var = pd.DataFrame({"day":[1, 2, 3, 4, 5, 6],
                    "eng":[10, 12, 14, 15, 16, 12],
                    "math":[17, 18, 19, 13, 14, 16]})
var

   day  eng  math
0    1   10    17
1    2   12    18
2    3   14    19
3    4   15    13
4    5   16    14
5    6   12    16

In [6]:
pd.melt(var)

   variable  value
0       day      1
1       day      2
2       day      3
3       day      4
4       day      5
5       day      6
6       eng     10
7       eng     12
8       eng     14
9       eng     15
10      eng     16
11      eng     12
12     math     17
13     math     18
14     math     19
15     math     13
16     math     14
17     math     16

In [9]:
pd.melt(var, id_vars=["day"], var_name="Python")

    day Python  value
0     1    eng     10
1     2    eng     12
2     3    eng     14
3     4    eng     15
4     5    eng     16
5     6    eng     12
6     1   math     17
7     2   math     18
8     3   math     19
9     4   math     13
10    5   math     14
11    6   math     16

# 1️⃣ What is a PivotTable?
- A PivotTable in pandas is used to reshape data and aggregate values.

- data by rows (index), columns, and aggregation functions (sum, mean, count, etc.)

- data analysis and reporting.

# Syntax

- pd.pivot_table(
-    data, 
-    values='column_to_aggregate',   # column to summarize
-    index='column_for_rows',        # row labels
-    columns='column_for_columns',   # column labels
-    aggfunc='sum'                   # aggregation function (sum, mean, count, etc.)
- )

# Parameter:
- `data`   --> The DataFrame to pivot
- `values` --> Column to aggregate
- `index`  --> Column to use for row labels
- `columns` --> Column to use for column labels
- `aggfunc` --> Aggregation function

In [13]:
import pandas as pd

data = {
    'Department': ['HR', 'HR', 'IT', 'IT', 'Sales', 'Sales'],
    'Gender': ['F', 'M', 'M', 'M', 'F', 'M'],
    'Salary': [50000, 60000, 70000, 80000, 55000, 65000]
}

df = pd.DataFrame(data)

# Create a PivotTable: sum of Salary by Department and Gender
pivot = pd.pivot_table(df, values='Salary', index='Department', columns='Gender', aggfunc='sum')
print(pivot)

Gender            F         M
Department
HR          50000.0   60000.0
IT              NaN  150000.0
Sales       55000.0   65000.0

# Multiple aggregation functions

In [12]:
pivot = pd.pivot_table(df, values='Salary', index='Department', columns='Gender', aggfunc=['sum', 'mean'])
print(pivot)

                sum               mean
Gender            F         M        F        M
Department
HR          50000.0   60000.0  50000.0  60000.0
IT              NaN  150000.0      NaN  75000.0
Sales       55000.0   65000.0  55000.0  65000.0